package com.aicharacter.v3;
import android.content.Context;import android.graphics.*;import android.graphics.drawable.*;import java.util.*;
/** Stable logical asset IDs with one-time bitmap decode/cache. */
public final class AssetManifest{
 private final Context context;private final Map<String,Integer> ids=new LinkedHashMap<>();private final Map<String,Bitmap> cache=new HashMap<>();public int missing=0;
 public AssetManifest(Context c){context=c;String[] names={"home_sky","home_distant","home_mid","home_ground","home_foreground","garden_sky","garden_distant","garden_mid","garden_ground","garden_foreground","lakeside_sky","lakeside_distant","lakeside_mid","lakeside_ground","lakeside_foreground","grove_sky","grove_distant","grove_mid","grove_ground","grove_foreground","girl_idle_right","girl_idle_left","girl_walk_right","girl_walk_left","girl_sit_right","girl_crouch_right","girl_sleep_right","girl_think_right","girl_search_right","girl_search_left","girl_react_right","shelter_wood","bench_wood_01","tree_autumn_02","lakeside_water_0","lakeside_water_1","lakeside_water_2","lakeside_water_3","rain_layer_0","rain_layer_1","rain_layer_2","light_evening","light_night","light_rain","home_warm_light","reedling_idle","reedling_move","reedling_forage","reedling_rest","reedling_alert","ui_panel_chat","ui_panel_god","ui_button","icon_voice","icon_god","icon_close","icon_inbox"};for(String n:names){int id=c.getResources().getIdentifier(n,"drawable",c.getPackageName());if(id!=0)ids.put(n,id);else missing++;}}
 public Bitmap get(String key){if(cache.containsKey(key))return cache.get(key);Integer id=ids.get(key);if(id==null){missing++;return null;}Drawable d=context.getDrawable(id);Bitmap b=d instanceof BitmapDrawable?((BitmapDrawable)d).getBitmap():null;if(b!=null){b.setDensity(Bitmap.DENSITY_NONE);cache.put(key,b);}else missing++;return b;}
 public void retainForArea(String area){if(area==null)return;java.util.Iterator<java.util.Map.Entry<String,Bitmap>> it=cache.entrySet().iterator();while(it.hasNext()){String k=it.next().getKey();boolean world=k.startsWith("home_")||k.startsWith("garden_")||k.startsWith("lakeside_")||k.startsWith("grove_");if(world&&!k.startsWith(area+"_"))it.remove();}}
 public int assetCount(){return ids.size();}public int loadedCount(){return cache.size();}public long estimatedBytes(){long n=0;for(Bitmap b:cache.values())n+=b.getAllocationByteCount();return n;}public String diagnostic(){return"assets="+assetCount()+" loaded="+loadedCount()+" missing="+missing+" approxBytes="+estimatedBytes();}
}
