package com.aicharacter.v3;
import org.json.*;import java.util.*;
public final class BeliefState {
 public String subject,value; public double confidence; public final List<BeliefEvidence> evidence=new ArrayList<>(); public final List<BeliefChange> history=new ArrayList<>();
 public BeliefState(String s,String v,double c){subject=s;value=v;confidence=clamp(c);}
 public void addEvidence(BeliefEvidence e){double old=confidence;evidence.add(e);trim();double support=0,contradict=0;long now=System.currentTimeMillis();for(BeliefEvidence x:evidence){double age=Math.max(0,(now-x.timestamp)/86400000.0);double rec=.45+.55*Math.exp(-age/45.0);double score=Math.max(0,x.weight)*rec;if(x.polarity>=0)support+=score*x.polarity;else contradict+=score*(-x.polarity);}double total=support+contradict;confidence=clamp(total<.001?confidence:(.15+.8*support/(total+.35)));history.add(new BeliefChange(now,old,confidence,e.evidenceId));trim();}
 /** Evidence may contradict the current value. Repeated strong contradiction can replace it while preserving history. */
 public void considerAlternative(String alternative,BeliefEvidence e){
  if(alternative==null||alternative.isEmpty()||alternative.equals(value)){addEvidence(e);return;}
  addEvidence(new BeliefEvidence(e.evidenceId,e.sourceMemoryId,e.type,-Math.abs(e.polarity),e.weight,e.timestamp,e.context));
  double alternativePressure=alternativePressure(e);if(confidence<=.30&&alternativePressure>=.50){double old=confidence;String prior=value;value=alternative;confidence=clamp(.42+Math.min(.28,alternativePressure*.22));evidence.add(new BeliefEvidence(IdFactory.next("evidence"),e.sourceMemoryId,"adopted_alternative",1,Math.max(.35,e.weight*.72),e.timestamp,e.context));history.add(new BeliefChange(e.timestamp,old,confidence,e.evidenceId+": "+prior+" -> "+alternative));trim();}
 }
 private double alternativePressure(BeliefEvidence incoming){double pressure=Math.max(0,incoming.weight)*Math.max(.25,Math.abs(incoming.polarity));long now=Math.max(System.currentTimeMillis(),incoming.timestamp);for(BeliefEvidence x:evidence){if(x.polarity>=0)continue;double age=Math.max(0,(now-x.timestamp)/86400000.0),rec=.45+.55*Math.exp(-age/45.0);pressure+=Math.max(0,x.weight)*(-x.polarity)*rec*.55;}return pressure;}
 /** Legacy migration only. New code should use addEvidence with a memory reference. */ public void revise(String newValue,double strength,String summary){if(!newValue.equals(value)&&Math.abs(strength)>.55)value=newValue;addEvidence(new BeliefEvidence(IdFactory.next("evidence"),"","legacy",newValue.equals(value)?1:-1,Math.abs(strength),System.currentTimeMillis(),summary));}
 public JSONObject toJson()throws JSONException{trim();JSONObject j=new JSONObject();j.put("subject",subject);j.put("value",value);j.put("confidence",confidence);JSONArray e=new JSONArray();for(BeliefEvidence x:evidence)e.put(x.toJson());j.put("evidenceV2",e);JSONArray h=new JSONArray();for(BeliefChange x:history)h.put(x.toJson());j.put("history",h);return j;}
 public static BeliefState fromJson(String key,JSONObject j){BeliefState b=new BeliefState(j.optString("subject",key),j.optString("value","uncertain"),j.optDouble("confidence",.4));JSONArray e=j.optJSONArray("evidenceV2");if(e!=null)for(int i=0;i<e.length();i++){JSONObject x=e.optJSONObject(i);if(x!=null)b.evidence.add(BeliefEvidence.fromJson(x));}else{JSONArray old=j.optJSONArray("evidence");if(old!=null)for(int i=0;i<old.length();i++)b.evidence.add(new BeliefEvidence(IdFactory.next("evidence"),"","legacy",1,.15,System.currentTimeMillis(),old.optString(i)));}JSONArray h=j.optJSONArray("history");if(h!=null)for(int i=0;i<h.length();i++){JSONObject x=h.optJSONObject(i);if(x!=null)b.history.add(BeliefChange.fromJson(x));}b.trim();return b;}
 private void trim(){while(evidence.size()>24)evidence.remove(0);while(history.size()>20)history.remove(0);}
 private static double clamp(double v){return Math.max(0,Math.min(1,v));}
}
