package com.aicharacter.v3;
import org.json.*;import java.util.*;
public final class BeliefState {
 public String subject,value; public double confidence; public final List<BeliefEvidence> evidence=new ArrayList<>(); public final List<BeliefChange> history=new ArrayList<>();
 public BeliefState(String s,String v,double c){subject=s;value=v;confidence=clamp(c);}
 public void addEvidence(BeliefEvidence e){double old=confidence;evidence.add(e);while(evidence.size()>24)evidence.remove(0);double support=0,contradict=0;long now=System.currentTimeMillis();for(BeliefEvidence x:evidence){double age=Math.max(0,(now-x.timestamp)/86400000.0);double rec=.45+.55*Math.exp(-age/45.0);double score=Math.max(0,x.weight)*rec;if(x.polarity>=0)support+=score*x.polarity;else contradict+=score*(-x.polarity);}double total=support+contradict;confidence=clamp(total<.001?confidence:(.15+.8*support/(total+.35)));history.add(new BeliefChange(now,old,confidence,e.evidenceId));while(history.size()>20)history.remove(0);}
 /** Legacy migration only. New code should use addEvidence with a memory reference. */ public void revise(String newValue,double strength,String summary){if(!newValue.equals(value)&&Math.abs(strength)>.55)value=newValue;addEvidence(new BeliefEvidence(IdFactory.next("evidence"),"","legacy",newValue.equals(value)?1:-1,Math.abs(strength),System.currentTimeMillis(),summary));}
 public JSONObject toJson()throws JSONException{JSONObject j=new JSONObject();j.put("subject",subject);j.put("value",value);j.put("confidence",confidence);JSONArray e=new JSONArray();for(BeliefEvidence x:evidence)e.put(x.toJson());j.put("evidenceV2",e);JSONArray h=new JSONArray();for(BeliefChange x:history)h.put(x.toJson());j.put("history",h);return j;}
 public static BeliefState fromJson(String key,JSONObject j){BeliefState b=new BeliefState(j.optString("subject",key),j.optString("value","uncertain"),j.optDouble("confidence",.4));JSONArray e=j.optJSONArray("evidenceV2");if(e!=null)for(int i=0;i<e.length();i++)b.evidence.add(BeliefEvidence.fromJson(e.optJSONObject(i)));else{JSONArray old=j.optJSONArray("evidence");if(old!=null)for(int i=0;i<old.length();i++)b.evidence.add(new BeliefEvidence(IdFactory.next("evidence"),"","legacy",1,.15,System.currentTimeMillis(),old.optString(i)));}JSONArray h=j.optJSONArray("history");if(h!=null)for(int i=0;i<h.length();i++)b.history.add(BeliefChange.fromJson(h.optJSONObject(i)));return b;} private static double clamp(double v){return Math.max(0,Math.min(1,v));}
}
