package com.aicharacter.v3;
/** Converts hidden physiology numbers into bounded subjective experiences. Never exposes engine values to the girl. */
public final class BodyPerceptionEngine{private BodyPerceptionEngine(){}
 public static void observe(WorldState s,long now){if(s==null)return;ThermalState t=s.thermal;RespirationState r=s.respiration;if(t!=null){if(t.coldLoad>=.58)emit(s,now,"body_cold","The air and dampness left her feeling distinctly cold.",-.18,.42,"cold","body");else if(t.heatLoad>=.62)emit(s,now,"body_heat","The warmth had become tiring and uncomfortable.",-.16,.40,"heat","body");}
  if(r!=null&&r.breathingLoad>=.48)emit(s,now,"breathing_strain","Breathing felt more effortful than usual.",-.24,.52,"breathing","body");
  double hunger=DigestionHydrationEngine.hunger(s),thirst=DigestionHydrationEngine.thirst(s),bladder=DigestionHydrationEngine.bladderUrgency(s);if(hunger>=.58)emit(s,now,"body_hunger",hunger>.82?"Her stomach felt distinctly empty and her energy was beginning to dip.":"She noticed a clear sense of hunger.",-.10,Math.min(.65,.28+hunger*.35),"hunger","body");if(thirst>=.50)emit(s,now,"body_thirst",thirst>.78?"Her mouth felt dry and her body was asking urgently for water.":"She noticed that she was getting thirsty.",-.14,Math.min(.72,.30+thirst*.38),"thirst","body");if(bladder>=.58)emit(s,now,"body_bladder","The pressure in her bladder had become hard to ignore.",-.08,Math.min(.58,.25+bladder*.30),"bladder","body");
  if(s.endocrine!=null&&s.endocrine.stressResponse>=.58)emit(s,now,"body_systemic_stress",s.endocrine.stressResponse>.78?"Her whole body felt wound tight and unable to settle.":"She felt a persistent physical tension that made it harder to relax.",-.15,Math.min(.70,.30+s.endocrine.stressResponse*.40),"stress","body");if(s.skin!=null&&Math.max(s.skin.irritation,s.skin.moistureExposure)>=.52)emit(s,now,"skin_discomfort",s.skin.irritation>.68?"Her skin felt distinctly irritated and uncomfortable.":"Her skin felt damp or mildly irritated.",-.10,Math.min(.58,.24+Math.max(s.skin.irritation,s.skin.moistureExposure)*.35),"skin","body");if(s.immune!=null&&s.immune.inflammation>=.50)emit(s,now,"body_inflammatory_fatigue",s.immune.inflammation>.72?"Her body felt unusually heavy and achy, as if recovery was taking effort.":"She noticed a vague heaviness and body-wide fatigue.",-.17,Math.min(.68,.30+s.immune.inflammation*.38),"inflammation","body","recovery");
  HumanAnatomyModel.Region region=HumanAnatomyModel.dominantPainRegion(s);if(region!=null){double load=HumanAnatomyModel.painLoad(s,region);if(load>=.28){String label=HumanAnatomyModel.info(region).label;emit(s,now,"regional_pain_"+region.name().toLowerCase(),"Pain was clearly concentrated around her "+label+".",-.28,Math.min(.8,.35+load*.45),"pain","body","region:"+region.name().toLowerCase());}}
 }
 private static void emit(WorldState s,long now,String kind,String summary,double valence,double significance,String...tags){long window=45L*60000L;for(int i=s.memories.size()-1;i>=0;i--){MemoryEntry m=s.memories.get(i);if(now-m.time>window)break;if(kind.equals(m.kind))return;}CognitionEngine.experience(s,now,kind,summary,valence,significance,tags);}
}