package com.aicharacter.v3;
/** Muscle work, heat, hydration, nutrition and respiration jointly determine circulatory/metabolic support and recovery. */
public final class CardioMetabolicEngine{private CardioMetabolicEngine(){}
 public static void advance(WorldState s,double dt){if(s==null||dt<=0)return;if(s.circulation==null)s.circulation=new CirculationState();if(s.metabolism==null)s.metabolism=new MetabolismState();double work=s.girlTravel!=null&&s.girlTravel.active?Math.min(1,s.girlTravel.lastSpeed/92.0):0;double fatigue=s.musculoskeletal==null?0:s.musculoskeletal.legFatigue;double stress=s.endocrine==null?0:s.endocrine.stressResponse;double thermal=s.thermal==null?0:Math.max(s.thermal.heatLoad,s.thermal.coldLoad),shiver=s.bodyInstinct==null?0:s.bodyInstinct.shiver,digestion=s.digestive==null?0:s.digestive.digestionLoad;double demand=Math.min(1,.15+work*.56+fatigue*.14+stress*.07+thermal*.10+shiver*.08+digestion*.05);s.metabolism.demand=follow(s.metabolism.demand,demand,dt,2.5);
  RespirationState r=s.respiration;double respiratory=r==null?1:Math.max(.08,Math.min(1,r.oxygenSaturation*(1-r.breathingLoad*.42)));double hydration=s.hydration==null?1:Math.max(.20,Math.min(1,s.hydration.hydration)),dehydration=Math.max(0,.72-hydration)/.72,heat=s.thermal==null?0:s.thermal.heatLoad;
  s.circulation.cardiacDrive=follow(s.circulation.cardiacDrive,Math.min(1,.24+demand*.62+stress*.09+heat*.10+dehydration*.12),dt,3.0);double volumeFactor=.60+.40*hydration;s.circulation.perfusion=Math.max(.16,Math.min(1,(.52+s.circulation.cardiacDrive*.52)*volumeFactor*(1-dehydration*.12)));s.circulation.oxygenDelivery=Math.max(.06,Math.min(1,respiratory*s.circulation.perfusion));
  double shortage=Math.max(0,s.metabolism.demand-s.circulation.oxygenDelivery);s.metabolism.oxygenDebt=integrateBounded(s.metabolism.oxygenDebt,shortage*.09,s.metabolism.oxygenDebt*.018,dt);double workAboveRest=Math.max(0,s.metabolism.demand-.18);if(s.body!=null){s.body.energy=Math.max(0,s.body.energy-workAboveRest*(1.8/3600.0)*dt);s.body.sleepiness=Math.min(100,s.body.sleepiness+work*(.7/3600.0)*dt);}
  double nutrient=s.digestive==null?1:Math.max(.25,Math.min(1,s.digestive.nutrientReserve)),fuelFactor=.68+.32*nutrient,endocrineSupport=s.endocrine==null?1:(.76+.24*s.endocrine.metabolicSupport);s.metabolism.availableEnergy=cl((s.body==null?1:s.body.energy/100.0)*fuelFactor*(.70+.30*hydration)*endocrineSupport*(1-s.metabolism.oxygenDebt*.55));s.metabolism.metabolicHeat=cl(.1+s.metabolism.demand*.68+shiver*.10);
 }
 private static double follow(double v,double t,double dt,double tau){double k=1-Math.exp(-dt/Math.max(.1,tau));return v+(t-v)*k;}private static double integrateBounded(double v,double gain,double loss,double dt){double rate=gain-loss;if(Math.abs(rate)<1e-12)return cl(v);double target=rate>0?1:0,tau=Math.max(.1,Math.abs((target-v)/rate));return cl(target+(v-target)*Math.exp(-dt/tau));}private static double cl(double v){return Math.max(0,Math.min(1,v));}}
