package com.aicharacter.v3;
/** Persistent cat life: decisions may choose a destination, but physical travel/contact must happen before sleep/attachment. */
public final class CatOfflineEngine{private CatOfflineEngine(){}private static final float ATTACH_RANGE=70f;
 public static String beginSleep(WorldState s,long now){CatState c=s.catState;if(!c.awake)return"already offline "+c.sleepMode;c.x=s.catX;c.areaId=area(s,c.x);c.sleepiness=Math.min(100,c.sleepiness+12);c.lastUpdatedAt=now;CatSleepPlanner.Plan p=CatSleepPlanner.choose(s);c.sleepAreaId=p.areaId;c.sleepDestination=p.areaId;c.sleepTargetEntity=p.targetEntity;c.sleepStartedAt=now;c.actualSleepStartedAt=0;c.lastSleepPlanReason=p.reason;c.awake=false;c.attachedToEntity="";c.attachmentContext="";c.carryKnownByGirl=false;String eid="cat_sleep_plan_"+Long.toHexString(now);WorldEventBus.publishId(s,now,eid,"CAT_SLEEP_PLAN_SELECTED","cat",p.mode+" → "+p.areaId+" because "+p.reason);if("WITH_GIRL".equals(p.mode)){c.sleepMode="APPROACHING_GIRL";c.approachTarget="girl";startApproachGirl(s,now);}else{c.sleepMode="TRAVELLING_TO_"+p.mode;c.approachTarget="";startTravel(s,p,now);}s.catX=c.x;return"selected "+p.mode+" physicalState="+c.sleepMode+" route="+s.catTravel.route;}
 private static void startApproachGirl(WorldState s,long now){CatState c=s.catState;if(c.energy<8||c.sleepiness>96){fallbackSafe(s,now,"too tired to finish approach");return;}String ga=area(s,s.haruX);if(sameAreaAndNear(s)){attach(s,now);return;}String id="cat_with_girl_"+Long.toHexString(c.sleepStartedAt);boolean started=area(s,c.x).equals(ga)?TravelEngine.startLocal(s,s.catTravel,"cat","girl",s.haruX,ATTACH_RANGE,id,now):TravelEngine.start(s,s.catTravel,"cat",ga,id,now);if(!started)fallbackSafe(s,now,"girl approach route unavailable");}
 private static void fallbackSafe(WorldState s,long now,String why){CatSleepPlanner.Plan alt=bestNonGirl(s);s.catState.sleepMode="TRAVELLING_TO_"+alt.mode;s.catState.sleepAreaId=alt.areaId;s.catState.sleepDestination=alt.areaId;s.catState.sleepTargetEntity=alt.targetEntity;s.catState.lastSleepPlanReason=why+"; "+alt.reason;s.catState.approachTarget="";startTravel(s,alt,now);}
 private static CatSleepPlanner.Plan bestNonGirl(WorldState s){for(CatSleepPlanner.Plan p:CatSleepPlanner.candidates(s))if(!"WITH_GIRL".equals(p.mode)&&!"NEAR_GIRL".equals(p.mode))return p;return CatSleepPlanner.choose(s);}
 private static void startTravel(WorldState s,CatSleepPlanner.Plan p,long now){String plan="cat_sleep_"+Long.toHexString(s.catState.sleepStartedAt);String here=area(s,s.catState.x);if(here.equals(p.areaId)){if("NEAR_GIRL".equals(p.mode)){float tx=s.haruX+(s.catState.x<=s.haruX?-90:90);if(TravelEngine.startLocal(s,s.catTravel,"cat","near_girl",tx,45,plan,now))return;}WorldObject o=s.world.object(p.targetEntity);if(o!=null&&Math.abs(s.catState.x-o.x)>Math.max(30,o.interactionRadius)){if(TravelEngine.startLocal(s,s.catTravel,"cat",o.id,o.x,Math.max(30,o.interactionRadius),plan,now))return;if(!isLocallySafe(s,here)){settleWhereActuallySafe(s,now,"local sleep target became unreachable");return;}}finishSleepArrival(s,p.mode,now);return;}if(!TravelEngine.start(s,s.catTravel,"cat",p.areaId,plan,now))settleWhereActuallySafe(s,now,"planned sleep route became unavailable");}
 private static void settleWhereActuallySafe(WorldState s,long now,String why){String here=area(s,s.catState.x);if(isLocallySafe(s,here)){s.catState.lastSleepPlanReason=why+"; stayed in a physically valid local safe context";finishSleepArrival(s,"SAFE_SPOT",now);return;}CatSleepPlanner.Plan alt=bestReachableNonGirl(s,here);if(alt!=null){s.catState.sleepMode="TRAVELLING_TO_"+alt.mode;s.catState.sleepAreaId=alt.areaId;s.catState.sleepDestination=alt.areaId;s.catState.sleepTargetEntity=alt.targetEntity;s.catState.lastSleepPlanReason=why+"; replanned to "+alt.reason;if(TravelEngine.start(s,s.catTravel,"cat",alt.areaId,"cat_sleep_"+Long.toHexString(s.catState.sleepStartedAt),now))return;}s.catState.sleepMode="RESTING_WHERE_STRANDED";s.catState.actualSleepStartedAt=now;s.catState.sleepAreaId=here;s.catState.sleepDestination=here;s.catState.sleepTargetEntity="";s.catState.lastSleepPlanReason=why+"; no reachable safe destination, so the cat remained at its actual location";s.catTravel.active=false;WorldEventBus.publishId(s,now,"cat_stranded_"+Long.toHexString(s.catState.sleepStartedAt),"CAT_SLEEP_ROUTE_FAILED","cat","Cat could not reach a planned safe sleep location and remained at "+here+".");}
 private static CatSleepPlanner.Plan bestReachableNonGirl(WorldState s,String here){for(CatSleepPlanner.Plan q:CatSleepPlanner.candidates(s))if(!"WITH_GIRL".equals(q.mode)&&!"NEAR_GIRL".equals(q.mode)&&!here.equals(q.areaId)&&Double.isFinite(WorldPathPlanner.routeCost(s,"cat",here,q.areaId)))return q;return null;}
 private static boolean isLocallySafe(WorldState s,String areaId){WorldArea a=s.world.area(areaId);if(a==null)return false;if("home_shelter".equals(areaId))return true;WorldObject safe=s.world.firstTagged("safe");return safe!=null&&areaId.equals(safe.areaId);}
 public static void advanceSleepTravel(WorldState s,double minutes,long now){CatState c=s.catState;if(c.awake)return;long previous=c.lastUpdatedAt;c.lastUpdatedAt=now;if(c.actualSleepStartedAt>0&&!s.catTravel.active&&isActualSleepMode(c.sleepMode)){double elapsed=previous>0?Math.max(0,now-Math.max(previous,c.actualSleepStartedAt))/60000.0:Math.max(0,minutes);recoverSleepingCat(c,elapsed);}if("APPROACHING_GIRL".equals(c.sleepMode)){String girlArea=area(s,s.haruX);boolean targetMoved="LOCAL".equals(s.catTravel.travelMode)&&Math.abs(s.haruX-s.catTravel.segmentEndX)>ATTACH_RANGE;if(s.catTravel.active&&(!girlArea.equals(s.catTravel.destinationArea)||targetMoved)){s.catTravel.active=false;startApproachGirl(s,now);}}if(s.catTravel.active){TravelEngine.advanceMinutes(s,s.catTravel,minutes,now);}if("APPROACHING_GIRL".equals(c.sleepMode)&&!s.catTravel.active){if(sameAreaAndNear(s))attach(s,now);else startApproachGirl(s,now);}}
 public static void onCatTravelArrival(WorldState s,TravelState t,long now){CatState c=s.catState;c.areaId=area(s,c.x);if("APPROACHING_GIRL".equals(c.sleepMode)){if(sameAreaAndNear(s))attach(s,now);else startApproachGirl(s,now);return;}String mode=c.sleepMode.startsWith("TRAVELLING_TO_")?c.sleepMode.substring("TRAVELLING_TO_".length()):c.sleepMode;if("ROUTE".equals(t.travelMode)){if("NEAR_GIRL".equals(mode)){float target=s.haruX+(c.x<=s.haruX?-90:90);if(TravelEngine.startLocal(s,s.catTravel,"cat","near_girl",target,45,t.currentPlanId,now))return;}WorldObject o=s.world.object(c.sleepTargetEntity);if(o!=null&&c.areaId.equals(o.areaId)&&Math.abs(c.x-o.x)>Math.max(30,o.interactionRadius)){if(TravelEngine.startLocal(s,s.catTravel,"cat",o.id,o.x,Math.max(30,o.interactionRadius),t.currentPlanId,now))return;}}finishSleepArrival(s,mode,now);}
 private static void finishSleepArrival(WorldState s,String mode,long now){CatState c=s.catState;c.areaId=area(s,c.x);c.sleepAreaId=c.areaId;c.sleepMode=mode;c.actualSleepStartedAt=now;count(c,mode);WorldEventBus.publishId(s,now,"cat_sleep_arrive_"+Long.toHexString(c.sleepStartedAt),"CAT_REACHED_SLEEP_LOCATION","cat",mode+" at "+c.areaId);WorldEventBus.publishId(s,now,"cat_asleep_"+Long.toHexString(c.sleepStartedAt),"CAT_FELL_ASLEEP","cat",mode+" at "+c.areaId);}
 private static void attach(WorldState s,long now){CatState c=s.catState;if(!sameAreaAndNear(s)||s.catTravel.active)return;c.attachedToEntity="girl";c.attachmentContext="bag";c.carryKnownByGirl=true;c.sleepMode="WITH_GIRL";c.actualSleepStartedAt=now;c.approachTarget="";c.withGirlSleeps++;c.x=s.haruX;s.catX=s.haruX;c.areaId=area(s,s.haruX);WorldEventBus.publishId(s,now,"cat_attach_"+Long.toHexString(c.sleepStartedAt),"CAT_ATTACHED_TO_GIRL","girl","Cat physically reached the girl; she knowingly accepted the cat into a safe carried context.");WorldEventBus.publishId(s,now,"cat_asleep_"+Long.toHexString(c.sleepStartedAt),"CAT_FELL_ASLEEP","cat","WITH_GIRL carried in "+c.attachmentContext);CognitionEngine.process(s,new Experience("carrying_cat","She knows the cat is resting with her in a carried context.",.18,.72).atTime(now).at(c.areaId,"girl").tag("cat").tag("carried"));}
 public static void followAttachment(WorldState s){CatState c=s.catState;if("girl".equals(c.attachedToEntity)){c.x=s.haruX;s.catX=s.haruX;c.areaId=area(s,s.haruX);c.carryKnownByGirl=true;s.catTravel.active=false;}}
 /** Player return wakes awareness/control but preserves carried attachment. */
 public static void wakeForPlayer(WorldState s,long now){CatState c=s.catState;if(c.awake)return;if(c.actualSleepStartedAt>0&&c.lastUpdatedAt>0&&now>c.lastUpdatedAt)recoverSleepingCat(c,(now-c.lastUpdatedAt)/60000.0);if("girl".equals(c.attachedToEntity)){followAttachment(s);c.sleepMode="WITH_GIRL_AWAKE";}else c.sleepMode="AWAKE";c.awake=true;c.actualSleepStartedAt=0;c.lastPlayerActiveAt=now;c.lastUpdatedAt=now;WorldEventBus.publishId(s,now,"cat_woke_"+Long.toHexString(now),"CAT_WOKE","cat","Player returned and the cat woke in its actual persistent context.");}
 public static boolean detachToNearbyGround(WorldState s,long now){CatState c=s.catState;if(!c.awake||!"girl".equals(c.attachedToEntity))return false;WorldArea a=s.world.areaAt(s.haruX);if(a==null)return false;float nx=Math.max(a.left+24,Math.min(a.right-24,s.haruX+56));c.x=nx;s.catX=nx;c.areaId=a.id;c.attachedToEntity="";c.attachmentContext="";c.carryKnownByGirl=false;c.sleepMode="AWAKE";WorldEventBus.publishId(s,now,"cat_detach_"+Long.toHexString(now),"CAT_DETACHED","cat","Cat climbed out to nearby valid ground in "+a.id+".");return true;}
 public static String attachTrace(WorldState s){return"Sleep state="+s.catState.sleepMode+" catArea="+area(s,s.catState.x)+" girlArea="+area(s,s.haruX)+" route="+s.catTravel.route+" distance="+(int)Math.abs(s.catState.x-s.haruX)+" range="+(int)ATTACH_RANGE+" allowed="+sameAreaAndNear(s)+" attached="+s.catState.attachedToEntity+" knownByGirl="+s.catState.carryKnownByGirl;}
 private static boolean isActualSleepMode(String mode){return "HOME".equals(mode)||"SAFE_SPOT".equals(mode)||"NEAR_GIRL".equals(mode)||"WITH_GIRL".equals(mode)||"RESTING_WHERE_STRANDED".equals(mode);}\n private static void recoverSleepingCat(CatState c,double minutes){if(minutes<=0)return;c.energy=Math.min(100,c.energy+minutes*(7.0/60.0));c.sleepiness=Math.max(0,c.sleepiness-minutes*(9.0/60.0));}\n private static boolean sameAreaAndNear(WorldState s){return area(s,s.catState.x).equals(area(s,s.haruX))&&Math.abs(s.catState.x-s.haruX)<=ATTACH_RANGE;}
 private static void count(CatState c,String m){if("HOME".equals(m))c.homeSleeps++;else if("SAFE_SPOT".equals(m))c.safeSpotSleeps++;else if("NEAR_GIRL".equals(m))c.nearGirlSleeps++;}
 private static String area(WorldState s,float x){WorldArea a=s.world.areaAt(x);return a==null?"garden_path":a.id;}
}
