package com.aicharacter.v3;import java.util.*;
public final class CognitionEngine {private CognitionEngine(){}
 public static MemoryEntry experience(WorldState s,String kind,String summary,double valence,double significance,String...tags){return experience(s,System.currentTimeMillis(),kind,summary,valence,significance,tags);} public static MemoryEntry experience(WorldState s,long now,String kind,String summary,double valence,double significance,String...tags){Experience e=new Experience(kind,summary,valence,significance).atTime(now).at(HaruPerception.currentPlaceId(s),"").with("cat");for(String t:tags)e.tag(t);return process(s,e);}
 public static MemoryEntry experienceAt(WorldState s,String kind,String summary,double valence,double significance,String semanticLocation,String...tags){Experience e=new Experience(kind,summary,valence,significance).at(semanticLocation,semanticLocation).with("cat");for(String t:tags)e.tag(t);return process(s,e);}
 public static MemoryEntry process(WorldState s,Experience e){List<String> tags=new ArrayList<>(e.tags);if(e.objectId!=null&&!e.objectId.isEmpty())tags.add(e.objectId);MemoryEntry m=new MemoryEntry(e.timestamp,e.type,e.perceivedEvent,e.significance,e.valence,.9,e.locationId==null?"":e.locationId,e.participants,tags);s.memories.add(m);WorldEventBus.publishId(s,m.time,"experience_"+m.memoryId,"HARU_EXPERIENCE",m.location,m.summary);applyConsequences(s,m,e);CharacterLearningEngine.learnOutcome(s,m,e.experienceId);MemoryConsolidationEngine.consolidate(s,m.time);return m;}
 private static void applyConsequences(WorldState s,MemoryEntry m,Experience e){if(m.hasTag("respect")){s.relationship.trust+=.35*m.importance;s.relationship.comfort+=.25*m.importance;revise(s,"cat_intent","respectful",.7*m.importance,m.summary);}if(m.hasTag("control")){s.relationship.irritation+=1.1*m.importance;s.relationship.hurt+=.35*m.importance;s.emotion.anger=Math.min(1,s.emotion.anger+.25);revise(s,"cat_intent","controlling",.9*m.importance,m.summary);}if(m.hasTag("kind")){s.relationship.gratitude+=.3*m.importance;s.relationship.affection+=.18*m.importance;s.emotion.joy=Math.min(1,s.emotion.joy+.15);}if(m.hasTag("absence")){s.emotion.loneliness=Math.min(1,s.emotion.loneliness+.18*m.importance);s.mood.loneliness=Math.min(1,s.mood.loneliness+.08*m.importance);}s.mood.absorb(m.valence,m.importance);s.relationship.clamp();s.haruMood=s.mood.label();}
 public static void revise(WorldState s,String subject,String value,double strength,String evidence){reviseAt(s,subject,value,strength,evidence,System.currentTimeMillis());}
 public static void reviseAt(WorldState s,String subject,String value,double strength,String evidence,long now){MemoryEntry m=new MemoryEntry(now,"belief_evidence",evidence,Math.min(1,Math.max(.2,Math.abs(strength))),strength>=0?.1:-.1,.85,HaruPerception.currentPlaceId(s),null,Arrays.asList("belief_evidence",subject));s.memories.add(m);reviseFromMemory(s,subject,value,strength>=0?1:-1,Math.abs(strength),m);}
 public static void reviseFromMemory(WorldState s,String subject,String value,double polarity,double weight,MemoryEntry source){BeliefState b=s.beliefStates.get(subject);if(b==null){b=new BeliefState(subject,value,.35);s.beliefStates.put(subject,b);}BeliefEvidence ev=new BeliefEvidence(IdFactory.next("evidence"),source==null?"":source.memoryId,"memory",polarity,Math.max(.05,weight)*(source==null?1:source.confidence)*(source==null?1:.5+.5*source.importance),source==null?System.currentTimeMillis():source.time,source==null?"":source.summary);if(!value.equals(b.value)&&polarity>0)b.considerAlternative(value,ev);else b.addEvidence(ev);}
 public static double recalledValence(WorldState s,String tag){return recalledValence(s,tag,System.currentTimeMillis());} public static double recalledValence(WorldState s,String tag,long now){List<MemoryEntry> ms=MemoryRetrievalEngine.retrieve(s,HaruPerception.currentPlaceId(s),null,tag,s.currentIntention,12,now);double sum=0,w=0;for(MemoryEntry m:ms)if(m.hasTag(tag)){double rw=MemoryRetrievalEngine.score(m,now,HaruPerception.currentPlaceId(s),null,tag,s);sum+=m.valence*rw;w+=rw;}return w==0?0:sum/w;}
 public static double placeAttraction(WorldState s,String id){PlaceAssociation a=s.placeAssociations.get(id);PreferenceState p=s.preferences.get("place:"+id);return(a==null?0:a.attraction())+(p==null?0:p.value*.5);}
 public static String timeContext(double minutes){double h=minutes/60;return h<6?"night":h<11?"morning":h<17?"day":h<21?"evening":"night";}
}
