package com.aicharacter.v3;
import org.json.JSONObject;
/** Persistent body/senses/motion for every authored non-human VNF creature. No Earth anatomy assumptions. */
public final class CreatureLifeState{
 public OrganismBodyState body=new OrganismBodyState();public OrganismSenseState sense=new OrganismSenseState();public OrganismCycleState cycle=new OrganismCycleState();
 public float x;public String areaId="",activity="rest",ecologyTargetAreaId="";public double hunger=.30,locomotionDrive=.20,avoidance=.10,curiosity=.22,relationPressure=.0,migrationIntent=.0,velocityXMps,verticalOffsetM,velocityYMps;public int heading=1;public boolean grounded=true;public long lastUpdatedAt;
 public JSONObject toJson(){JSONObject j=new JSONObject();try{j.put("body",body.toJson());j.put("sense",sense.toJson());j.put("cycle",cycle.toJson());j.put("x",x);j.put("areaId",areaId);j.put("activity",activity);j.put("ecologyTargetAreaId",ecologyTargetAreaId);j.put("hunger",hunger);j.put("locomotionDrive",locomotionDrive);j.put("avoidance",avoidance);j.put("curiosity",curiosity);j.put("relationPressure",relationPressure);j.put("migrationIntent",migrationIntent);j.put("velocityXMps",velocityXMps);j.put("verticalOffsetM",verticalOffsetM);j.put("velocityYMps",velocityYMps);j.put("heading",heading);j.put("grounded",grounded);j.put("lastUpdatedAt",lastUpdatedAt);}catch(Exception ignored){}return j;}
 public static CreatureLifeState fromJson(JSONObject j){CreatureLifeState c=new CreatureLifeState();if(j==null)return c;c.body=OrganismBodyState.fromJson(j.optJSONObject("body"));c.sense=OrganismSenseState.fromJson(j.optJSONObject("sense"));c.cycle=OrganismCycleState.fromJson(j.optJSONObject("cycle"));c.x=(float)j.optDouble("x");c.areaId=j.optString("areaId","");c.activity=j.optString("activity","rest");c.ecologyTargetAreaId=j.optString("ecologyTargetAreaId","");c.hunger=cl(j.optDouble("hunger",c.hunger));c.locomotionDrive=cl(j.optDouble("locomotionDrive",c.locomotionDrive));c.avoidance=cl(j.optDouble("avoidance",c.avoidance));c.curiosity=cl(j.optDouble("curiosity",c.curiosity));c.relationPressure=cl(j.optDouble("relationPressure"));c.migrationIntent=cl(j.optDouble("migrationIntent"));c.velocityXMps=j.optDouble("velocityXMps",0);c.verticalOffsetM=Math.max(0,j.optDouble("verticalOffsetM",0));c.velocityYMps=j.optDouble("velocityYMps",0);c.heading=j.optInt("heading",1)<0?-1:1;c.grounded=j.optBoolean("grounded",c.verticalOffsetM<=.02);c.lastUpdatedAt=j.optLong("lastUpdatedAt");return c;}
 private static double cl(double v){return Math.max(0,Math.min(1,v));}
}