package com.aicharacter.v3;

import android.content.Context;
import android.graphics.*;
import android.view.View;

/** Full-screen non-human manifestation. It visualizes session phase only; it never creates world state. */
public final class DivineManifestationView extends View {
    public enum Phase { CONNECTING, PRESENT, THINKING, SPEAKING, WARNING, OBSERVING, APPLYING, DEGRADED, DISAPPEARING }
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
    private Phase phase=Phase.CONNECTING;private long phaseAt=System.currentTimeMillis();
    public DivineManifestationView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
    public Phase phase(){return phase;}
    public void setPhase(Phase next){if(next==null)next=Phase.DEGRADED;if(phase!=next){phase=next;phaseAt=System.currentTimeMillis();}invalidate();}
    @Override protected void onDraw(Canvas c){super.onDraw(c);long now=System.currentTimeMillis();float t=(now-phaseAt)/1000f,cx=getWidth()*.5f,cy=getHeight()*.43f,pulse=(float)(.5+.5*Math.sin(now/520.0)),strength=strength();if(phase==Phase.DISAPPEARING)strength=Math.max(0f,1f-t/.55f);drawVeil(c,cx,cy,pulse,strength);drawRays(c,cx,cy,t,strength);drawOrbit(c,cx,cy,t,pulse,strength);drawSigil(c,cx,cy,t,pulse,strength);drawMotes(c,cx,cy,t,strength);if((phase!=Phase.DISAPPEARING&&phase!=Phase.DEGRADED)||(phase==Phase.DISAPPEARING&&strength>0))postInvalidateDelayed(33);}
    private float strength(){switch(phase){case DEGRADED:return .32f;case CONNECTING:return .58f;case WARNING:return 1f;case APPLYING:return .96f;default:return .88f;}}
    private void drawVeil(Canvas c,float cx,float cy,float pulse,float s){float d=getResources().getDisplayMetrics().density,r=220*d+pulse*28*d;p.setStyle(Paint.Style.FILL);p.setShader(new RadialGradient(cx,cy,r,new int[]{Color.argb((int)(66*s),239,224,172),Color.argb((int)(28*s),132,192,199),Color.TRANSPARENT},new float[]{0f,.38f,1f},Shader.TileMode.CLAMP));c.drawCircle(cx,cy,r,p);p.setShader(null);p.setColor(Color.argb((int)(16*s),21,32,54));c.drawRect(0,0,getWidth(),getHeight(),p);}
    private void drawRays(Canvas c,float cx,float cy,float t,float s){float d=getResources().getDisplayMetrics().density;p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<9;i++){float x=cx+(i-4)*24*d+(float)Math.sin(t*.45+i)*9*d,top=cy-(210+(i%3)*34)*d,bottom=cy+(135+(i+1)%3*26)*d;p.setStrokeWidth((.7f+(i%3)*.35f)*d);p.setColor(Color.argb((int)((24+(i%4)*10)*s),208,230,220));c.drawLine(x,top,x+(float)Math.sin(t*.7+i)*12*d,bottom,p);}p.setStrokeCap(Paint.Cap.BUTT);}
    private void drawOrbit(Canvas c,float cx,float cy,float t,float pulse,float s){float d=getResources().getDisplayMetrics().density;p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<4;i++){float r=(62+i*28+pulse*(i%2==0?5:-3))*d;p.setStrokeWidth((1.1f+i*.45f)*d);p.setColor(Color.argb((int)((118-i*18)*s),i%2==0?236:182,i%2==0?219:220,i%2==0?171:221));RectF box=new RectF(cx-r,cy-r*.62f,cx+r,cy+r*.62f);float start=t*(18+i*7)*(i%2==0?1:-1)+i*71;c.drawArc(box,start,128+i*19,false,p);}p.setStrokeCap(Paint.Cap.BUTT);}
    private void drawSigil(Canvas c,float cx,float cy,float t,float pulse,float s){float d=getResources().getDisplayMetrics().density,r=(42+pulse*4)*d;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2.2f*d);p.setColor(Color.argb((int)(220*s),247,228,175));Path diamond=new Path();diamond.moveTo(cx,cy-r);diamond.lineTo(cx+r*.72f,cy);diamond.lineTo(cx,cy+r);diamond.lineTo(cx-r*.72f,cy);diamond.close();c.drawPath(diamond,p);p.setStrokeWidth(1.1f*d);p.setColor(Color.argb((int)(175*s),190,226,224));c.drawCircle(cx,cy,r*.54f,p);float spin=t*(phase==Phase.THINKING?42:22);for(int i=0;i<6;i++){double a=Math.toRadians(spin+i*60);float x1=cx+(float)Math.cos(a)*r*.28f,y1=cy+(float)Math.sin(a)*r*.28f,x2=cx+(float)Math.cos(a)*r*.52f,y2=cy+(float)Math.sin(a)*r*.52f;c.drawLine(x1,y1,x2,y2,p);}p.setStyle(Paint.Style.FILL);p.setShader(new RadialGradient(cx,cy,18*d,Color.argb((int)(245*s),255,240,190),Color.TRANSPARENT,Shader.TileMode.CLAMP));c.drawCircle(cx,cy,18*d,p);p.setShader(null);if(phase==Phase.WARNING){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.5f*d);p.setColor(Color.argb((int)(210*s),255,185,151));c.drawCircle(cx,cy,r*1.42f,p);}else if(phase==Phase.APPLYING){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.4f*d);p.setColor(Color.argb((int)(210*s),210,236,204));c.drawArc(new RectF(cx-r*1.55f,cy-r*1.05f,cx+r*1.55f,cy+r*1.05f),-20,220,false,p);}}
    private void drawMotes(Canvas c,float cx,float cy,float t,float s){float d=getResources().getDisplayMetrics().density,count=phase==Phase.DEGRADED?8:18;p.setStyle(Paint.Style.FILL);for(int i=0;i<(int)count;i++){double a=i*2.399+t*(.22+(i%3)*.05);float r=(76+i*9)%210*d,x=cx+(float)Math.cos(a)*r,y=cy+(float)Math.sin(a)*r*.63f,sz=(1.2f+(i%4)*.55f)*d;p.setColor(Color.argb((int)((72+(i%4)*28)*s),232,222,180));c.drawCircle(x,y,sz,p);}if(phase==Phase.DEGRADED&&((int)(t*4)%2==0)){p.setColor(Color.argb(52,218,229,230));c.drawRect(cx-52*d,cy+34*d,cx-18*d,cy+36*d,p);}}
}
