package com.aicharacter.v3;
import java.util.*;
/** Haru infers ecology from repeated visible co-occurrence. Hypotheses may be wrong and are revised only by later observations. */
public final class EcologyObservationLearningEngine{
 private static final long SAMPLE_MS=60000L,EVIDENCE_COOLDOWN_MS=8L*60000L,RECENT_CREATURE_MS=3L*60000L;
 private EcologyObservationLearningEngine(){}
 public static void observe(WorldState s,long now){
  if(s==null||s.world==null||BodyRhythmEngine.isSleeping(s))return;if(s.ecologyObservation==null)s.ecologyObservation=new EcologyObservationState();EcologyObservationState st=s.ecologyObservation;
  if(st.lastObservedAt>0&&now-st.lastObservedAt<SAMPLE_MS)return;HaruVisionEngine.Snapshot v=HaruVisionEngine.observe(s);if(v.attention*v.visibility<.24)return;
  Map<String,HaruVisionEngine.Seen> seen=new LinkedHashMap<>();for(HaruVisionEngine.Seen x:v.seen)seen.put(x.id,x);
  List<WorldObject> visibleCreatures=new ArrayList<>(),visibleFlora=new ArrayList<>();for(HaruVisionEngine.Seen x:v.seen){WorldObject o=s.world.object(x.id);if(o==null)continue;if("creature".equals(o.type))visibleCreatures.add(o);else if(LivingWorldEngine.isLivingFlora(o))visibleFlora.add(o);}
  for(WorldObject c:visibleCreatures)st.creatureSeen.put(c.id,now);
  for(WorldObject flora:visibleFlora){FloraLifeState f=LivingWorldEngine.flora(s,flora.id);if(f==null)continue;EcologyObservationState.FloraSeen prior=st.flora.get(flora.id);if(prior!=null&&prior.seenAt>0){double delta=f.opening-prior.opening,growth=f.growthPulse-prior.growthPulse;long elapsed=Math.max(1,now-prior.seenAt);for(WorldObject creature:visibleCreatures){String key=subject(creature.id,flora.id),cool=key+":"+signal(delta,growth);if(now-st.evidenceCooldown.getOrDefault(cool,0L)<EVIDENCE_COOLDOWN_MS)continue;boolean consecutive=st.creatureSeen.getOrDefault(creature.id,0L)>=prior.seenAt-RECENT_CREATURE_MS;double magnitude=Math.max(Math.abs(delta),Math.abs(growth)*.75);if(magnitude>=.07){String change=delta>.055?"opened more than before":delta<-.055?"closed more than before":"changed its living rhythm";MemoryEntry m=observationMemory(s,now,creature,flora,"She noticed that "+label(creature)+" was nearby while "+label(flora)+" "+change+".",Math.min(.68,.28+magnitude*.75));CognitionEngine.reviseFromMemory(s,key,"may_affect_response",1,Math.min(.72,.26+magnitude*.80),m,now);st.evidenceCooldown.put(cool,now);}else if(consecutive&&elapsed>=SAMPLE_MS){BeliefState b=s.beliefStates.get(key);if(b!=null&&b.confidence>.20){MemoryEntry m=observationMemory(s,now,creature,flora,"She watched "+label(creature)+" near "+label(flora)+", but this time the plant-like organism did not visibly change in the same way.",.30);CognitionEngine.reviseFromMemory(s,key,b.value,-1,.26,m,now);st.evidenceCooldown.put(cool,now);}}}}
    EcologyObservationState.FloraSeen cur=new EcologyObservationState.FloraSeen();cur.opening=f.opening;cur.growthPulse=f.growthPulse;cur.seenAt=now;st.flora.put(flora.id,cur);
  }
  st.lastObservedAt=now;trim(st,now);
 }
 public static String bestQuestionTarget(WorldState s){
  if(s==null||s.world==null)return"";String best="";double score=0;for(Map.Entry<String,BeliefState>e:s.beliefStates.entrySet()){if(!e.getKey().startsWith("eco_hyp:"))continue;BeliefState b=e.getValue();if(b==null||b.confidence<.18||b.confidence>.72)continue;String flora=parseFlora(e.getKey());WorldObject o=s.world.object(flora);if(o==null||!o.enabled)continue;double uncertainty=1-Math.abs(b.confidence-.45)/.45,recency=recentEvidence(b)>0?.18:0,v=uncertainty+recency;if(v>score){score=v;best=flora;}}return best;
 }
 public static double questionDrive(WorldState s){String target=bestQuestionTarget(s);if(target.isEmpty()||s==null)return 0;double curiosity=s.mood==null?.3:s.mood.curiosity,energy=s.body==null?.5:s.body.energy/100.0;return Math.max(0,Math.min(1,curiosity*.62+energy*.22+.12));}
 public static String diagnostic(WorldState s){StringBuilder x=new StringBuilder("HARU ECOLOGY HYPOTHESES\n");if(s==null)return x.append("<no state>").toString();for(Map.Entry<String,BeliefState>e:s.beliefStates.entrySet())if(e.getKey().startsWith("eco_hyp:")){BeliefState b=e.getValue();x.append(readableSubject(s,e.getKey())).append(" | belief=").append(b.value).append(" | confidence=").append(String.format(Locale.US,"%.2f",b.confidence)).append(" | evidence=").append(b.evidence.size()).append('\n');}return x.toString();}
 private static MemoryEntry observationMemory(WorldState s,long now,WorldObject creature,WorldObject flora,String text,double significance){return CognitionEngine.process(s,new Experience("ecology_observation",text,.03,significance).atTime(now).at(HaruPerception.currentPlaceId(s),flora.id).with(creature.id).tag("observe").tag("ecology").tag("creature:"+creature.id).tag("flora:"+flora.id));}
 private static String subject(String creature,String flora){return"eco_hyp:"+creature+"->"+flora+":response";}
 private static String parseFlora(String subject){int a=subject.indexOf("->"),b=subject.lastIndexOf(":");return a>=0&&b>a?subject.substring(a+2,b):"";}
 private static String parseCreature(String subject){int a=subject.indexOf("eco_hyp:"),b=subject.indexOf("->");return a>=0&&b>a?subject.substring(a+8,b):"";}
 private static String readableSubject(WorldState s,String subject){WorldObject c=s.world==null?null:s.world.object(parseCreature(subject)),f=s.world==null?null:s.world.object(parseFlora(subject));return(c==null?parseCreature(subject):label(c))+" -> "+(f==null?parseFlora(subject):label(f));}
 private static String label(WorldObject o){return o==null||o.haruDescription==null||o.haruDescription.isEmpty()?o==null?"something":o.id:o.haruDescription;}
 private static String signal(double delta,double growth){return delta>.055?"open":delta<-.055?"close":Math.abs(growth)>.07?"rhythm":"stable";}
 private static long recentEvidence(BeliefState b){if(b==null||b.evidence.isEmpty())return 0;return b.evidence.get(b.evidence.size()-1).timestamp;}
 private static void trim(EcologyObservationState s,long now){s.creatureSeen.entrySet().removeIf(e->now-e.getValue()>12L*3600000L);s.evidenceCooldown.entrySet().removeIf(e->now-e.getValue()>2L*24L*3600000L);while(s.flora.size()>80){Iterator<String>it=s.flora.keySet().iterator();if(!it.hasNext())break;it.next();it.remove();}}
}