package com.aicharacter.v3;
import android.content.Context;import android.graphics.*;import android.view.*;
/** Layered state-driven renderer. World simulation remains the only source of actor/environment truth. */
public final class GameView extends View{
 private static final long DISTURBANCE_NOTICE_MS=3000L,MIN_DISTURBANCE_DISPLAY_MS=1400L,SEVERE_DISTURBANCE_MS=8000L,RECOVERY_NOTICE_MS=2600L;private static final int MAX_ACTIVE_CATCHUP_STEPS=48;
 public interface Host{void onTalk();void onGod();void onConsole();void onVoiceTap(boolean doubleTap);}private final Paint p=new Paint(),text=new Paint(),bg=new Paint();private final WorldState state;private final Host host;private final AssetManifest assets;private long lastFrame=System.nanoTime(),lastVoiceTap,lastFailureAt,logicalWallNow,disturbanceStartedAt,recoveryNoticeUntil,activeBacklogMs,lastFrameGapMs,devVeilUntil,lastAutoMaintenanceAt,haruVisionUntil;private int consecutiveFailures;private boolean devVeilSevere;private float density,anim;private String loadedArea="";private Throwable lastRenderError;
 public GameView(Context c,WorldState s,Host h){super(c);state=s;host=h;density=getResources().getDisplayMetrics().density;p.setAntiAlias(false);p.setFilterBitmap(false);bg.setAntiAlias(false);bg.setFilterBitmap(false);bg.setColorFilter(worldPaletteFilter());text.setAntiAlias(true);text.setTypeface(Typeface.create(Typeface.SANS_SERIF,Typeface.NORMAL));assets=new AssetManifest(c);logicalWallNow=Math.max(System.currentTimeMillis(),Math.max(state.lastOpenedAt,state.lastSimulatedAt));StateInvariantChecker.normalize(state,logicalWallNow);syncRealClock(logicalWallNow);setFocusable(true);}
 @Override protected void onDraw(Canvas c){long now=System.nanoTime(),wall=System.currentTimeMillis();lastFrameGapMs=Math.max(0L,(now-lastFrame)/1000000L);float dt=Math.min(.05f,Math.max(0f,lastFrameGapMs/1000f));lastFrame=now;if(lastFrameGapMs>=DISTURBANCE_NOTICE_MS)beginDisturbance(wall);Throwable failure=null;try{update(dt);}catch(Throwable e){failure=e;}if(failure==null){try{render(c);}catch(Throwable e){failure=e;}}boolean forcedVeil=wall<devVeilUntil;if(failure!=null){lastRenderError=failure;lastFailureAt=wall;consecutiveFailures++;beginDisturbance(wall);tryAutoMaintenance(wall);try{drawWorldDisturbance(c,wall,severeDisturbance(wall,true));}catch(Throwable ignored){drawEmergencyVeil(c);}}else{lastRenderError=null;if(activeBacklogMs>=DISTURBANCE_NOTICE_MS)beginDisturbance(wall);boolean stabilizing=forcedVeil||activeBacklogMs>500||(disturbanceStartedAt>0&&wall-disturbanceStartedAt<MIN_DISTURBANCE_DISPLAY_MS);if(stabilizing){drawWorldDisturbance(c,wall,forcedVeil&&devVeilSevere);}else{if(devVeilUntil>0){devVeilUntil=0;devVeilSevere=false;}if(disturbanceStartedAt>0){recoveryNoticeUntil=Math.max(recoveryNoticeUntil,wall+RECOVERY_NOTICE_MS);disturbanceStartedAt=0;consecutiveFailures=0;}if(wall<recoveryNoticeUntil)drawRecoveryNotice(c,wall);if(wall<haruVisionUntil)drawHaruVision(c);} }postInvalidateDelayed(failure!=null?250:33);}
 private void tryAutoMaintenance(long now){if(now-lastAutoMaintenanceAt<5000L)return;lastAutoMaintenanceAt=now;try{DivineMaintenanceEngine.maintain(state,now);}catch(Throwable ignored){}}
 public void showHaruVisionTest(){haruVisionUntil=System.currentTimeMillis()+10000L;postInvalidate();}
 private void drawHaruVision(Canvas c){HaruVisionEngine.Snapshot v=HaruVisionEngine.observe(state);float w=getWidth(),h=getHeight(),m=16*density,pw=Math.min(w*.46f,440*density),ph=Math.min(h*.72f,430*density);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb((int)(35+95*(1-v.visibility)),8,20,22));c.drawRect(0,0,w,h,p);p.setColor(Color.argb(210,8,20,22));c.drawRoundRect(m,m,m+pw,m+ph,16*density,16*density,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.2f*density);p.setColor(Color.argb(130,174,222,213));c.drawRoundRect(m,m,m+pw,m+ph,16*density,16*density,p);p.setStyle(Paint.Style.FILL);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(13*density);text.setColor(Color.rgb(220,235,226));float x=m+18*density,y=m+28*density;c.drawText("HARU VISION",x,y,text);text.setTextSize(11*density);text.setColor(Color.rgb(168,198,190));y+=23*density;c.drawText("Noi: "+v.areaName,x,y,text);y+=19*density;c.drawText("Thoi tiet: "+v.weather,x,y,text);y+=19*density;c.drawText("Tam nhin: "+(int)(v.visibility*100)+"%  |  Chu y: "+(int)(v.attention*100)+"%",x,y,text);y+=19*density;c.drawText("Co the: "+v.bodyHint,x,y,text);y+=24*density;text.setColor(v.catVisible?Color.rgb(226,236,205):Color.rgb(145,166,164));c.drawText(v.catVisible?"Meo: NHIN THAY | "+(int)v.catDistance+"px":"Meo: KHONG NHIN THAY",x,y,text);y+=24*density;int shown=0;for(HaruVisionEngine.Seen s:v.seen){if(shown++>=7)break;text.setColor(Color.argb((int)(125+120*s.clarity),205,224,216));c.drawText("- "+s.label+" | "+(int)s.distance+"px | "+s.direction,x,y,text);y+=20*density;}if(v.seen.isEmpty()){text.setColor(Color.rgb(145,166,164));c.drawText("Khong co vat the nao du ro trong tam nhin.",x,y,text);}text.setTextAlign(Paint.Align.LEFT);}
 public void showGodVeilTest(boolean severe){long now=System.currentTimeMillis();devVeilSevere=severe;devVeilUntil=now+6000L;recoveryNoticeUntil=0;disturbanceStartedAt=now;postInvalidate();}
 private void beginDisturbance(long at){if(disturbanceStartedAt<=0)disturbanceStartedAt=at>0?at:System.currentTimeMillis();}
 private boolean severeDisturbance(long now,boolean failed){long age=disturbanceStartedAt<=0?0:Math.max(0,now-disturbanceStartedAt);return failed&&(consecutiveFailures>=3||age>=SEVERE_DISTURBANCE_MS);}
 private void drawWorldDisturbance(Canvas c,long now,boolean severe){float w=getWidth(),h=getHeight(),cx=w*.5f,cy=h*.47f,min=Math.min(w,h),pulse=(float)(.5+.5*Math.sin(now/420.0));p.setShader(null);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(severe?218:190,severe?10:11,severe?13:22,severe?25:29));c.drawRect(0,0,w,h,p);p.setColor(Color.argb(severe?34:26,185,218,228));for(int i=0;i<12;i++){float y=(h*.08f+i*h*.078f)+(float)Math.sin(now/210.0+i*.9)*3*density;c.drawRect(0,y,w, y+Math.max(1f,density*.7f),p);}float phase=(now%12000L)/12000f;p.setStyle(Paint.Style.STROKE);p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<4;i++){float r=min*(.12f+i*.055f)+pulse*2*density;p.setStrokeWidth((1.1f+i*.35f)*density);p.setColor(Color.argb((severe?74:58)-i*8,severe?242:184,severe?211:226,255));RectF ring=new RectF(cx-r,cy-r,cx+r,cy+r);float start=(phase*360f*(i%2==0?1:-1))+i*47f;c.drawArc(ring,start,150f+i*18f,false,p);}p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(severe?30:24,222,236,255));c.drawCircle(cx,cy,min*.075f+pulse*3*density,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.4f*density);p.setColor(Color.argb(severe?135:105,226,236,255));float sr=min*.063f;c.drawCircle(cx,cy,sr,p);for(int i=0;i<8;i++){double a=i*Math.PI/4.0+phase*Math.PI*.75;float x1=cx+(float)Math.cos(a)*sr*.40f,y1=cy+(float)Math.sin(a)*sr*.40f,x2=cx+(float)Math.cos(a)*sr,y2=cy+(float)Math.sin(a)*sr;c.drawLine(x1,y1,x2,y2,p);}Path sigil=new Path();sigil.moveTo(cx,cy-sr*.72f);sigil.lineTo(cx+sr*.55f,cy);sigil.lineTo(cx,cy+sr*.72f);sigil.lineTo(cx-sr*.55f,cy);sigil.close();c.drawPath(sigil,p);drawVeilCracks(c,cx,cy,w,h,severe,phase);p.setStyle(Paint.Style.FILL);for(int i=0;i<18;i++){float fx=((i*173f+(now/18L)%997)%997)/997f,fy=((i*311f+(now/27L)%991)%991)/991f;float px=w*(.08f+.84f*fx),py=h*(.12f+.76f*fy),rr=(i%3==0?1.8f:1.1f)*density;p.setColor(Color.argb(45+(i%4)*14,205,230,238));c.drawCircle(px,py,rr,p);}drawVeilCorners(c,w,h,severe);text.setTextAlign(Paint.Align.CENTER);text.setShadowLayer(8*density,0,2*density,Color.argb(150,0,0,0));text.setColor(Color.rgb(179,201,199));text.setTextSize(10.5f*density);c.drawText("SYSTEM  //  DIVINE INTERVENTION",cx,cy-min*.22f,text);text.setColor(Color.rgb(246,233,204));text.setTextSize((severe?30:28)*density);c.drawText(severe?"THẾ GIỚI ĐANG BÀI XÍCH BẠN":"THẾ GIỚI ĐANG DAO ĐỘNG",cx,cy+min*.22f,text);text.setTextSize(16*density);text.setColor(Color.rgb(216,227,221));c.drawText(severe?"Thần đã dựng màn chắn.":"Thần đang giữ bạn ở lại.",cx,cy+min*.28f,text);text.setTextSize(12.5f*density);text.setColor(Color.rgb(151,178,176));c.drawText(severe?"Hiện thực đang được ổn định lại.":"Cánh cửa vẫn đang mở.",cx,cy+min*.33f,text);text.clearShadowLayer();text.setTextAlign(Paint.Align.LEFT);p.setStyle(Paint.Style.FILL);p.setStrokeCap(Paint.Cap.BUTT);}
 private void drawVeilCracks(Canvas c,float cx,float cy,float w,float h,boolean severe,float phase){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth((severe?1.5f:1f)*density);p.setColor(Color.argb(severe?100:54,210,228,244));for(int side=0;side<2;side++){float sx=side==0?w*.08f:w*.92f,dir=side==0?1:-1;for(int i=0;i<3;i++){float sy=h*(.24f+i*.21f)+(float)Math.sin(phase*6.28+i)*9*density;float x=sx,y=sy;for(int j=0;j<4;j++){float nx=x+dir*w*(.045f+.012f*j),ny=y+(float)Math.sin((i+1)*(j+1)*1.7+phase*5)*14*density;c.drawLine(x,y,nx,ny,p);x=nx;y=ny;}}}}
 private void drawVeilCorners(Canvas c,float w,float h,boolean severe){float m=22*density,l=34*density;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.4f*density);p.setColor(Color.argb(severe?145:100,215,232,236));c.drawLine(m,m,m+l,m,p);c.drawLine(m,m,m,m+l,p);c.drawLine(w-m,m,w-m-l,m,p);c.drawLine(w-m,m,w-m,m+l,p);c.drawLine(m,h-m,m+l,h-m,p);c.drawLine(m,h-m,m,h-m-l,p);c.drawLine(w-m,h-m,w-m-l,h-m,p);c.drawLine(w-m,h-m,w-m,h-m-l,p);}
 private void drawRecoveryNotice(Canvas c,long now){float w=getWidth(),h=getHeight(),cx=w*.5f,pulse=(float)(.5+.5*Math.sin(now/300.0));p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(178,10,25,27));c.drawRoundRect(w*.27f,h*.095f,w*.73f,h*.215f,18*density,18*density,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(1.2f*density);p.setColor(Color.argb((int)(90+40*pulse),190,224,212));c.drawRoundRect(w*.27f,h*.095f,w*.73f,h*.215f,18*density,18*density,p);p.setStyle(Paint.Style.FILL);text.setTextAlign(Paint.Align.CENTER);text.setColor(Color.rgb(242,232,205));text.setTextSize(17*density);c.drawText("ỔN ĐỊNH ĐÃ TRỞ LẠI",cx,h*.15f,text);text.setTextSize(11.5f*density);text.setColor(Color.rgb(172,202,190));c.drawText("Thần đã giữ được cánh cửa.",cx,h*.19f,text);text.setTextAlign(Paint.Align.LEFT);}
 private void drawEmergencyVeil(Canvas c){c.drawColor(Color.rgb(9,13,22));text.setTextAlign(Paint.Align.CENTER);text.setColor(Color.rgb(241,229,201));text.setTextSize(24*density);c.drawText("THẦN ĐANG GIỮ BẠN Ở LẠI",getWidth()*.5f,getHeight()*.5f,text);text.setTextAlign(Paint.Align.LEFT);}
 private long logicalNow(){long wall=System.currentTimeMillis();if(wall>logicalWallNow)logicalWallNow=wall;logicalWallNow=Math.max(logicalWallNow,Math.max(state.lastOpenedAt,state.lastSimulatedAt));return logicalWallNow;}
 private void syncRealClock(long now){java.util.Calendar c=java.util.Calendar.getInstance();c.setTimeInMillis(now);state.worldMinutes=c.get(java.util.Calendar.HOUR_OF_DAY)*60+c.get(java.util.Calendar.MINUTE)+c.get(java.util.Calendar.SECOND)/60.0;state.environment.updateForTime(state.worldMinutes);}
 private void update(float frameDt){long wallNow=logicalNow(),cursor=state.lastSimulatedAt>0?state.lastSimulatedAt:wallNow;StateInvariantChecker.normalize(state,cursor);state.catX=Math.max(82,Math.min(2318,state.catX));if(state.catState.awake){state.catState.x=state.catX;WorldArea ca=state.world.areaAt(state.catX);if(ca!=null)state.catState.areaId=ca.id;}int guard=0;while(cursor<wallNow&&guard++<MAX_ACTIVE_CATCHUP_STEPS){long stepMs=Math.min(wallNow-cursor,activeStepMs());long subNow=cursor+stepMs;advanceActiveSlice((float)(stepMs/1000.0),subNow);cursor=subNow;state.lastSimulatedAt=cursor;GirlCatPresenceEngine.tick(state,subNow);}activeBacklogMs=Math.max(0,wallNow-cursor);if(cursor==wallNow)syncRealClock(cursor);anim+=frameDt;}
 private long activeStepMs(){boolean dynamic=(state.girlTravel!=null&&state.girlTravel.active)||(state.girlPhysics!=null&&!state.girlPhysics.grounded);return dynamic?250L:1000L;}
 private void advanceActiveSlice(float dt,long now){syncRealClock(now);AtmosphereEvolutionEngine.advance(state,now);RespirationEngine.advance(state,now);ThermalEngine.advance(state,now);BodyInstinctEngine.advance(state,now);BodyPerceptionEngine.observe(state,now);HaruAutonomyEngine.tick(state,dt,now);PhysicalLifeStepEngine.advance(state,dt,now,true,false);}
 private void render(Canvas screen){int w=getWidth(),h=getHeight();if(w<=0||h<=0)return;float scale=Math.max(w/2400f,h/1080f);float vw=w/scale,vh=h/scale;float ox=(w-vw*scale)/2f,oy=(h-vh*scale)/2f;screen.save();screen.translate(ox,oy);screen.scale(scale,scale);drawWorld(screen,vw,vh);screen.restore();drawUi(screen);}
 private void drawWorld(Canvas c,float vw,float vh){CatCameraDirector.Frame f=CatCameraDirector.direct(state);float cam=0f;float lookElev=Math.max(-26,Math.min(26,(540f-f.lookY)*.08f));c.save();c.translate(0,f.elevation+lookElev);String area=areaKey();if(!area.equals(loadedArea)){assets.retainForArea(area);loadedArea=area;}drawSky(c,area,cam);if("lakeside".equals(area)){drawCleanLakeside(c);drawWater(c,cam);}else{drawLayer(c,area+"_distant",cam,.08f);drawLayer(c,area+"_mid",cam,.22f);drawLayer(c,area+"_ground",cam,1f);}for(WorldObject o:state.world.objects)if(o.enabled&&!"FAR_VEGETATION".equals(o.renderLayer))drawObject(c,o,o.x-cam);float girlGround=(float)GroundGeometry.heightPx(state,state.haruX);drawGirl(c,state.haruX-cam,girlGround);if(!"lakeside".equals(area))drawLayer(c,area+"_foreground",cam,1.08f);drawWeather(c,cam);drawTimeTint(c);c.restore();}
 private String areaKey(){WorldArea a=state.world.areaAt(state.haruX);if(a==null)return"lakeside";if("home_shelter".equals(a.id))return"home";if("garden_path".equals(a.id))return"garden";if("quiet_grove".equals(a.id))return"grove";return"lakeside";}
 private void drawSky(Canvas c,String area,float cam){if("lakeside".equals(area)){WorldVisualProfile v=WorldVisualProfile.lakeside(getContext());p.setShader(null);p.setColor(v.skyBottom);c.drawRect(0,0,2400,1080,p);p.setColor(v.skyTop);c.drawRect(0,0,2400,360,p);if(v.clouds){p.setColor(v.cloud);p.setAlpha(180);c.drawRect(180,170,520,222,p);c.drawRect(360,145,640,205,p);c.drawRect(1480,210,1770,254,p);c.drawRect(1630,182,1940,238,p);p.setAlpha(255);}return;}drawLayer(c,area+"_sky",cam,.02f);}
 private void drawCleanLakeside(Canvas c){WorldVisualProfile v=WorldVisualProfile.lakeside(getContext());p.setShader(null);p.setAntiAlias(false);p.setColor(Color.rgb(104,129,108));Path hills=new Path();hills.moveTo(0,565);hills.lineTo(260,430);hills.lineTo(520,520);hills.lineTo(790,390);hills.lineTo(1070,515);hills.lineTo(1360,410);hills.lineTo(1640,525);hills.lineTo(1940,405);hills.lineTo(2180,500);hills.lineTo(2400,420);hills.lineTo(2400,660);hills.lineTo(0,660);hills.close();c.drawPath(hills,p);p.setColor(Color.rgb(73,101,76));for(int i=0;i<9;i++){float x=90+i*285,base=690+(i%3)*18;c.drawRect(x-10,base-110,x+10,base,p);c.drawRect(x-44,base-110,x+44,base-74,p);c.drawRect(x-31,base-145,x+32,base-105,p);}p.setColor(Color.rgb(90,117,80));c.drawRect(0,790,2400,1080,p);p.setColor(Color.rgb(124,145,96));c.drawRect(0,812,2400,846,p);}
 private void drawLayer(Canvas c,String key,float cam,float parallax){Bitmap b=assets.get(key);if(b!=null)c.drawBitmap(b,null,new RectF(0,0,2400,1080),bg);}
 private void drawWater(Canvas c,float cam){int wf=((int)(anim*1.15f))&3;Bitmap b=assets.get("lakeside_water_"+wf);if(b==null)return;float storm="RAIN".equals(state.environment.weather)?1.7f:1f,shimmer=(float)Math.sin(anim*.7*storm)*(8*storm);c.drawBitmap(b,null,new RectF(-cam*.18f+shimmer,0,2400-cam*.18f+shimmer,1080),bg);if("RAIN".equals(state.environment.weather)){p.setColor(Color.argb(28,205,225,230));for(int i=0;i<18;i++){float x=(i*137+(anim*53)%137)%2400,y=650+(i%5)*23;c.drawOval(x-18,y-3,x+18,y+3,p);}}}
 private void drawObject(Canvas c,WorldObject o,float x){String key=o.assetRef;if("creature".equals(o.type)){String a=state.reedling.activity==null?"idle":state.reedling.activity;key="reedling_"+(a.contains("forage")?"forage":a.contains("rest")?"rest":a.contains("flee")||a.contains("alert")?"alert":a.contains("wander")?"move":"idle");}Bitmap b=assets.get(key);if(b==null)return;float bob="creature".equals(o.type)?(float)Math.sin(anim*2.1)*3:0;if("creature".equals(o.type)&&b.getWidth()>=8){int fw=b.getWidth()/8,fr=((int)(anim*5))%8;c.drawBitmap(b,new Rect(fr*fw,0,(fr+1)*fw,b.getHeight()),new RectF(x-o.width*.5f,o.y-o.height+bob,x+o.width*.5f,o.y+bob),p);}else c.drawBitmap(b,null,new RectF(x-o.width*.5f,o.y-o.height+bob,x+o.width*.5f,o.y+bob),p);}
 private void drawGirl(Canvas c,float x,float ground){if(x<-240||x>2640)return;GirlAnimationController.Visual v=GirlAnimationController.select(state);Bitmap b=assets.get(v.asset);if(b==null){BlockBodyRenderer.drawHuman(c,p,state,x,ground);return;}int frame=v.isWalk()&&state.bodyRig!=null?Math.min(v.frames-1,(int)Math.floor(state.bodyRig.stridePhase*v.frames)%v.frames):Math.min(v.frames-1,(int)(anim*v.fps)%v.frames),fw=b.getWidth()/v.frames,fh=b.getHeight();float sc=1.34f,ax=v.anchorX*fw*sc;float left=x-ax,top=GirlAnimationController.renderTop(ground,fh,sc,v.anchorY);BodyRigState rig=state.bodyRig;if(rig!=null){float lean=(float)(rig.spineLean*22.0+rig.pelvisTilt*10.0);left+=lean;}BodyInstinctState bi=state.bodyInstinct;if(bi!=null){float breath=(float)(Math.sin(anim*(2.0+bi.breathDrive*2.4))*bi.breathDrive*2.2);float shiver=(float)(Math.sin(anim*24)*bi.shiver*1.7);float droop=(float)(bi.fatigueDroop*5.0);left+=shiver;top+=droop+breath;}p.setColor(Color.argb(v.state==GirlAnimationController.State.SIT?44:58,0,0,0));c.drawOval(x-47,ground-8,x+47,ground+10,p);p.setAlpha((int)(190+65*state.environment.ambientBrightness));c.drawBitmap(b,new Rect(frame*fw,0,(frame+1)*fw,fh),new RectF(left,top,left+fw*sc,top+fh*sc),p);p.setAlpha(255);}
 private void drawWeather(Canvas c,float cam){if(!"RAIN".equals(state.environment.weather))return;Bitmap rain=assets.get("rain_layer_2");if(rain!=null){c.save();WorldObject shelter=state.world.object("shelter_01");WorldArea ca=state.world.areaAt(state.catX);if(shelter!=null&&ca!=null&&"home_shelter".equals(ca.id)){float sx=shelter.x-cam;c.clipOutRect(sx-shelter.width*.5f,shelter.y-shelter.height,sx+shelter.width*.5f,shelter.y);}Bitmap far=assets.get("rain_layer_0"),mid=assets.get("rain_layer_1");float yf=(anim*95)%1080,ym=(anim*140)%1080;if(far!=null){p.setAlpha(70);c.drawBitmap(far,null,new RectF(0,yf-1080,2400,yf),p);c.drawBitmap(far,null,new RectF(0,yf,2400,yf+1080),p);}if(mid!=null){p.setAlpha(110);c.drawBitmap(mid,null,new RectF(0,ym-1080,2400,ym),p);c.drawBitmap(mid,null,new RectF(0,ym,2400,ym+1080),p);}p.setAlpha((int)(90+120*state.environment.weatherIntensity));float y=(anim*190)%1080;c.drawBitmap(rain,null,new RectF(0,y-1080,2400,y),p);c.drawBitmap(rain,null,new RectF(0,y,2400,y+1080),p);p.setAlpha(255);c.restore();}}
 private ColorFilter worldPaletteFilter(){float saturation=1.20f,contrast=1.08f,offset=128f*(1f-contrast);ColorMatrix sat=new ColorMatrix();sat.setSaturation(saturation);ColorMatrix con=new ColorMatrix(new float[]{contrast,0,0,0,offset,0,contrast,0,0,offset,0,0,contrast,0,offset,0,0,0,1,0});sat.postConcat(con);return new ColorMatrixColorFilter(sat);}
 private void drawTimeTint(Canvas c){String phase=state.environment.dayPhase(state.worldMinutes),lk="NIGHT".equals(phase)?"light_night":"EVENING".equals(phase)?"light_evening":null;if(lk!=null){Bitmap lb=assets.get(lk);if(lb!=null)c.drawBitmap(lb,null,new RectF(0,0,2400,1080),p);}if("home".equals(areaKey())&&("NIGHT".equals(phase)||"EVENING".equals(phase))){Bitmap hw=assets.get("home_warm_light");if(hw!=null)c.drawBitmap(hw,null,new RectF(0,0,2400,1080),p);}int col="NIGHT".equals(phase)?Color.argb(120,18,29,61):"EVENING".equals(phase)?Color.argb(58,178,91,91):"MORNING".equals(phase)?Color.argb(25,255,210,145):Color.TRANSPARENT;if(col!=Color.TRANSPARENT){p.setColor(col);c.drawRect(0,0,2400,1080,p);}if("RAIN".equals(state.environment.weather)){p.setColor(Color.argb(36,30,48,62));c.drawRect(0,0,2400,1080,p);}p.setColor(Color.argb(18,18,24,26));c.drawRect(0,930,2400,1080,p);}
 private void drawUi(Canvas c){int w=getWidth(),h=getHeight();float m=14*density;text.setTextSize(13*density);text.setColor(Color.WHITE);Bitmap panel=assets.get("ui_panel_chat");float pr=Math.min(w*.42f,360*density);if(panel!=null)c.drawBitmap(panel,null,new RectF(m,m,pr,60*density),p);else{p.setColor(Color.argb(112,12,22,25));c.drawRoundRect(m,m,pr,60*density,14*density,14*density,p);}c.drawText("VNF · "+phaseLabel()+" · "+weatherLabel(),28*density,40*density,text);button(c,w-190*density,14*density,w-14*density,56*density,"LIÊN HỆ THẦN");button(c,w-205*density,h-66*density,w-120*density,h-20*density,"NÓI");button(c,w-110*density,h-66*density,w-24*density,h-20*density,"MIC");}
 private String phaseLabel(){String x=state.environment.dayPhase(state.worldMinutes);if("MORNING".equals(x))return"SÁNG";if("EVENING".equals(x))return"CHIỀU TỐI";if("NIGHT".equals(x))return"ĐÊM";return"BAN NGÀY";}
 private String weatherLabel(){String x=state.environment.weather;if("RAIN".equals(x))return"MƯA";if("CLOUDY".equals(x))return"NHIỀU MÂY";return"TRỜI QUANG";}
 private void button(Canvas c,float l,float t,float r,float b,String label){Bitmap ub=assets.get("ui_button");if(ub!=null)c.drawBitmap(ub,null,new RectF(l,t,r,b),p);else{p.setColor(Color.argb(145,16,28,31));c.drawRoundRect(l,t,r,b,15*density,15*density,p);}text.setTextAlign(Paint.Align.CENTER);c.drawText(label,(l+r)/2,t+(b-t)*.65f,text);text.setTextAlign(Paint.Align.LEFT);}
 @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY(),h=getHeight(),w=getWidth();if(e.getAction()==MotionEvent.ACTION_DOWN){if(x>w-115*density&&y>h-85*density){long n=System.currentTimeMillis();boolean dbl=n-lastVoiceTap<350;lastVoiceTap=n;host.onVoiceTap(dbl);return true;}if(x>w-215*density&&x<w-115*density&&y>h-85*density){host.onTalk();return true;}if(x>w-205*density&&y<75*density){host.onGod();return true;}}return true;}
 public String assetDiagnostic(){return assets.diagnostic();}
}
