package com.aicharacter.v3;import java.util.*;
/** Search planner consumes only girl-available evidence. System cat coordinates are consulted only by local perception. */
public final class GirlCatSearchEngine{
 public static final class SearchState{public String searchId="",reason="",pauseReason="";public final List<String> candidates=new ArrayList<>(),sources=new ArrayList<>(),visited=new ArrayList<>();public int index=0;public boolean active=false,found=false,paused=false;public org.json.JSONObject toJson(){org.json.JSONObject j=new org.json.JSONObject();try{j.put("searchId",searchId);j.put("reason",reason);j.put("pauseReason",pauseReason);j.put("index",index);j.put("active",active);j.put("found",found);j.put("paused",paused);j.put("candidates",new org.json.JSONArray(candidates));j.put("sources",new org.json.JSONArray(sources));j.put("visited",new org.json.JSONArray(visited));}catch(Exception ignored){}return j;}public static SearchState fromJson(org.json.JSONObject j){SearchState x=new SearchState();if(j==null)return x;x.searchId=j.optString("searchId","");x.reason=j.optString("reason","");x.pauseReason=j.optString("pauseReason","");x.index=j.optInt("index",0);x.active=j.optBoolean("active",false);x.found=j.optBoolean("found",false);x.paused=j.optBoolean("paused",false);load(j.optJSONArray("candidates"),x.candidates);load(j.optJSONArray("sources"),x.sources);load(j.optJSONArray("visited"),x.visited);return x;}private static void load(org.json.JSONArray a,List<String> o){if(a!=null)for(int i=0;i<a.length();i++)o.add(a.optString(i));}}
 private GirlCatSearchEngine(){}
 public static boolean shouldSearch(WorldState s,long now){if(s.catState.awake||s.catSearch.active||s.catState.carryKnownByGirl||"girl".equals(s.catState.attachedToEntity))return false;if(s.body.energy<18||s.body.pain>35||s.body.sleepiness>88)return false;long absent=Math.max(0,now-s.lastCatSeenAt)/60000L;double utility=s.relationship.attachment*.22+s.mood.loneliness*18+Math.min(26,absent/45.0)+("RAIN".equals(s.environment.weather)?7:0)-s.body.pain*.35-(100-s.body.energy)*.12;return absent>60&&utility>14;}
 public static void start(WorldState s,long now,String reason){if(!shouldSearch(s,now))return;SearchState q=new SearchState();q.active=true;q.searchId="search_"+Long.toHexString(now);q.reason=reason;LinkedHashMap<String,Double> score=new LinkedHashMap<>();LinkedHashMap<String,String> source=new LinkedHashMap<>();add(score,source,"home_shelter",.30+habit(s,"cat_sleep_home",now),"known cat home / sleep habit");for(MemoryEntry m:s.memories){if(m.location==null||m.location.isEmpty())continue;if(m.tags.contains("cat")||m.participants.contains("cat")||m.tags.contains("player")){add(score,source,m.location,.25+m.importance,"memory:"+m.memoryId);}}for(PlaceAssociation p:s.placeAssociations.values())if(p!=null&&p.id!=null&&!p.id.isEmpty()&&p.familiarity>.25)add(score,source,p.id,.10+p.familiarity*.2,"place association");String current=HaruPerception.currentPlaceId(s);add(score,source,current,.06,"nearby current place");List<Map.Entry<String,Double>> entries=new ArrayList<>(score.entrySet());entries.sort((a,b)->Double.compare(b.getValue(),a.getValue()));for(Map.Entry<String,Double> e:entries)if(s.world.area(e.getKey())!=null){q.candidates.add(e.getKey());q.sources.add(source.get(e.getKey()));}s.catSearch=q;s.currentIntention="find_cat";s.planState=new PlanState();s.planState.planId="plan_"+q.searchId;s.planState.intentionId="find_cat";s.planState.goal="find cat from remembered evidence";s.planState.status="ACTIVE";s.planState.commitment=.68;s.planState.createdAt=now;s.planState.lastProgressAt=now;s.planState.plannedAction="SEARCH_LOCAL";s.planState.steps.addAll(q.candidates);startNextLeg(s,now);WorldEventBus.publishId(s,now,"girl_search_start_"+q.searchId,"GIRL_STARTED_SEARCH",q.searchId,"Girl began searching from memory, habits and known places.");}
 public static void advance(WorldState s,long now,double minutes){if(!s.catSearch.active)return;if(s.catState.carryKnownByGirl||"girl".equals(s.catState.attachedToEntity)){stopContradiction(s,now,"cat knowingly carried");return;}if(s.body.energy<12||s.body.pain>45){pause(s,now,"body condition requires rest");return;}if(s.catSearch.paused)return;PlanReconsiderationEngine.Result r=PlanReconsiderationEngine.evaluate(s,now);if(r.reconsider()){PlanExecutor.applyDecision(s,r,now);if("PAUSED".equals(s.planState.status)){pause(s,now,r.reason);return;}}if(s.girlTravel.active)TravelEngine.advanceMinutes(s,s.girlTravel,minutes,now);else if("ACTIVE".equals(s.planState.status)&&s.catSearch.index<s.catSearch.candidates.size())startNextLeg(s,now);}
 public static void advance(WorldState s,long now){advance(s,now,8);}
 private static void startNextLeg(WorldState s,long now){if(s.catSearch.index>=s.catSearch.candidates.size()){finishSearch(s,now,"FAILED","searched remembered places without finding the cat");return;}String area=s.catSearch.candidates.get(s.catSearch.index);s.persistentIntentionTarget=area;s.planState.destination=area;s.planState.stepIndex=s.catSearch.index;s.planState.lastProgressAt=now;if(!TravelEngine.start(s,s.girlTravel,"girl",area,s.planState.planId,now)){s.catSearch.visited.add(area+":unreachable");s.catSearch.index++;startNextLeg(s,now);}else s.haruActivity="walking and looking for the cat";}
 public static void onArrival(WorldState s,long now){if(!s.catSearch.active||s.catSearch.index>=s.catSearch.candidates.size())return;String area=s.catSearch.candidates.get(s.catSearch.index);if("ROUTE".equals(s.girlTravel.travelMode)){float anchor=searchAnchor(s,area);if(Math.abs(s.haruX-anchor)>70&&TravelEngine.startLocal(s,s.girlTravel,"girl","search_anchor_"+area,anchor,60,s.planState.planId,now)){s.haruActivity="searching carefully in "+area;return;}}s.catSearch.visited.add(area);WorldEventBus.publishId(s,now,"search_arrive_"+s.catSearch.searchId+"_"+s.catSearch.index,"GIRL_REACHED_SEARCH_CANDIDATE",area,"Girl physically reached search candidate "+area+".");if(canPerceiveCat(s)){long away=Math.max(s.lastAbsenceMinutes,Math.max(0,now-s.lastCatSeenAt)/60000L);s.catSearch.found=true;s.catSearch.active=false;s.planState.status="COMPLETED";s.planState.lastProgressAt=now;s.planState.lastAction="SEARCH_LOCAL @"+now;s.planState.lastOutcome="cat found at "+area;s.currentIntention="";s.persistentIntentionTarget="";s.intentionStartedAt=now;MemoryEntry m=CognitionEngine.process(s,new Experience("found_cat","She locally perceived the cat after searching.",.20,.82).at(area,"").with("cat").tag("cat").tag("search").tag("found"));CognitionEngine.reviseFromMemory(s,"cat_location","perceived nearby",1,.92,m);WorldEventBus.publishId(s,now,"girl_found_"+s.catSearch.searchId,"GIRL_FOUND_CAT",s.catSearch.searchId,"Girl locally perceived the cat after physically reaching a searched place.");if(away>=45){s.lastAbsenceMinutes=away;s.reunionContext=ReunionEngine.contextKey(s,away);}s.lastCatSeenAt=now;decideWake(s,now);}else{MemoryEntry m=CognitionEngine.process(s,new Experience("searched_location_not_found","She searched "+area+" but did not find the cat.",-.12,.55).at(area,"").tag("cat").tag("search").tag("not_found"));CognitionEngine.reviseFromMemory(s,"cat_location_"+area,"probably not here",-1,.55,m);WorldEventBus.publishId(s,now,"search_miss_"+s.catSearch.searchId+"_"+s.catSearch.index,"GIRL_DID_NOT_FIND_CAT",area,"Girl reached "+area+" and did not locally perceive the cat.");s.catSearch.index++;s.planState.lastOutcome="not found at "+area;s.planState.lastAction="SEARCH_LOCAL @"+now;if(s.catSearch.index<s.catSearch.candidates.size())startNextLeg(s,now);else{finishSearch(s,now,"FAILED","searched remembered places without finding the cat");}}}
 public static boolean canPerceiveCat(WorldState s){if("girl".equals(s.catState.attachedToEntity)&&s.catState.carryKnownByGirl)return true;WorldArea ga=s.world.areaAt(s.haruX),ca=s.world.areaAt(s.catState.x);return ga!=null&&ca!=null&&ga.id.equals(ca.id)&&Math.abs(s.haruX-s.catState.x)<=120f;}
 public static void decideWake(WorldState s,long now){if(!s.catSearch.found||s.catState.awake)return;long sleepMin=Math.max(0,now-s.catState.sleepStartedAt)/60000L;double urgency=("RAIN".equals(s.environment.weather)?.45:0)+(sleepMin>720?.18:0)+(s.catState.sleepMode.contains("SAFE")?.06:0),desire=s.relationship.attachment/101.0*.15,restraint=.30+s.relationship.comfort/101.0*.12+s.personality.patience*.10;if(urgency+desire>restraint){WorldEventBus.publishId(s,now,"girl_wake_"+s.catSearch.searchId,"GIRL_CALLING_CAT_TO_WAKE",s.catSearch.searchId,"Girl decided there was enough reason to call the sleeping cat awake.");s.haruActivity="gently calling the sleeping cat";}else{s.haruActivity="sitting quietly near the sleeping cat";WorldEventBus.publishId(s,now,"girl_wait_"+s.catSearch.searchId,"GIRL_DECIDED_TO_WAIT",s.catSearch.searchId,"Girl found the sleeping cat and chose not to wake it.");}}
 public static boolean resume(WorldState s,long now){if(!s.catSearch.active||!s.catSearch.paused)return false;if(s.body.energy<20||s.body.pain>35)return false;s.catSearch.paused=false;s.catSearch.pauseReason="";s.planState.status="ACTIVE";s.planState.lastProgressAt=now;s.currentIntention="find_cat";s.intentionStartedAt=now;startNextLeg(s,now);return true;}
 private static void pause(WorldState s,long now,String why){s.catSearch.paused=true;s.catSearch.pauseReason=why;s.planState.status="PAUSED";s.planState.pausedAt=now;s.planState.pauseReason=why;s.planState.lastProgressAt=now;s.girlTravel.active=false;s.haruActivity="pausing the search to recover";}
 private static void stopContradiction(WorldState s,long now,String why){finishSearch(s,now,"ABANDONED",why);}
 private static void finishSearch(WorldState s,long now,String status,String outcome){s.catSearch.active=false;s.catSearch.paused=false;s.girlTravel.active=false;s.planState.status=status;s.planState.lastOutcome=outcome;s.planState.lastProgressAt=now;s.currentIntention="";s.persistentIntentionTarget="";s.intentionStartedAt=now;s.haruActivity="pausing after the search";}
 private static float searchAnchor(WorldState s,String area){String id="home_shelter".equals(area)?"shelter_01":"lakeside".equals(area)?"bench_lake_01":"quiet_grove".equals(area)?"lake_tree_03":"";WorldObject o=s.world.object(id);return o!=null?o.x:WorldPathPlanner.center(s.world,area);}
 private static void add(Map<String,Double>s,Map<String,String>src,String p,double v,String why){if(p==null||p.isEmpty())return;if(!s.containsKey(p)||v>s.get(p)){s.put(p,v);src.put(p,why);}}
 private static double habit(WorldState s,String id,long now){HabitState h=s.habits.get(id);return h==null?0:h.effectiveStrength(now,CognitionEngine.timeContext(s.worldMinutes));}
 public static String trace(WorldState s){SearchState q=s.catSearch;StringBuilder b=new StringBuilder("GIRL SEARCH TRACE V2\nreason=").append(q.reason).append(" paused=").append(q.paused).append("\ncandidates (NO catX planning):\n");for(int i=0;i<q.candidates.size();i++)b.append(i).append(' ').append(q.candidates.get(i)).append(" <- ").append(i<q.sources.size()?q.sources.get(i):"unknown").append('\n');b.append("index=").append(q.index).append(" route=").append(s.girlTravel.route).append(" visited=").append(q.visited).append(" localPerception=").append(canPerceiveCat(s));return b.toString();}
}
