package com.aicharacter.v3;

import android.content.Context;import org.json.JSONArray;import org.json.JSONObject;import java.io.BufferedReader;import java.io.InputStream;import java.io.InputStreamReader;import java.nio.charset.StandardCharsets;import java.text.Normalizer;import java.util.ArrayList;import java.util.Arrays;import java.util.Comparator;import java.util.LinkedHashSet;import java.util.List;import java.util.Locale;import java.util.Set;
/** Read-only eyes on code for the online God channel. */
public final class GodCodeVision{
 private static final String ASSET="god_world_source_snapshot.txt";private static final int MAX_SOURCE_CHARS=22000,MAX_FILES=7;private GodCodeVision(){}
 public static JSONObject build(Context context,String question){JSONObject out=new JSONObject();try{boolean requested=isTechnicalCodeQuestion(question);out.put("enabled",requested);out.put("mode","READ_ONLY_BUILD_SNAPSHOT");out.put("canModifyCode",false);out.put("canExecuteCode",false);out.put("canSelfUpdate",false);out.put("freshness","exact sources from this APK build");if(!requested){out.put("note","Code snapshot withheld because the player is not asking a technical/code question.");return out;}String snapshot=readAsset(context);if(snapshot.isEmpty()){out.put("available",false);out.put("note","Build snapshot asset is unavailable.");return out;}List<Section> sections=parse(snapshot);Set<String> terms=queryTerms(question);for(Section s:sections)s.score=score(s,terms);sections.sort(Comparator.comparingInt((Section s)->s.score).reversed().thenComparing(s->s.name));JSONArray catalog=new JSONArray();for(Section s:sections)catalog.put(s.name);out.put("available",true);out.put("fileCatalog",catalog);JSONArray excerpts=new JSONArray();int used=0,added=0;for(Section s:sections){if(added>=MAX_FILES||used>=MAX_SOURCE_CHARS)break;if(s.score<=0&&added>=3)break;int remain=MAX_SOURCE_CHARS-used;String text=s.text.length()>remain?s.text.substring(0,Math.max(0,remain)):s.text;if(text.isEmpty())break;JSONObject e=new JSONObject();e.put("file",s.name);e.put("score",s.score);e.put("source",text);excerpts.put(e);used+=text.length();added++;}if(added==0){for(String core:Arrays.asList("WorldState.java","HaruMind.java","WorldRepository.java","LifeCycleEngine.java","GameView.java")){Section found=find(sections,core);if(found==null||used>=MAX_SOURCE_CHARS||added>=MAX_FILES)continue;int remain=MAX_SOURCE_CHARS-used;String text=found.text.length()>remain?found.text.substring(0,remain):found.text;JSONObject e=new JSONObject();e.put("file",found.name);e.put("score",0);e.put("source",text);excerpts.put(e);used+=text.length();added++;}}out.put("excerpts",excerpts);out.put("excerptCharacters",used);out.put("limitations","Read-only build snapshot. It cannot inspect runtime memory beyond System Reality, cannot alter source, cannot rebuild the APK, and may only reason from supplied excerpts.");}catch(Throwable t){try{out.put("available",false);out.put("error",t.getClass().getSimpleName());}catch(Exception ignored){}}return out;}
 /** Shared opt-in gate for code/world-internals. Keep ordinary divine conversation free of developer/runtime details. */
 public static boolean isTechnicalCodeQuestion(String q){String n=norm(q);String[] keys={"code","ma nguon","source","java","class","engine","logic","he thong","system","bug","loi","crash","anr","camera","background","render","renderer","save","database","memory","bo nho","world code","code the gioi","kien truc","architecture","debug","chan doan","compile","build","gradle","apk"};for(String k:keys)if(n.contains(k))return true;return false;}
 private static Set<String> queryTerms(String q){LinkedHashSet<String> out=new LinkedHashSet<>();String n=norm(q).replaceAll("[^a-z0-9_ ]"," ");for(String t:n.split("\\s+"))if(t.length()>=3&&!STOP.contains(t))out.add(t);if(n.contains("camera")||n.contains("goc nhin")){out.add("camera");out.add("gameview");out.add("framing");}if(n.contains("background")||n.contains("do hoa")){out.add("render");out.add("asset");out.add("gameview");}if(n.contains("tri nho")||n.contains("memory")){out.add("memory");out.add("belief");}if(n.contains("co gai")||n.contains("haru")){out.add("haru");out.add("intention");out.add("emotion");}if(n.contains("the gioi")||n.contains("world")){out.add("world");out.add("environment");out.add("lifecycle");}if(n.contains("save")){out.add("repository");out.add("save");out.add("json");}return out;}
 private static int score(Section s,Set<String> terms){String name=norm(s.name),body=norm(s.text);int score=0;for(String t:terms){if(name.contains(t))score+=12;int at=body.indexOf(t);if(at>=0)score+=3;if(at>=0&&body.indexOf(t,at+t.length())>=0)score+=2;}if(name.equals("worldstate.java"))score+=1;return score;}
 private static List<Section> parse(String snapshot){List<Section> out=new ArrayList<>();String marker="===== FILE: ";int pos=0;while(true){int m=snapshot.indexOf(marker,pos);if(m<0)break;int endName=snapshot.indexOf(" =====",m+marker.length());if(endName<0)break;String name=snapshot.substring(m+marker.length(),endName).trim();int bodyStart=snapshot.indexOf('\n',endName);if(bodyStart<0)break;bodyStart++;int next=snapshot.indexOf(marker,bodyStart);String body=(next<0?snapshot.substring(bodyStart):snapshot.substring(bodyStart,next)).trim();out.add(new Section(name,body));if(next<0)break;pos=next;}return out;}
 private static Section find(List<Section> list,String name){for(Section s:list)if(s.name.equals(name))return s;return null;}
 private static String readAsset(Context context)throws Exception{if(context==null)return"";StringBuilder b=new StringBuilder(600000);try(InputStream in=context.getAssets().open(ASSET);BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null){b.append(line).append('\n');if(b.length()>900000)break;}}return b.toString();}
 private static String norm(String s){if(s==null)return"";String x=Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}+","");return x.toLowerCase(Locale.ROOT).replace('đ','d');}
 private static final Set<String> STOP=new LinkedHashSet<>(Arrays.asList("cho","voi","nay","kia","cua","the","gioi","than","xem","giup","minh","toi","ban","dang","duoc","khong","sao","tai","nhu","mot","nhung","code"));
 private static final class Section{final String name,text;int score;Section(String name,String text){this.name=name;this.text=text;}}
}
