package com.aicharacter.v3;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.Gravity;
import android.view.View;
import android.widget.*;

/** In-world God contact. UI remains a quiet channel around the manifestation, never a modal chatbot card. */
public final class GodContactScene{
 public interface Host{void onSend(String text);void onClose();}
 private final Activity a;private final Host host;private final FrameLayout root;private final TextView status,conversation;private final ScrollView scroll;private final EditText input;private final Button send;private final DivineManifestationView manifestation;private boolean sending,closing;
 public GodContactScene(Activity a,String inbox,Host h){this.a=a;host=h;root=new FrameLayout(a);root.setClickable(true);root.setBackgroundColor(Color.argb(12,4,9,17));root.setAlpha(0f);root.animate().alpha(1f).setDuration(560).start();manifestation=new DivineManifestationView(a);root.addView(manifestation,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout shell=new LinearLayout(a);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(18),dp(12),dp(18),dp(16));root.addView(shell,new FrameLayout.LayoutParams(-1,-1));
  LinearLayout top=new LinearLayout(a);top.setGravity(Gravity.CENTER_VERTICAL);TextView mark=text("✦  VNF",13,Color.rgb(235,222,186));mark.setLetterSpacing(.20f);top.addView(mark,new LinearLayout.LayoutParams(0,-2,1));status=text(label(GodSessionManager.getState()),11,Color.rgb(187,211,209));status.setGravity(Gravity.CENTER);top.addView(status,new LinearLayout.LayoutParams(0,-2,1));Button x=ghostButton("×");x.setOnClickListener(v->{if(!sending&&!closing)dismiss(host::onClose);else Toast.makeText(a,"Không gian vẫn đang dao động…",Toast.LENGTH_SHORT).show();});top.addView(x,new LinearLayout.LayoutParams(dp(48),dp(42)));shell.addView(top);
  Space breathing=new Space(a);shell.addView(breathing,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout channel=new LinearLayout(a);channel.setOrientation(LinearLayout.VERTICAL);channel.setPadding(dp(14),dp(10),dp(14),dp(12));GradientDrawable channelBg=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{Color.argb(48,8,18,28),Color.argb(178,7,15,24)});channelBg.setCornerRadius(dp(18));channelBg.setStroke(dp(1),Color.argb(76,196,219,210));channel.setBackground(channelBg);shell.addView(channel,new LinearLayout.LayoutParams(-1,-2));
  scroll=new ScrollView(a);scroll.setFillViewport(false);conversation=text(inbox==null?"":inbox,13,Color.rgb(232,230,216));conversation.setLineSpacing(0,1.12f);conversation.setPadding(dp(3),dp(2),dp(3),dp(7));scroll.addView(conversation);channel.addView(scroll,new LinearLayout.LayoutParams(-1,dp(86)));
  LinearLayout row=new LinearLayout(a);row.setGravity(Gravity.CENTER_VERTICAL);input=new EditText(a);input.setHint("Gửi một ý niệm…");input.setTextColor(Color.rgb(244,242,231));input.setHintTextColor(Color.rgb(145,167,169));input.setSingleLine(false);input.setMaxLines(2);input.setPadding(dp(13),dp(8),dp(13),dp(8));GradientDrawable ib=new GradientDrawable();ib.setColor(Color.argb(96,8,18,27));ib.setCornerRadius(dp(14));ib.setStroke(dp(1),Color.argb(58,176,209,205));input.setBackground(ib);row.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=ghostButton("GỬI");LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(76),dp(44));sp.setMargins(dp(9),0,0,0);row.addView(send,sp);channel.addView(row);send.setOnClickListener(v->{String q=input.getText().toString().trim();if(!q.isEmpty()&&!sending&&!closing){busy(true);setPhase(DivineManifestationView.Phase.THINKING);conversation.append("\n\n◌  "+q+"\n\n✦  …");bottom();host.onSend(q);}});bottom();syncSession(GodSessionManager.getState());
 }
 public View view(){return root;}public boolean isSending(){return sending||closing;}public void setSessionState(GodSessionManager.State s){a.runOnUiThread(()->syncSession(s));}public void showThinking(){setPhase(DivineManifestationView.Phase.THINKING);}public void showObserving(){setPhase(DivineManifestationView.Phase.OBSERVING);}public void showWarning(){setPhase(DivineManifestationView.Phase.WARNING);}public void showApplying(){setPhase(DivineManifestationView.Phase.APPLYING);}
 public void showReply(String s){setPhase(DivineManifestationView.Phase.SPEAKING);finish(s,true);a.getWindow().getDecorView().postDelayed(()->{if(!sending&&!closing)setPhase(DivineManifestationView.Phase.PRESENT);},900);}public void showSystem(String s){showReply(s);}public void showError(String s){setPhase(DivineManifestationView.Phase.WARNING);String detail=s==null?"":s.trim();finish(detail.isEmpty()?"Sự hiện diện chợt mờ đi.":"Sự hiện diện chợt mờ đi. "+detail,true);}public void showProgress(String s){setPhase(DivineManifestationView.Phase.APPLYING);finish(s,false);}
 public void dismiss(Runnable after){if(closing)return;closing=true;busy(true);setPhase(DivineManifestationView.Phase.DISAPPEARING);root.animate().alpha(0f).setDuration(450).withEndAction(()->{if(after!=null)after.run();}).start();}
 private Button ghostButton(String label){Button b=new Button(a);b.setText(label);b.setTextColor(Color.rgb(235,226,199));b.setTextSize(12);b.setAllCaps(false);b.setPadding(0,0,0,0);GradientDrawable g=new GradientDrawable();g.setColor(Color.argb(76,12,24,32));g.setCornerRadius(dp(15));g.setStroke(dp(1),Color.argb(76,193,216,207));b.setBackground(g);return b;}
 private void setPhase(DivineManifestationView.Phase p){a.runOnUiThread(()->manifestation.setPhase(p));}
 private void syncSession(GodSessionManager.State s){status.setText(label(s));if(s==GodSessionManager.State.CONNECTING)setPhase(DivineManifestationView.Phase.CONNECTING);else if(s==GodSessionManager.State.DEGRADED||s==GodSessionManager.State.OFFLINE)setPhase(DivineManifestationView.Phase.DEGRADED);else if(!sending)setPhase(DivineManifestationView.Phase.PRESENT);}
 private void finish(String reply,boolean release){a.runOnUiThread(()->{String s=conversation.getText().toString();if(s.endsWith("✦  …"))s=s.substring(0,s.length()-1)+(reply==null?"…":reply);else s+="\n\n✦  "+(reply==null?"…":reply);conversation.setText(s);if(release){input.setText("");busy(false);}bottom();});}
 private void bottom(){scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}private void busy(boolean v){sending=v;input.setEnabled(!v);send.setEnabled(!v);}private String label(GodSessionManager.State s){switch(s){case CONNECTING:return"ĐANG ĐẾN";case ONLINE:return"HIỆN DIỆN";case DEGRADED:return"ÁNH SÁNG CHẬP CHỜN";default:return"DƯ ÂM";}}
 private TextView text(String s,float z,int color){TextView t=new TextView(a);t.setText(s);t.setTextSize(z);t.setTextColor(color);return t;}private int dp(int n){return Math.round(n*a.getResources().getDisplayMetrics().density);}
}
