package com.aicharacter.v3;
import java.util.*;
/** Builds Haru's own concepts from perceived similarities. Never reads WorldObject type/tags, biome, or System ecology dictionaries. */
public final class HaruConceptEngine{
 private static final long SAMPLE_MS=10L*60000L,EVIDENCE_COOLDOWN_MS=25L*60000L;
 private static final String[] FEATURES={"mobile","floating","anchored","open_close","luminous","pulse","vibration","tall_branching","soft_sheet","networked","withdraws","recovers"};
 private HaruConceptEngine(){}
 public static void observe(WorldState s,long now){
  if(s==null||BodyRhythmEngine.isSleeping(s))return;ensure(s);if(s.perceptualConcepts.lastObservedAt>0&&now-s.perceptualConcepts.lastObservedAt<SAMPLE_MS)return;
  HaruVisionEngine.Snapshot v=HaruVisionEngine.observe(s);if(v.attention*v.visibility<.28)return;
  List<String> touched=new ArrayList<>();
  for(HaruVisionEngine.Seen seen:v.seen){String key="object:"+seen.id;PersonalLexiconState.Entry le=s.personalLexicon==null?null:s.personalLexicon.entries.get(key);if(le==null||le.encounters<2||seen.clarity<.26)continue;updateProfile(s.perceptualConcepts.profile(key),seen.label,seen.clarity,now);touched.add(key);}
  for(HaruNamingEngine.PhenomenonSnapshot p:HaruNamingEngine.visiblePhenomena(s)){PersonalLexiconState.Entry le=s.personalLexicon==null?null:s.personalLexicon.entries.get(p.key);if(le==null||le.encounters<2)continue;updateProfile(s.perceptualConcepts.profile(p.key),p.description,.62,now);touched.add(p.key);}
  formConcepts(s,touched,now);reviseConcepts(s,touched,now);s.perceptualConcepts.lastObservedAt=now;trim(s,now);
 }
 public static String bestUncertainMember(WorldState s){
  if(s==null||s.perceptualConcepts==null)return"";String best="";double score=0;
  for(PerceptualConceptState.Concept c:s.perceptualConcepts.concepts.values()){if(c.confidence<.24||c.confidence>.76||c.members.size()<2)continue;double uncertainty=1-Math.abs(c.confidence-.48)/.48;for(String key:c.members){if(!key.startsWith("object:"))continue;String id=key.substring(7);if(s.world==null||s.world.object(id)==null)continue;double x=uncertainty+(c.contradictions>0?.15:0);if(x>score){score=x;best=id;}}}return best;
 }
 public static double questionDrive(WorldState s){String id=bestUncertainMember(s);if(id.isEmpty())return 0;double curiosity=s.personality==null?.3:s.personality.curiosity,energy=s.body==null?.5:s.body.energy/100.0;return cl(curiosity*.58+energy*.22+.10);}
 public static String nearestVisibleConceptSummary(WorldState s){
  if(s==null||s.perceptualConcepts==null)return"";HaruVisionEngine.Snapshot v=HaruVisionEngine.observe(s);for(HaruVisionEngine.Seen seen:v.seen){String key="object:"+seen.id;PerceptualConceptState.Concept best=bestConceptFor(s,key);if(best!=null&&best.confidence>=.42)return conceptSentence(s,best,key);}return"";
 }
 public static String diagnostic(WorldState s){ensure(s);StringBuilder b=new StringBuilder("HARU CONCEPTS\n");for(PerceptualConceptState.Concept c:s.perceptualConcepts.concepts.values()){b.append(c.name).append(" | confidence=").append(fmt(c.confidence)).append(" support=").append(c.support).append(" contradiction=").append(c.contradictions).append(" features=").append(c.definingFeatures).append(" members=");for(String k:c.members)b.append(memberLabel(s,k)).append("; ");b.append('\n');}return b.toString();}
 private static void updateProfile(PerceptualConceptState.Profile p,String cue,double clarity,long now){Map<String,Double> f=extract(cue);double alpha=Math.min(.42,.16+.22*clarity);for(String k:FEATURES){double old=p.feature(k),obs=f.getOrDefault(k,0.0);p.features.put(k,PerceptualConceptState.cl(old*(1-alpha)+obs*alpha));}p.observations++;p.lastSeenAt=now;}
 private static Map<String,Double> extract(String cue){String c=cue==null?"":cue.toLowerCase(Locale.ROOT);Map<String,Double>f=new LinkedHashMap<>();put(f,"mobile",has(c,"tự di chuyển","rời dần","tránh xa","chuyển động","lơ lửng")?1:0);put(f,"floating",has(c,"lơ lửng","trôi")?1:0);put(f,"anchored",has(c,"gốc","thân sống","mạng mô thấp","áp sát mặt rễ","thảm sống")?1:0);put(f,"open_close",has(c,"khép","mở dần","co lại")?1:0);put(f,"luminous",has(c,"sáng","ánh bạc","ánh mờ","điểm hồng","nút hồng")?1:0);put(f,"pulse",has(c,"nhịp","co giãn","dày lên")?1:0);put(f,"vibration",has(c,"rung","rung động","nền đất")?1:0);put(f,"tall_branching",has(c,"thân sống cao","nhánh phiến","dọc thân")?1:0);put(f,"soft_sheet",has(c,"phiến mềm","dải lụa","phiến cong")?1:0);put(f,"networked",has(c,"mạng mô","thảm sống","chạy qua")?1:0);put(f,"withdraws",has(c,"thu mình","tránh xa","co lại","giữ khoảng cách")?1:0);put(f,"recovers",has(c,"hồi lại","hồi phục","mở dần","tăng trưởng")?1:0);return f;}
 private static void formConcepts(WorldState s,List<String> touched,long now){
  for(int i=0;i<touched.size();i++)for(int j=i+1;j<touched.size();j++){String a=touched.get(i),b=touched.get(j);PerceptualConceptState.Profile pa=s.perceptualConcepts.profiles.get(a),pb=s.perceptualConcepts.profiles.get(b);if(pa==null||pb==null||pa.observations<3||pb.observations<3)continue;List<String> shared=sharedStrong(pa,pb);double sim=similarity(pa,pb);if(shared.size()<2||sim<.70)continue;String f1=shared.get(0),f2=shared.get(1),id="concept:"+f1+"+"+f2;PerceptualConceptState.Concept c=s.perceptualConcepts.concepts.get(id);boolean created=false;if(c==null){c=new PerceptualConceptState.Concept();c.id=id;c.name=conceptName(f1,f2);c.definingFeatures.add(f1);c.definingFeatures.add(f2);c.createdAt=now;s.perceptualConcepts.concepts.put(id,c);created=true;}boolean changed=c.members.add(a)|c.members.add(b);String ev=id+":"+a+":"+b;if(now-s.perceptualConcepts.evidenceCooldown.getOrDefault(ev,0L)>=EVIDENCE_COOLDOWN_MS){c.support++;c.confidence=PerceptualConceptState.cl(c.confidence+.06+.05*(sim-.70)/.30);c.lastUpdatedAt=now;s.perceptualConcepts.evidenceCooldown.put(ev,now);if(created||changed)remember(s,c,now,created?"She began to suspect that some familiar things belonged to the same kind in her own way of thinking.":"Another observation made one of her self-made groups feel more coherent.");}}
 }
 private static void reviseConcepts(WorldState s,List<String> touched,long now){
  for(PerceptualConceptState.Concept c:s.perceptualConcepts.concepts.values()){List<String> remove=new ArrayList<>();for(String key:new ArrayList<>(c.members)){if(!touched.contains(key))continue;PerceptualConceptState.Profile p=s.perceptualConcepts.profiles.get(key);if(p==null||p.observations<5)continue;double fit=conceptFit(p,c),coolKey=c.id+":contradict:"+key;if(fit<.38&&now-s.perceptualConcepts.evidenceCooldown.getOrDefault(coolKey,0L)>=EVIDENCE_COOLDOWN_MS){c.contradictions++;c.confidence=PerceptualConceptState.cl(c.confidence-.10);s.perceptualConcepts.evidenceCooldown.put(coolKey,now);if(c.contradictions>=2&&fit<.28){remove.add(key);c.revisions++;remember(s,c,now,"She stopped treating one familiar thing as a good member of "+c.name+" because later observations no longer fit.");}}}c.members.removeAll(remove);if(c.members.size()<2)c.confidence=Math.min(c.confidence,.22);}
 }
 private static List<String> sharedStrong(PerceptualConceptState.Profile a,PerceptualConceptState.Profile b){List<String>x=new ArrayList<>();for(String k:FEATURES){double m=Math.min(a.feature(k),b.feature(k));if(m>=.48)x.add(k);}x.sort((u,v)->Double.compare(Math.min(a.feature(v),b.feature(v)),Math.min(a.feature(u),b.feature(u))));return x;}
 private static double similarity(PerceptualConceptState.Profile a,PerceptualConceptState.Profile b){double total=0,weight=0;for(String k:FEATURES){double av=a.feature(k),bv=b.feature(k),w=Math.max(av,bv);if(w<.12)continue;total+=(1-Math.abs(av-bv))*w;weight+=w;}return weight<=0?0:cl(total/weight);}
 private static double conceptFit(PerceptualConceptState.Profile p,PerceptualConceptState.Concept c){if(c.definingFeatures.isEmpty())return 0;double x=0;for(String f:c.definingFeatures)x+=p.feature(f);return cl(x/c.definingFeatures.size());}
 private static PerceptualConceptState.Concept bestConceptFor(WorldState s,String key){PerceptualConceptState.Concept best=null;double score=0;for(PerceptualConceptState.Concept c:s.perceptualConcepts.concepts.values())if(c.members.contains(key)){double v=c.confidence+.03*c.support-.04*c.contradictions;if(v>score){score=v;best=c;}}return best;}
 private static String conceptSentence(WorldState s,PerceptualConceptState.Concept c,String focus){return"Mình tạm xếp "+memberLabel(s,focus)+" vào "+c.name+" vì chúng có vài nét mình thấy lặp lại. Mình chưa chắc đó là một loại thật sự.";}
 private static String conceptName(String a,String b){String pair=a+"+"+b;if(pair.contains("luminous")&&pair.contains("pulse"))return"nhóm Lumera";if(pair.contains("vibration")&&pair.contains("open_close"))return"nhóm Terin";if(pair.contains("mobile")&&pair.contains("floating"))return"nhóm Velai";if(pair.contains("anchored")&&pair.contains("open_close"))return"nhóm Orena";if(pair.contains("soft_sheet")&&pair.contains("vibration"))return"nhóm Selvi";if(pair.contains("networked")&&pair.contains("pulse"))return"nhóm Ravin";if(pair.contains("withdraws")&&pair.contains("mobile"))return"nhóm Neria";return"nhóm "+syllable(a)+syllable(b);}
 private static String syllable(String f){if("luminous".equals(f))return"Lu";if("pulse".equals(f))return"ra";if("vibration".equals(f))return"Te";if("open_close".equals(f))return"ri";if("mobile".equals(f))return"Ve";if("floating".equals(f))return"la";if("anchored".equals(f))return"O";if("soft_sheet".equals(f))return"se";if("networked".equals(f))return"Na";if("withdraws".equals(f))return"mi";if("recovers".equals(f))return"re";return"i";}
 private static String memberLabel(WorldState s,String key){if(key.startsWith("object:")){String id=key.substring(7);WorldObject o=s.world==null?null:s.world.object(id);if(o!=null)return HaruNamingEngine.personalOrDescription(s,o);return id;}PersonalLexiconState.Entry e=s.personalLexicon==null?null:s.personalLexicon.entries.get(key);return e!=null&&e.named()?e.name:e!=null&&!e.lastCue.isEmpty()?e.lastCue:key;}
 private static void remember(WorldState s,PerceptualConceptState.Concept c,long now,String text){CognitionEngine.process(s,new Experience("concept_learning",text,.04,.42).atTime(now).at(HaruPerception.currentPlaceId(s),"").tag("concept").tag(c.id));}
 private static boolean has(String c,String...q){for(String x:q)if(c.contains(x))return true;return false;}
 private static void put(Map<String,Double>m,String k,double v){m.put(k,v);}
 private static void trim(WorldState s,long now){s.perceptualConcepts.evidenceCooldown.entrySet().removeIf(e->now-e.getValue()>3L*24L*3600000L);while(s.perceptualConcepts.concepts.size()>48){Iterator<String>it=s.perceptualConcepts.concepts.keySet().iterator();if(!it.hasNext())break;String k=it.next();PerceptualConceptState.Concept c=s.perceptualConcepts.concepts.get(k);if(c!=null&&c.confidence>.55)break;it.remove();}while(s.perceptualConcepts.profiles.size()>96){Iterator<String>it=s.perceptualConcepts.profiles.keySet().iterator();if(!it.hasNext())break;it.next();it.remove();}}
 private static void ensure(WorldState s){if(s.perceptualConcepts==null)s.perceptualConcepts=new PerceptualConceptState();if(s.personalLexicon==null)s.personalLexicon=new PersonalLexiconState();}
 private static double cl(double v){return Math.max(0,Math.min(1,v));}
 private static String fmt(double v){return String.format(Locale.US,"%.2f",v);}
}