package com.aicharacter.v3;
import java.util.*;
/** Haru coins private names from perceived cues and her own beliefs. Hidden object IDs/taxonomy never provide the name meaning. */
public final class HaruNamingEngine{
 private static final long SAMPLE_MS=8L*60000L,ENCOUNTER_GAP_MS=10L*60000L;
 public static final class Phenomenon{public final String key,description;Phenomenon(String k,String d){key=k;description=d;}}
 private HaruNamingEngine(){}
 public static void observe(WorldState s,long now){
  if(s==null||s.world==null||BodyRhythmEngine.isSleeping(s))return;ensure(s);if(s.personalLexicon.lastObservedAt>0&&now-s.personalLexicon.lastObservedAt<SAMPLE_MS)return;
  HaruVisionEngine.Snapshot v=HaruVisionEngine.observe(s);if(v.attention*v.visibility<.25)return;
  for(HaruVisionEngine.Seen seen:v.seen){WorldObject o=s.world.object(seen.id);if(o==null||(!"creature".equals(o.type)&&!LivingWorldEngine.isLivingFlora(o)))continue;if(seen.clarity<.28)continue;String cue=perceivedCue(s,o);learn(s,"object:"+o.id,o.type,cue,seen.clarity,now);}
  for(Phenomenon p:perceivedPhenomena(s,v))learn(s,p.key,"phenomenon",p.description,Math.min(1,v.attention*v.visibility+.18),now);
  s.personalLexicon.lastObservedAt=now;
 }
 public static String displayLabel(WorldState s,WorldObject o,String raw){if(s==null||o==null||raw==null)return raw;ensure(s);PersonalLexiconState.Entry e=s.personalLexicon.entries.get("object:"+o.id);return e!=null&&e.named()?e.name+" — "+raw:raw;}
 public static String personalName(WorldState s,WorldObject o){if(s==null||o==null)return"";ensure(s);PersonalLexiconState.Entry e=s.personalLexicon.entries.get("object:"+o.id);return e==null?"":e.name;}
 public static String personalOrDescription(WorldState s,WorldObject o){String n=personalName(s,o);return!n.isEmpty()?n:o==null?"":o.haruDescription;}
 public static String nearestNamedVisible(WorldState s){if(s==null||s.world==null)return"";HaruVisionEngine.Snapshot v=HaruVisionEngine.observe(s);for(HaruVisionEngine.Seen x:v.seen){WorldObject o=s.world.object(x.id);String n=personalName(s,o);if(!n.isEmpty())return n;}for(Phenomenon p:perceivedPhenomena(s,v)){PersonalLexiconState.Entry e=s.personalLexicon.entries.get(p.key);if(e!=null&&e.named())return e.name;}return"";}
 public static String diagnostic(WorldState s){ensure(s);StringBuilder b=new StringBuilder("HARU PERSONAL LEXICON\n");for(PersonalLexiconState.Entry e:s.personalLexicon.entries.values())b.append(e.key).append(" | ").append(e.stage()).append(" | name=").append(e.named()?e.name:"?").append(" | encounters=").append(e.encounters).append(" | confidence=").append(fmt(e.confidence)).append(" | salience=").append(fmt(e.salience)).append(" | cue=").append(e.lastCue).append('\n');return b.toString();}
 private static void learn(WorldState s,String key,String kind,String cue,double clarity,long now){PersonalLexiconState.Entry e=s.personalLexicon.entry(key,kind);if(e.firstSeenAt<=0)e.firstSeenAt=now;if(e.lastSeenAt>0&&now-e.lastSeenAt<ENCOUNTER_GAP_MS)return;e.lastSeenAt=now;e.encounters++;e.salience=cl(e.salience*.84+clarity*.24+memorySalience(s,key)*.18);e.lastCue=cue;
  String candidate=coinCandidate(s,kind,cue,key);if(candidate.equals(e.candidate))e.candidateVotes++;else{e.candidate=candidate;e.candidateVotes=1;}
  if(!e.named()&&e.encounters>=3&&e.candidateVotes>=2&&e.salience>=.30){e.name=candidate;e.namedAt=now;e.lastChangedAt=now;e.confidence=.42;rememberNaming(s,e,now,false);}
  else if(e.named()){e.confidence=cl(e.confidence+.045+.035*clarity);String revised=beliefRevisionCandidate(s,key,cue,candidate);if(!revised.equals(e.name)&&!revised.equals(e.candidate)){e.candidate=revised;e.candidateVotes=1;}else if(revised.equals(e.candidate)&&!revised.equals(e.name))e.candidateVotes++;if(e.confidence<.82&&e.encounters>=7&&e.candidateVotes>=4&&!e.candidate.equals(e.name)&&e.renames<2){e.priorNames.add(e.name);while(e.priorNames.size()>4)e.priorNames.remove(0);e.name=e.candidate;e.renames++;e.confidence=.52;e.lastChangedAt=now;rememberNaming(s,e,now,true);}}
 }
 private static void rememberNaming(WorldState s,PersonalLexiconState.Entry e,long now,boolean revised){String text=revised?"She decided the old nickname no longer fit and quietly changed what she called it to "+e.name+".":"After seeing it several times, she privately started calling it "+e.name+".";CognitionEngine.process(s,new Experience("personal_naming",text,.08,.46).atTime(now).at(HaruPerception.currentPlaceId(s),"").tag("language").tag("self_named").tag(e.key));}
 private static String coinCandidate(WorldState s,String kind,String cue,String key){String c=cue==null?"":cue.toLowerCase(Locale.ROOT);String stem;
  if(c.contains("ánh bạc")||c.contains("phủ ánh bạc"))stem="Sela";else if(c.contains("sáng xanh")||c.contains("nhịp sáng"))stem="Lumi";else if(c.contains("điểm hồng")||c.contains("nút hồng"))stem="Rava";else if(c.contains("lơ lửng")||c.contains("dải lụa"))stem="Veli";else if(c.contains("dừng lại")||c.contains("rung động"))stem="Nema";else if(c.contains("sinh vật nhỏ"))stem="Piri";else if(c.contains("thân sống cao")||c.contains("nhánh phiến"))stem="Oren";else if(c.contains("hạt sáng"))stem="Miri";else if(c.contains("đợt rung"))stem="Tera";else if(c.contains("ánh mờ")&&c.contains("ẩm"))stem="Sumi";else{String[]a={"Ari","Eli","Ira","Nui","Ora","Savi","Tali","Yeri"};stem=a[Math.floorMod(c.hashCode(),a.length)];}
  String suffix="phenomenon".equals(kind)?"a":"creature".equals(kind)?"i":"en";return stem+suffix;
 }
 private static String beliefRevisionCandidate(WorldState s,String key,String cue,String fallback){if(!key.startsWith("object:"))return fallback;String id=key.substring(7);for(Map.Entry<String,BeliefState>x:s.beliefStates.entrySet()){BeliefState b=x.getValue();if(b==null||b.confidence<.58)continue;String k=x.getKey();if(k.startsWith("eco_pair:")&&k.contains(id)){if("may_avoid_each_other".equals(b.value))return"Lani";if("may_seek_each_other".equals(b.value))return"Sori";}if(k.startsWith("eco_hyp:")&&k.contains(id)&&"may_affect_response".equals(b.value))return"Reni";}return fallback;}
 private static double memorySalience(WorldState s,String key){if(s==null||key==null)return 0;String id=key.startsWith("object:")?key.substring(7):key;double best=0;for(MemoryEntry m:s.memories)if(m.tags.contains(id)||m.tags.contains(key)||m.participants.contains(id))best=Math.max(best,Math.abs(m.valence)*.45+m.importance*.55);return cl(best);}
 private static String perceivedCue(WorldState s,WorldObject o){String cue=o.haruDescription==null?"":o.haruDescription;PersonalLexiconState.Entry e=s.personalLexicon==null?null:s.personalLexicon.entries.get("object:"+o.id);if(e!=null&&e.named()&&cue.startsWith(e.name))cue=cue.substring(e.name.length());return cue;}
 private static List<Phenomenon> perceivedPhenomena(WorldState s,HaruVisionEngine.Snapshot v){List<Phenomenon>x=new ArrayList<>();if(s==null||s.world==null||v==null||v.visibility<.34)return x;WorldArea a=s.world.area(v.areaId);if(a==null)return x;BiomeLifeFieldState f=LivingWorldEngine.field(s,a.id);if(f==null)return x;if(f.sense.lumenSense>.56&&f.densityVitality>.46)x.add(new Phenomenon("phenomenon:"+a.id+":lumen_drift","những hạt sáng nhỏ trôi thành nhịp trong không khí"));if(f.motionDrive>.48&&f.sense.vibrationSense>.35)x.add(new Phenomenon("phenomenon:"+a.id+":field_pulse","những đợt rung mảnh chạy qua thảm sống quanh đây"));if(f.sense.moistureSense>.70&&s.environment.ambientBrightness<.62)x.add(new Phenomenon("phenomenon:"+a.id+":moist_glow","một lớp ánh mờ dày lên trong không khí ẩm"));return x;}
 private static void ensure(WorldState s){if(s.personalLexicon==null)s.personalLexicon=new PersonalLexiconState();}
 private static double cl(double v){return Math.max(0,Math.min(1,v));}
 private static String fmt(double v){return String.format(Locale.US,"%.2f",v);}
}