package com.aicharacter.v3;
import java.util.Locale;
public final class HaruMind {
 public static final class Response{public final String speech;public final boolean controlAttempt;public final String expression;public Response(String s,boolean c){this(s,c,"");}public Response(String s,boolean c,String e){speech=s;controlAttempt=c;expression=e==null?"":e;}}
 private HaruMind(){}
 private static Response expressed(WorldState s,String speech,boolean control){long now=System.currentTimeMillis();return new Response(OfflineSpeechContext.enrich(s,speech,now),control,BehaviorExpressionEngine.observe(s,now).stageDirection());}
 private static Response finish(WorldState s,String reunion,String speech,boolean control){String a=reunion==null?"":reunion.trim(),b=speech==null?"":speech.trim();String out=a.isEmpty()?b:b.isEmpty()?a:a+"\n\n"+b;return expressed(s,out.isEmpty()?"…":out,control);}
 public static Response respond(WorldState s,String input){String raw=input==null?"":input.trim();String q=raw.toLowerCase(Locale.ROOT);if(q.isEmpty())return expressed(s,"…",false);s.lastCatSeenAt=System.currentTimeMillis();String reunion="";if(s.reunionContext!=null&&!s.reunionContext.isEmpty()){Response rr=ReunionEngine.process(s,System.currentTimeMillis());if(rr!=null&&rr.speech!=null)reunion=rr.speech;}IntentParser.Parsed parsed=IntentParser.parse(raw);
  if(parsed.isControlAttempt()){CognitionEngine.experience(s,"boundary","The cat tried to directly control what she did.",-.72,.82,"control","player");return finish(s,reunion,"Cậu không có quyền điều khiển mình.",true);}
  if(parsed.act==IntentParser.SpeechAct.NAME_PROPOSAL)return finish(s,reunion,"Nếu cậu muốn đề nghị một tên, hãy dùng “LIÊN HỆ VỚI THẦN”. Mình không tự biến một lời gọi thành tên chính thức.",false);
  if(q.contains("đi dạo")||q.contains("walk")){double memory=CognitionEngine.recalledValence(s,"player");double willingness=s.relationship.trust*.45+s.relationship.comfort*.55+s.relationship.attachment*.2+memory*8-s.relationship.irritation*.35-s.relationship.hurt*.45-s.body.pain*.8+(s.body.energy-35)*.18;if(willingness>4){s.currentIntention="walk_with_cat";s.haruActivity="walking with the cat";CognitionEngine.experience(s,"shared_activity","She accepted the cat's invitation to walk by the lake.",.45,.65,"respect","kind","player");return finish(s,reunion,LocalDialogueEngine.walkAccepted(s,raw),false);}CognitionEngine.experience(s,"decision","She declined an invitation because her current state or feelings mattered more.",-.08,.35,"player");return finish(s,reunion,LocalDialogueEngine.walkDeclined(s,raw),false);}
  if(q.contains("ổn không")||q.contains("khỏe không")){CognitionEngine.experience(s,"care","The cat checked how she was feeling.",.3,.48,"kind","player");return finish(s,reunion,LocalDialogueEngine.health(s,raw),false);}
  if(q.contains("tên")||q.contains("name"))return finish(s,reunion,s.nameState.isNamed()?"Tên mình được gọi là “"+s.nameState.officialName+"”. Mình nhớ lúc cái tên ấy trở thành một phần của thế giới.":"Mình chưa có tên chính thức.",false);
  CognitionEngine.experience(s,"conversation","The cat said: "+raw,.08,.34,"player");return finish(s,reunion,LocalDialogueEngine.generic(s,raw),false);
 }
}