package com.aicharacter.v3;import java.util.*;
/** Shared causal choice. Needs are pressures, not commands; memory, beliefs, personality, world and outcomes compete. */
public final class LifeDecisionEngine {private LifeDecisionEngine(){}
 public static LifeDecision choose(WorldState s,long now){NeedState n=NeedState.evaluate(s);double hour=s.worldMinutes/60.0;List<LifeDecision> c=new ArrayList<>();WorldArea here=s.world==null?null:s.world.areaAt(s.haruX);double exposure=WorldSemantics.exposure(here);boolean alreadyDry=exposure<.35;
  add(c,new Intention("sleep",0,"rest","shelter_01","sleep",.9,now+10800000),"rest_need",n.rest,"night_context",(hour>=22||hour<6)?18:0,"pain",s.body.pain*.6);
  LifeDecision shelter=add(c,new Intention("seek_shelter",0,"safety","shelter_01","get comfortable and safe",.78,now+7200000),"physical_comfort_need",alreadyDry?-n.physicalComfort*.30:n.physicalComfort*.72,"safety_need",n.safety*.42,"wetness",alreadyDry?-s.worldWetness*8:s.worldWetness*12,"already_sheltered",alreadyDry?-24:0,"thermal_relief",thermalRelief(s,alreadyDry),"breathing_relief",breathingRelief(s,alreadyDry));psychological(s,shelter,"home_shelter","seek_shelter",false,now);world(s,shelter,"home_shelter",true);
  LifeDecision recover=add(c,new Intention("recover",0,"rest","bench_lake_01","recover energy",.62,now+5400000),"rest_need",n.rest*.38,"low_energy",Math.max(0,48-s.body.energy)*.25,"pain",s.body.pain*.18,"physical_comfort",-n.physicalComfort*.16);psychological(s,recover,"lakeside","recover",environmentRisk(s,"lakeside",n),now);world(s,recover,"lakeside",false);
  LifeDecision reflect=add(c,new Intention("reflect",0,"curiosity","bench_lake_01","reflect",.3,now+10800000),"curiosity_need",n.curiosity*.2,"late_light_context",hour>=16&&hour<19?7:0,"physical_comfort",-n.physicalComfort*.20,"energy",(s.body.energy-45)*.12);psychological(s,reflect,"lakeside","reflect",environmentRisk(s,"lakeside",n),now);world(s,reflect,"lakeside",false);
  LifeDecision observe=add(c,new Intention("observe_lake",0,"curiosity","bench_lake_01","observe the lake",.24,now+7200000),"curiosity_need",n.curiosity*.24,"calm",s.emotion.calm*8,"energy",Math.max(0,s.body.energy-35)*.08,"physical_comfort",-n.physicalComfort*.17);psychological(s,observe,"lakeside","observe",environmentRisk(s,"lakeside",n),now);world(s,observe,"lakeside",false);
  LifeDecision explore=add(c,new Intention("explore_garden",0,"curiosity","garden_path","notice something different",.32,now+7200000),"curiosity_need",n.curiosity*.28,"personality_curiosity",s.personality.curiosity*10,"energy",Math.max(0,s.body.energy-42)*.12,"physical_comfort",-n.physicalComfort*.22,"pain",-s.body.pain*.35);psychological(s,explore,"garden_path","explore",environmentRisk(s,"garden_path",n),now);world(s,explore,"garden_path",false);
  LifeDecision creature=add(c,new Intention("watch_reedling",0,"curiosity","reedling_01","quietly observe the small creature",.26,now+5400000),"curiosity_need",n.curiosity*.22,"creature_interest",s.knowledge.getOrDefault("reedling",0)*2.5,"energy",Math.max(0,s.body.energy-38)*.07,"physical_comfort",-n.physicalComfort*.15);psychological(s,creature,"lakeside","observe_creature",environmentRisk(s,"lakeside",n),now);world(s,creature,"lakeside",false);
  LifeDecision solitude=add(c,new Intention("seek_solitude",0,"solitude","lake_tree_03","quiet",.4,now+7200000),"solitude_need",n.solitude,"hurt",s.relationship.hurt*.22,"physical_comfort",-n.physicalComfort*.14);psychological(s,solitude,"quiet_grove","seek_solitude",environmentRisk(s,"quiet_grove",n),now);world(s,solitude,"quiet_grove",false);
  LifeDecision breathe=add(c,new Intention("quiet_pause",0,"solitude","lake_tree_03","settle emotions",.22,now+3600000),"tension",s.mood.arousal*9+s.emotion.anger*12+s.emotion.sadness*7,"solitude_need",n.solitude*.18,"critical_energy",s.body.energy<20?-15:0,"physical_comfort",-n.physicalComfort*.12);psychological(s,breathe,"quiet_grove","quiet_pause",environmentRisk(s,"quiet_grove",n),now);world(s,breathe,"quiet_grove",false);
  double away=Math.max(0,(now-s.lastCatSeenAt)/3600000.0),belief=s.beliefStates.containsKey("cat_returns")?s.beliefStates.get("cat_returns").confidence:.5;
  LifeDecision find=add(c,new Intention("find_cat",0,"connection",rememberedCatPlace(s),"find cat",.65,now+14400000),"absence",Math.min(25,away*2.2),"returns_belief",-belief*7,"loneliness",s.mood.loneliness*18,"connection_need",n.connection*.20,"physical_comfort",-n.physicalComfort*.08,"known_carried",(s.catState.carryKnownByGirl&&"girl".equals(s.catState.attachedToEntity))?-1000:0);psychological(s,find,find.intention.targetId,"find_cat",environmentRisk(s,find.intention.targetId,n),now);world(s,find,find.intention.targetId,true);
  for(LifeDecision d:c)d.intention.utility=sum(d.reasons)+(d.intention.id.equals(s.currentIntention)?5:0);
  DeliberationEngine.apply(s,c,now);c.sort((a,b)->Double.compare(b.intention.utility,a.intention.utility));LifeDecision selected=c.get(0);
  if(s.planState!=null&&s.planState.active()){LifeDecision current=null;for(LifeDecision d:c)if(d.intention.id.equals(s.planState.intentionId)){current=d;break;}if(current!=null&&selected.intention.utility-current.intention.utility<5+12*s.planState.commitment)selected=current;}
  DeliberationEngine.recordThought(s,c,selected,now);s.lastDecisionTrace=trace(c,selected,s,n);return selected;}
 private static double thermalRelief(WorldState s,boolean sheltered){if(!sheltered||s.thermal==null)return 0;return Math.max(s.thermal.coldLoad,s.thermal.heatLoad)*34;}\n private static double breathingRelief(WorldState s,boolean sheltered){if(!sheltered||s.respiration==null)return 0;return s.respiration.breathingLoad*18;}\n private static boolean environmentRisk(WorldState s,String targetId,NeedState n){WorldArea a=s.world==null?null:s.world.area(targetId);if(a==null&&s.world!=null){WorldObject o=s.world.object(targetId);if(o!=null)a=s.world.area(o.areaId);}if(a==null)return false;double exposure=WorldSemantics.exposure(a);double thermal=s.thermal==null?0:Math.max(s.thermal.coldLoad,s.thermal.heatLoad),breath=s.respiration==null?0:s.respiration.breathingLoad;return exposure>.55&&(n.safety>32||n.physicalComfort>38||s.body.pain>20||s.body.energy<25||thermal>.45||breath>.35);}
 private static void world(WorldState s,LifeDecision d,String areaId,boolean urgent){WorldArea a=s.world==null?null:s.world.area(areaId);if(a==null){WorldObject o=s.world==null?null:s.world.object(areaId);if(o!=null)a=s.world.area(o.areaId);}if(a==null)return;d.reason("world_comfort",WorldSemantics.comfort(s,a)*10);d.reason("visibility",urgent?(s.visibility-.5)*4:(s.visibility-.5)*2);}
 private static void psychological(WorldState s,LifeDecision d,String place,String action,boolean risk,long now){HistoryDecisionEngine.place(s,place,now,d.reasons);HistoryDecisionEngine.personality(s,action,risk,d.reasons);HistoryDecisionEngine.habit(s,action,place,now,d.reasons);HistoryDecisionEngine.relationship(s,action,d.reasons);}
 private static double sum(Map<String,Double>m){double v=0;for(double x:m.values())v+=x;return v;}
 private static String trace(List<LifeDecision>c,LifeDecision selected,WorldState s,NeedState n){StringBuilder b=new StringBuilder("WHY HARU V108\nperception=").append(HaruPerception.currentPlaceId(s)).append(" mood=").append(s.mood.label()).append(" bodyEnergy=").append(s.body.energy).append(" pain=").append(s.body.pain).append(" needs[rest=").append(String.format(Locale.US,"%.1f",n.rest)).append(", safety=").append(String.format(Locale.US,"%.1f",n.safety)).append(", comfort=").append(String.format(Locale.US,"%.1f",n.physicalComfort)).append(", connection=").append(String.format(Locale.US,"%.1f",n.connection)).append(", solitude=").append(String.format(Locale.US,"%.1f",n.solitude)).append(", curiosity=").append(String.format(Locale.US,"%.1f",n.curiosity)).append("]\n");for(LifeDecision d:c)b.append("- ").append(d.explain()).append(" total=").append(String.format(Locale.US,"%.2f",d.intention.utility)).append('\n');return b.append("selected=").append(selected.intention.id).toString();}
 private static LifeDecision add(List<LifeDecision>out,Intention i,Object...pairs){LifeDecision d=new LifeDecision(i);for(int x=0;x<pairs.length;x+=2)d.reason((String)pairs[x],((Number)pairs[x+1]).doubleValue());out.add(d);return d;}
 private static String rememberedCatPlace(WorldState s){List<MemoryEntry>ms=MemoryRetrievalEngine.retrieve(s,null,"cat","player",8);for(MemoryEntry m:ms)if(m.location!=null&&!m.location.isEmpty())return m.location;for(BeliefState b:s.beliefStates.values())if(b.subject.startsWith("cat_at:")&&b.confidence>.55)return b.subject.substring(7);return"home_shelter";}
}