package com.aicharacter.v3;import java.util.*;
/** Deterministic diagnostic scenarios. Mutates the supplied dev world only. */
public final class LifeDevTest {private LifeDevTest(){}
 public static String runAll(WorldState s){StringBuilder r=new StringBuilder();r.append(testMeaningfulPlace(s)).append('\n');r.append(testBelief(s)).append('\n');r.append(testCreature(s)).append('\n');r.append(testAbsence(s));return r.toString();}
 public static String testMeaningfulPlace(WorldState s){double before=CognitionEngine.placeAttraction(s,"bench_lake_01");for(int i=0;i<5;i++)CognitionEngine.process(s,new Experience("dev_place","A calm, positive moment happened at the lakeside bench.",.65,.55).at("lakeside","bench_lake_01").tag("reflect").tag("world"));double after=CognitionEngine.placeAttraction(s,"bench_lake_01");return"LIFE A meaningful-place: "+(after>before?"PASS":"FAIL")+" attraction "+fmt(before)+" -> "+fmt(after);}
 public static String testBelief(WorldState s){BeliefState b=s.beliefStates.get("cat_returns");if(b==null){b=new BeliefState("cat_returns","uncertain",.4);s.beliefStates.put("cat_returns",b);}double a=b.confidence;for(int i=0;i<4;i++)b.revise("usually_returns",.45,"Observed another return.");double high=b.confidence;b.revise("may_stay_away",.5,"A long contradictory absence occurred.");return"LIFE C belief-evidence: "+(high>a&&b.confidence!=high?"PASS":"FAIL")+" confidence "+fmt(a)+" -> "+fmt(high)+" -> "+fmt(b.confidence);}
 public static String testCreature(WorldState s){double before=s.reedling.trustHaru;int n=s.reedling.encountersHaru;s.reedling.meetHaru(true,System.currentTimeMillis());s.reedling.meetHaru(true,System.currentTimeMillis());return"LIFE D creature persistence: "+(s.reedling.trustHaru>before&&s.reedling.encountersHaru==n+2?"PASS":"FAIL")+" trust "+fmt(before)+" -> "+fmt(s.reedling.trustHaru);}
 public static String testAbsence(WorldState s){long old=s.lastOpenedAt;s.lastOpenedAt=System.currentTimeMillis()-12*3600000L;int before=s.memories.size();String story=OfflineLifeEngine.reconstruct(s,System.currentTimeMillis());boolean ok=s.memories.size()>before&&!story.isEmpty()&&s.lastAbsenceMinutes>=700;return"LIFE B bounded-offline-sequence: "+(ok?"PASS":"FAIL")+" events/story generated, Haru x="+(int)s.haruX;}
 private static String fmt(double v){return String.format(Locale.US,"%.2f",v);}}
