package com.aicharacter.v3;import java.util.*;
/** Shared causal choice. Needs are pressures, not commands; memory, beliefs, personality, world and outcomes compete. */
public final class LifeDecisionEngine {private LifeDecisionEngine(){}
 public static LifeDecision choose(WorldState s,long now){NeedState n=NeedState.evaluate(s);double hour=s.worldMinutes/60.0;List<LifeDecision> c=new ArrayList<>();WorldArea here=s.world==null?null:s.world.areaAt(s.haruX);double exposure=WorldSemantics.exposure(here);boolean alreadyDry=exposure<.35;double mobility=MusculoskeletalEngine.locomotorCapacity(s)*BodyInstinctEngine.movementCapacity(s)*NervousSystemEngine.locomotorConstraint(s),regionalInjury=s.localizedPain==null?0:s.localizedPain.maxLoad(),exertionPenalty=Math.max(0,.68-mobility)*38+regionalInjury*18;String recoveryTarget=recoveryTarget(s,mobility,regionalInjury);
  add(c,new Intention("sleep",0,"rest","shelter_01","sleep",.9,now+10800000),"rest_need",n.rest,"night_context",(hour>=22||hour<6)?18:0,"pain",s.body.pain*.6);
  LifeDecision shelter=add(c,new Intention("seek_shelter",0,"safety","shelter_01","get comfortable and safe",.78,now+7200000),"physical_comfort_need",alreadyDry?-n.physicalComfort*.30:n.physicalComfort*.72,"safety_need",n.safety*.42,"wetness",alreadyDry?-s.worldWetness*8:s.worldWetness*12,"already_sheltered",alreadyDry?-24:0,"thermal_relief",thermalRelief(s,alreadyDry),"breathing_relief",breathingRelief(s,alreadyDry));psychological(s,shelter,"home_shelter","seek_shelter",false,now);world(s,shelter,"home_shelter",true);
  LifeDecision recover=add(c,new Intention("recover",0,"rest",recoveryTarget,"recover energy",.62,now+5400000),"rest_need",n.rest*.38,"low_energy",Math.max(0,48-s.body.energy)*.25,"pain",s.body.pain*.18,"physical_comfort",-n.physicalComfort*.16,"injury_recovery",regionalInjury*28+Math.max(0,.62-mobility)*30);psychological(s,recover,recoveryTarget,"recover",environmentRisk(s,recoveryTarget,n),now);world(s,recover,recoveryTarget,false);
  LifeDecision eat=add(c,new Intention("eat",0,"nutrition","shelter_01","eat enough to reduce hunger",.58,now+5400000),"hunger",n.hunger*.72,"low_nutrient_reserve",(1-s.digestive.nutrientReserve)*18,"already_full",-s.digestive.stomachFood*13);psychological(s,eat,"home_shelter","eat",false,now);world(s,eat,"home_shelter",true);
  LifeDecision drink=add(c,new Intention("drink",0,"hydration","shelter_01","drink water",.74,now+3600000),"thirst",n.thirst*.88,"heat",s.thermal==null?0:s.thermal.heatLoad*14,"low_hydration",(1-s.hydration.hydration)*16);psychological(s,drink,"home_shelter","drink",false,now);world(s,drink,"home_shelter",true);
  LifeDecision toilet=add(c,new Intention("toilet",0,"elimination","shelter_01","relieve bladder pressure privately",.66,now+3600000),"bladder_pressure",n.elimination*.92,"privacy_home",n.elimination>45?8:0);psychological(s,toilet,"home_shelter","toilet",false,now);world(s,toilet,"home_shelter",true);
  LifeDecision reflect=add(c,new Intention("reflect",0,"curiosity","bench_lake_01","reflect",.3,now+10800000),"curiosity_need",n.curiosity*.2,"late_light_context",hour>=16&&hour<19?7:0,"physical_comfort",-n.physicalComfort*.20,"energy",(s.body.energy-45)*.12);psychological(s,reflect,"lakeside","reflect",environmentRisk(s,"lakeside",n),now);world(s,reflect,"lakeside",false);
  LifeDecision observe=add(c,new Intention("observe_lake",0,"curiosity","bench_lake_01","observe the lake",.24,now+7200000),"curiosity_need",n.curiosity*.24,"calm",s.emotion.calm*8,"energy",Math.max(0,s.body.energy-35)*.08,"physical_comfort",-n.physicalComfort*.17,"exertion",-exertionPenalty*.60);psychological(s,observe,"lakeside","observe",environmentRisk(s,"lakeside",n),now);world(s,observe,"lakeside",false);
  LifeDecision explore=add(c,new Intention("explore_garden",0,"curiosity","garden_path","notice something different",.32,now+7200000),"curiosity_need",n.curiosity*.28,"personality_curiosity",s.personality.curiosity*10,"energy",Math.max(0,s.body.energy-42)*.12,"physical_comfort",-n.physicalComfort*.22,"pain",-s.body.pain*.35,"exertion",-exertionPenalty);psychological(s,explore,"garden_path","explore",environmentRisk(s,"garden_path",n),now);world(s,explore,"garden_path",false);
  LifeDecision creature=add(c,new Intention("watch_reedling",0,"curiosity","reedling_01","quietly observe the small creature",.26,now+5400000),"curiosity_need",n.curiosity*.22,"creature_interest",s.knowledge.getOrDefault("reedling",0)*2.5,"energy",Math.max(0,s.body.energy-38)*.07,"physical_comfort",-n.physicalComfort*.15,"exertion",-exertionPenalty*.65);psychological(s,creature,"lakeside","observe_creature",environmentRisk(s,"lakeside",n),now);world(s,creature,"lakeside",false);
  LifeDecision solitude=add(c,new Intention("seek_solitude",0,"solitude","lake_tree_03","quiet",.4,now+7200000),"solitude_need",n.solitude,"hurt",s.relationship.hurt*.22,"physical_comfort",-n.physicalComfort*.14,"exertion",-exertionPenalty*.70);psychological(s,solitude,"quiet_grove","seek_solitude",environmentRisk(s,"quiet_grove",n),now);world(s,solitude,"quiet_grove",false);
  LifeDecision breathe=add(c,new Intention("quiet_pause",0,"solitude","lake_tree_03","settle emotions",.22,now+3600000),"tension",s.mood.arousal*9+s.emotion.anger*12+s.emotion.sadness*7,"solitude_need",n.solitude*.18,"critical_energy",s.body.energy<20?-15:0,"physical_comfort",-n.physicalComfort*.12,"exertion",-exertionPenalty*.55);psychological(s,breathe,"quiet_grove","quiet_pause",environmentRisk(s,"quiet_grove",n),now);world(s,breathe,"quiet_grove",false);
  if(s.herbalism==null)s.herbalism=new HerbalismState();double herbalNeed=HerbalismEngine.bodyNeed(s),herbalCuriosity=n.curiosity*.22;WorldObject seenHerb=visibleHerb(s),rememberedHerb=seenHerb!=null?seenHerb:rememberedHerbTarget(s);
  if(seenHerb!=null){HerbalismState.Knowledge hk=s.herbalism.knowledge.get(seenHerb.dictionaryRef);int obs=hk==null?0:hk.observations;if(obs<4){LifeDecision study=add(c,new Intention("study_herb",0,"curiosity",seenHerb.id,"understand an unfamiliar living plant a little better",.20,now+5400000),"curiosity",herbalCuriosity,"novelty",obs==0?10:Math.max(1,5-obs),"body_condition",herbalNeed*5,"safety_cost",-n.safety*.07,"exertion",-exertionPenalty*.28);psychological(s,study,seenHerb.areaId,"observe",environmentRisk(s,seenHerb.id,n),now);world(s,study,seenHerb.id,false);}}
  if(rememberedHerb!=null&&s.herbalism.carriedCount<3){HerbalismState.Knowledge hk=s.herbalism.knowledge.get(rememberedHerb.dictionaryRef);if(hk!=null&&hk.observations>0&&HerbalismEngine.appearsHarvestable(s,rememberedHerb)&&(s.herbalism.carriedHerbId.isEmpty()||rememberedHerb.dictionaryRef.equals(s.herbalism.carriedHerbId))){LifeDecision gather=add(c,new Intention("harvest_herb",0,"curiosity",rememberedHerb.id,"collect a small remembered sample for careful investigation",.18,now+7200000),"curiosity",n.curiosity*.10,"observed_before",Math.min(7,hk.observations*1.6),"body_relevance",herbalNeed*11,"learned_effect",hk.effectConfidence*12,"uncertainty_cost",-(1-hk.safetyConfidence)*7,"exertion",-exertionPenalty*.42);psychological(s,gather,rememberedHerb.areaId,"explore",environmentRisk(s,rememberedHerb.id,n),now);world(s,gather,rememberedHerb.id,false);}}
  if(s.herbalism.carriedCount>0){HerbalismState.Knowledge hk=s.herbalism.knowledge.get(s.herbalism.carriedHerbId);double trials=hk==null?0:hk.trials;LifeDecision prep=add(c,new Intention("prepare_herb",0,"curiosity","shelter_01","try a cautious preparation method on the collected sample",.16,now+7200000),"curiosity",n.curiosity*.12,"sample_waiting",8,"body_relevance",herbalNeed*9,"untried_method",trials==0?6:Math.max(1,4-trials),"home_safety",5);psychological(s,prep,"home_shelter","reflect",false,now);world(s,prep,"home_shelter",false);}
  if(!s.herbalism.preparedHerbId.isEmpty()&&HerbalismEngine.canAttemptTrial(s)){HerbalismState.Knowledge hk=s.herbalism.knowledge.get(s.herbalism.preparedHerbId);double safety=hk==null?.10:hk.safetyConfidence,effect=hk==null?.05:hk.effectConfidence;HerbalismState.MethodEvidence me=hk==null?null:hk.methods.get(s.herbalism.preparedMethod);double methodSafety=me==null?.12:me.safetyConfidence,methodEffect=me==null?.05:me.effectConfidence;LifeDecision trial=add(c,new Intention("try_herb",0,"recovery","shelter_01","test a very small prepared sample and observe the result",.22,now+5400000),"body_need",herbalNeed*24,"past_help",effect*8+methodEffect*10,"caution",-((1-safety)*8+(1-methodSafety)*9+n.safety*.05),"curiosity",n.curiosity*.07,"home_context",4);psychological(s,trial,"home_shelter","reflect",false,now);world(s,trial,"home_shelter",true);}
  double away=Math.max(0,(now-s.lastCatSeenAt)/3600000.0),belief=s.beliefStates.containsKey("cat_returns")?s.beliefStates.get("cat_returns").confidence:.5;
  LifeDecision find=add(c,new Intention("find_cat",0,"connection",rememberedCatPlace(s),"find cat",.65,now+14400000),"absence",Math.min(25,away*2.2),"returns_belief",-belief*7,"loneliness",s.mood.loneliness*18,"connection_need",n.connection*.20,"physical_comfort",-n.physicalComfort*.08,"injury_cost",-exertionPenalty*.80,"known_carried",(s.catState.carryKnownByGirl&&"girl".equals(s.catState.attachedToEntity))?-1000:0);psychological(s,find,find.intention.targetId,"find_cat",environmentRisk(s,find.intention.targetId,n),now);world(s,find,find.intention.targetId,true);
  for(LifeDecision d:c)d.intention.utility=sum(d.reasons)+(d.intention.id.equals(s.currentIntention)?5:0);
  DeliberationEngine.apply(s,c,now);c.sort((a,b)->Double.compare(b.intention.utility,a.intention.utility));LifeDecision selected=c.get(0);
  if(s.planState!=null&&s.planState.active()){LifeDecision current=null;for(LifeDecision d:c)if(d.intention.id.equals(s.planState.intentionId)){current=d;break;}if(current!=null&&selected.intention.utility-current.intention.utility<5+12*s.planState.commitment)selected=current;}
  DeliberationEngine.recordThought(s,c,selected,now);s.lastDecisionTrace=trace(c,selected,s,n);return selected;}
 private static double thermalRelief(WorldState s,boolean sheltered){if(!sheltered||s.thermal==null)return 0;return Math.max(s.thermal.coldLoad,s.thermal.heatLoad)*34;}
 private static double breathingRelief(WorldState s,boolean sheltered){if(!sheltered||s.respiration==null)return 0;return s.respiration.breathingLoad*18;}
 private static boolean environmentRisk(WorldState s,String targetId,NeedState n){WorldArea a=s.world==null?null:s.world.area(targetId);if(a==null&&s.world!=null){WorldObject o=s.world.object(targetId);if(o!=null)a=s.world.area(o.areaId);}if(a==null)return false;double exposure=WorldSemantics.exposure(a);double thermal=s.thermal==null?0:Math.max(s.thermal.coldLoad,s.thermal.heatLoad),breath=s.respiration==null?0:s.respiration.breathingLoad;return exposure>.55&&(n.safety>32||n.physicalComfort>38||s.body.pain>20||s.body.energy<25||thermal>.45||breath>.35);}
 private static void world(WorldState s,LifeDecision d,String areaId,boolean urgent){WorldArea a=s.world==null?null:s.world.area(areaId);if(a==null){WorldObject o=s.world==null?null:s.world.object(areaId);if(o!=null)a=s.world.area(o.areaId);}if(a==null)return;d.reason("world_comfort",WorldSemantics.comfort(s,a)*10);d.reason("visibility",urgent?(s.visibility-.5)*4:(s.visibility-.5)*2);}
 private static void psychological(WorldState s,LifeDecision d,String place,String action,boolean risk,long now){HistoryDecisionEngine.place(s,place,now,d.reasons);HistoryDecisionEngine.personality(s,action,risk,d.reasons);HistoryDecisionEngine.habit(s,action,place,now,d.reasons);HistoryDecisionEngine.relationship(s,action,d.reasons);}
 private static double sum(Map<String,Double>m){double v=0;for(double x:m.values())v+=x;return v;}
 private static String trace(List<LifeDecision>c,LifeDecision selected,WorldState s,NeedState n){StringBuilder b=new StringBuilder("WHY HARU V108\nperception=").append(HaruPerception.currentPlaceId(s)).append(" mood=").append(s.mood.label()).append(" bodyEnergy=").append(s.body.energy).append(" pain=").append(s.body.pain).append(" needs[rest=").append(String.format(Locale.US,"%.1f",n.rest)).append(", safety=").append(String.format(Locale.US,"%.1f",n.safety)).append(", comfort=").append(String.format(Locale.US,"%.1f",n.physicalComfort)).append(", connection=").append(String.format(Locale.US,"%.1f",n.connection)).append(", solitude=").append(String.format(Locale.US,"%.1f",n.solitude)).append(", curiosity=").append(String.format(Locale.US,"%.1f",n.curiosity)).append(", hunger=").append(String.format(Locale.US,"%.1f",n.hunger)).append(", thirst=").append(String.format(Locale.US,"%.1f",n.thirst)).append(", elimination=").append(String.format(Locale.US,"%.1f",n.elimination)).append("]\n");for(LifeDecision d:c)b.append("- ").append(d.explain()).append(" total=").append(String.format(Locale.US,"%.2f",d.intention.utility)).append('\n');return b.append("selected=").append(selected.intention.id).toString();}
 private static LifeDecision add(List<LifeDecision>out,Intention i,Object...pairs){LifeDecision d=new LifeDecision(i);for(int x=0;x<pairs.length;x+=2)d.reason((String)pairs[x],((Number)pairs[x+1]).doubleValue());out.add(d);return d;}
 private static String recoveryTarget(WorldState s,double mobility,double regionalInjury){if(s==null||s.world==null)return"bench_lake_01";WorldArea here=s.world.areaAt(s.haruX);if(here==null)return"bench_lake_01";if(mobility<.58||regionalInjury>.35)return here.id;WorldObject nearest=null;double best=Double.MAX_VALUE;for(WorldObject o:s.world.objects){if(o==null||!o.enabled||!o.interactable||!here.id.equals(o.areaId)||!(o.tags.contains("rest")||o.tags.contains("sit")))continue;double d=Math.abs(PhysicalInteraction.targetXForAction(s,o,"girl",s.haruX,"REST_PROTECT")-s.haruX);if(d<best){best=d;nearest=o;}}return nearest==null?"bench_lake_01":nearest.id;}
 private static WorldObject visibleHerb(WorldState s){if(s==null||s.world==null)return null;WorldObject best=null;double d=Double.MAX_VALUE;for(WorldObject o:s.world.objects){if(!HerbalismEngine.isHerb(o)||!HaruVisionEngine.canSee(s,o))continue;double x=Math.abs(HaruVisionEngine.actualX(s,o)-s.haruX);if(x<d){d=x;best=o;}}return best;}
 private static WorldObject rememberedHerbTarget(WorldState s){if(s==null||s.world==null)return null;for(int i=s.memories.size()-1;i>=0;i--){MemoryEntry m=s.memories.get(i);if(!m.hasTag("herb"))continue;for(WorldObject o:s.world.objects)if(HerbalismEngine.isHerb(o)&&(m.hasTag(o.id)||m.hasTag("herb:"+o.dictionaryRef)))return o;}return null;}
 private static String rememberedCatPlace(WorldState s){List<MemoryEntry>ms=MemoryRetrievalEngine.retrieve(s,null,"cat","player",8);for(MemoryEntry m:ms)if(m.location!=null&&!m.location.isEmpty())return m.location;for(BeliefState b:s.beliefStates.values())if(b.subject.startsWith("cat_at:")&&b.confidence>.55)return b.subject.substring(7);return"home_shelter";}
}