package com.aicharacter.v3;
/** Causal fictional biology for non-human VNF life. It gives body/senses to creatures and authored plants without copying Earth biology. */
public final class LivingWorldEngine{
 private LivingWorldEngine(){}
 public static void advance(WorldState s,double minutes,long now){
  if(s==null||s.world==null||minutes<=0)return;if(s.livingWorld==null)s.livingWorld=new LivingWorldState();for(WorldArea a:s.world.areas)advanceField(s,a,minutes,now);advanceReedling(s,minutes,now);
  for(WorldObject o:s.world.objects){if(isLivingFlora(o))advanceFlora(s,o,minutes,now);else if(isGenericCreature(o,s))advanceCreature(s,o,minutes,now);}
 }
 public static boolean isLivingFlora(WorldObject o){return o!=null&&o.enabled&&("herb".equals(o.type)||o.tags!=null&&(o.tags.contains("vegetation")||o.tags.contains("moss")||o.tags.contains("tree")))&&!"creature".equals(o.type);}
 private static void advanceField(WorldState s,WorldArea a,double minutes,long now){BiomeLifeFieldState f=s.livingWorld.field(a.id);BiomeProfile b=s.world.biome(a.biomeId);double moisture=EcologyEngine.localMoisture(s,a),temp=EcologyEngine.localTemperatureC(s,a),lumen=(s.environment==null?.5:s.environment.ambientBrightness)*(a.weatherExposed?1:.70),wind=s.environment==null?0:s.environment.wind,rain=s.environment!=null&&"RAIN".equals(s.environment.weather)?s.environment.weatherIntensity:0;double motion=0;if(s.girlTravel!=null&&s.girlTravel.active&&a==s.world.areaAt(s.haruX))motion+=.45;if(s.catTravel!=null&&s.catTravel.active&&s.catState!=null&&a==s.world.areaAt(s.catState.x))motion+=.30;f.sense.lumenSense=follow(f.sense.lumenSense,cl(lumen),minutes,14);f.sense.moistureSense=follow(f.sense.moistureSense,moisture,minutes,18);f.sense.thermalSense=follow(f.sense.thermalSense,cl((temp+10)/55.0),minutes,24);f.sense.vibrationSense=follow(f.sense.vibrationSense,cl(motion),minutes,2);f.sense.proximitySense=follow(f.sense.proximitySense,cl(motion*.75),minutes,3);f.sense.alertness=follow(f.sense.alertness,cl(wind*.18+rain*.20+motion*.58),minutes,4);double comfort=1-Math.abs(f.sense.thermalSense-.58),feed=cl(f.sense.lumenSense*.44+f.sense.moistureSense*.42+comfort*.14);f.body.vitalReserve=follow(f.body.vitalReserve,feed,minutes,160);f.body.fluidBalance=follow(f.body.fluidBalance,cl(.18+f.sense.moistureSense*.72),minutes,90);f.body.strain=follow(f.body.strain,cl((1-feed)*.58+f.sense.alertness*.10),minutes,45);f.body.rhythm=follow(f.body.rhythm,cl(.20+f.body.vitalReserve*.45+f.sense.lumenSense*.18),minutes,30);f.body.surfaceIntegrity=follow(f.body.surfaceIntegrity,cl(.70+f.body.vitalReserve*.28-f.body.strain*.18),minutes,240);f.motionDrive=follow(f.motionDrive,cl(wind*.70+rain*.22+f.sense.vibrationSense*.30),minutes,2);f.densityVitality=follow(f.densityVitality,cl((b==null?.55:.65)+f.body.vitalReserve*.28-f.body.strain*.18),minutes,360);f.lastUpdatedAt=now;f.body.lastUpdatedAt=now;f.sense.lastUpdatedAt=now;}
 private static void advanceReedling(WorldState s,double minutes,long now){
  CreatureState c=s.reedling;if(c==null)return;if(c.body==null)c.body=new OrganismBodyState();if(c.sense==null)c.sense=new OrganismSenseState();WorldArea a=s.world.area(c.areaId);WorldObject o=s.world.object(c.objectId);if(a==null||o==null)return;
  double suitability=EcologyEngine.creatureSuitability(s,a,o),moisture=EcologyEngine.localMoisture(s,a),temp=EcologyEngine.localTemperatureC(s,a),lumen=s.environment==null?.5:s.environment.ambientBrightness;
  double haru=proximity(s.haruX,c.x,a,s.world.areaAt(s.haruX)),cat=s.catState==null?0:proximity(s.catState.x,c.x,a,s.world.areaAt(s.catState.x)),motion=(s.girlTravel!=null&&s.girlTravel.active?haru:0)+(s.catTravel!=null&&s.catTravel.active?cat:0);
  c.sense.lumenSense=follow(c.sense.lumenSense,lumen,minutes,5);c.sense.moistureSense=follow(c.sense.moistureSense,moisture,minutes,4);c.sense.thermalSense=follow(c.sense.thermalSense,cl((temp+10)/55.0),minutes,6);c.sense.proximitySense=follow(c.sense.proximitySense,Math.max(haru,cat),minutes,1.5);c.sense.vibrationSense=follow(c.sense.vibrationSense,cl(motion),minutes,.8);c.sense.alertness=follow(c.sense.alertness,cl(c.fear*.45+c.sense.proximitySense*.38+c.sense.vibrationSense*.35),minutes,2);
  double active="wander".equals(c.activity)||"forage".equals(c.activity)?1:0;c.body.vitalReserve=cl(c.energy*.72+(1-c.hunger)*.28);c.body.fluidBalance=follow(c.body.fluidBalance,cl(.35+moisture*.55),minutes,35);c.body.strain=follow(c.body.strain,cl((1-suitability)*.55+active*.15+c.sense.alertness*.18),minutes,8);c.body.rhythm=follow(c.body.rhythm,cl(.28+active*.35+c.sense.alertness*.22),minutes,3);c.body.surfaceIntegrity=follow(c.body.surfaceIntegrity,cl(.72+suitability*.25-c.body.strain*.12),minutes,90);c.body.structure=follow(c.body.structure,cl(.78+suitability*.20-c.body.strain*.10),minutes,180);c.body.lastUpdatedAt=now;c.sense.lastUpdatedAt=now;
 }
 public static boolean isGenericCreature(WorldObject o,WorldState s){return o!=null&&o.enabled&&"creature".equals(o.type)&&(s==null||s.reedling==null||!o.id.equals(s.reedling.objectId));}
 private static void advanceCreature(WorldState s,WorldObject o,double minutes,long now){
  CreatureLifeState c=s.livingWorld.creature(o.id);if(c.areaId==null||c.areaId.isEmpty()){c.areaId=o.areaId;c.x=o.x;}WorldArea a=s.world.area(c.areaId);if(a==null){a=s.world.area(o.areaId);c.areaId=o.areaId;c.x=o.x;}if(a==null)return;
  double suitability=EcologyEngine.creatureSuitability(s,a,o),moisture=EcologyEngine.localMoisture(s,a),temp=EcologyEngine.localTemperatureC(s,a),lumen=s.environment==null?.5:s.environment.ambientBrightness;
  double haru=proximity(s.haruX,c.x,a,s.world.areaAt(s.haruX)),cat=s.catState==null?0:proximity(s.catState.x,c.x,a,s.world.areaAt(s.catState.x)),motion=(s.girlTravel!=null&&s.girlTravel.active?haru:0)+(s.catTravel!=null&&s.catTravel.active?cat:0);
  c.sense.lumenSense=follow(c.sense.lumenSense,lumen,minutes,5);c.sense.moistureSense=follow(c.sense.moistureSense,moisture,minutes,5);c.sense.thermalSense=follow(c.sense.thermalSense,cl((temp+10)/55.0),minutes,7);c.sense.proximitySense=follow(c.sense.proximitySense,Math.max(haru,cat),minutes,1.4);c.sense.vibrationSense=follow(c.sense.vibrationSense,cl(motion),minutes,.9);c.sense.alertness=follow(c.sense.alertness,cl(c.sense.proximitySense*.42+c.sense.vibrationSense*.38+(1-suitability)*.20),minutes,2);
  c.hunger=cl(c.hunger+minutes*(.0008+.0008*(1-suitability)));c.avoidance=follow(c.avoidance,cl(c.sense.alertness*.72+(1-suitability)*.30),minutes,3);c.curiosity=follow(c.curiosity,cl(.18+(1-c.sense.alertness)*.36+c.sense.proximitySense*.10),minutes,8);
  c.body.fluidBalance=follow(c.body.fluidBalance,cl(.28+moisture*.62),minutes,40);c.body.vitalReserve=follow(c.body.vitalReserve,cl((1-c.hunger)*.48+suitability*.32+c.body.fluidBalance*.20),minutes,45);c.body.strain=follow(c.body.strain,cl((1-suitability)*.50+c.sense.alertness*.22+c.avoidance*.16),minutes,8);c.body.rhythm=follow(c.body.rhythm,cl(.22+c.body.vitalReserve*.35+c.sense.alertness*.24),minutes,4);c.body.structure=follow(c.body.structure,cl(.76+suitability*.20-c.body.strain*.12),minutes,180);c.body.surfaceIntegrity=follow(c.body.surfaceIntegrity,cl(.70+suitability*.24-c.body.strain*.12),minutes,120);
  if(c.body.strain>.75||c.body.vitalReserve<.24){c.activity="rest";c.locomotionDrive=follow(c.locomotionDrive,.05,minutes,2);}
  else if(c.avoidance>.62){c.activity="withdraw";c.locomotionDrive=follow(c.locomotionDrive,.75,minutes,1.5);}
  else if(c.hunger>.60){c.activity="forage";c.locomotionDrive=follow(c.locomotionDrive,.52,minutes,2);}
  else{c.activity="drift";c.locomotionDrive=follow(c.locomotionDrive,.28+c.curiosity*.22,minutes,3);}
  float span=Math.max(24,a.right-a.left-70);double phase=((now/1000.0)/(14.0-8.0*c.locomotionDrive))+(o.id.hashCode()&63)*.11;float center=(a.left+a.right)*.5f,amp=span*.44f*(float)(.35+.55*c.locomotionDrive);c.x=Math.max(a.left+30,Math.min(a.right-30,center+(float)Math.sin(phase)*amp));c.lastUpdatedAt=now;c.body.lastUpdatedAt=now;c.sense.lastUpdatedAt=now;
 }
 private static void advanceFlora(WorldState s,WorldObject o,double minutes,long now){
  FloraLifeState f=s.livingWorld.flora(o.id);WorldArea a=s.world.area(o.areaId);if(a==null)return;double moisture=EcologyEngine.localMoisture(s,a),temp=EcologyEngine.localTemperatureC(s,a),lumen=(s.environment==null?.5:s.environment.ambientBrightness)*(a.weatherExposed?1:.72),wind=s.environment==null?0:s.environment.wind;
  double haru=proximity(s.haruX,o.x,a,s.world.areaAt(s.haruX)),cat=s.catState==null?0:proximity(s.catState.x,o.x,a,s.world.areaAt(s.catState.x)),motion=(s.girlTravel!=null&&s.girlTravel.active?haru:0)+(s.catTravel!=null&&s.catTravel.active?cat:0);
  f.sense.lumenSense=follow(f.sense.lumenSense,cl(lumen),minutes,10);f.sense.moistureSense=follow(f.sense.moistureSense,moisture,minutes,14);f.sense.thermalSense=follow(f.sense.thermalSense,cl((temp+10)/55.0),minutes,18);f.sense.proximitySense=follow(f.sense.proximitySense,Math.max(haru,cat),minutes,2);f.sense.vibrationSense=follow(f.sense.vibrationSense,cl(motion),minutes,1);f.sense.alertness=follow(f.sense.alertness,cl(f.sense.vibrationSense*.62+f.sense.proximitySense*.25+wind*.16),minutes,2);
  double lumenFeed=cl(.18+f.sense.lumenSense*.58),fluidFeed=cl(.15+f.sense.moistureSense*.70),comfort=1-Math.abs(f.sense.thermalSense-.58);f.body.fluidBalance=follow(f.body.fluidBalance,fluidFeed,minutes,50);f.body.vitalReserve=follow(f.body.vitalReserve,cl(lumenFeed*.48+fluidFeed*.38+comfort*.14),minutes,80);f.body.strain=follow(f.body.strain,cl((1-fluidFeed)*.46+(1-comfort)*.30+f.sense.alertness*.12),minutes,25);f.body.rhythm=follow(f.body.rhythm,cl(.18+f.body.vitalReserve*.52+f.sense.lumenSense*.18),minutes,20);f.body.surfaceIntegrity=follow(f.body.surfaceIntegrity,cl(.72+f.body.vitalReserve*.28-f.body.strain*.20),minutes,180);f.rootGrip=follow(f.rootGrip,cl(.62+f.body.fluidBalance*.30-f.body.strain*.10),minutes,240);f.opening=follow(f.opening,cl(f.sense.lumenSense*.72+(1-f.sense.alertness)*.20),minutes,12);f.swayDrive=follow(f.swayDrive,cl(wind*.72+f.sense.vibrationSense*.35),minutes,1.5);f.growthPulse=follow(f.growthPulse,cl(f.body.vitalReserve*.62+f.body.fluidBalance*.28-f.body.strain*.20),minutes,120);f.lastStimulus=f.sense.vibrationSense>.42?"ground-vibration":wind>.45?"air-current":f.sense.moistureSense>.72?"moisture-rise":"ambient";f.lastUpdatedAt=now;f.body.lastUpdatedAt=now;f.sense.lastUpdatedAt=now;
 }
 public static String diagnostic(WorldState s){if(s==null)return"LIVING WORLD <no state>";StringBuilder b=new StringBuilder("LIVING WORLD TRACE\n");if(s.reedling!=null&&s.reedling.body!=null&&s.reedling.sense!=null){b.append("reedling body[vital=").append(fmt(s.reedling.body.vitalReserve)).append(" fluid=").append(fmt(s.reedling.body.fluidBalance)).append(" structure=").append(fmt(s.reedling.body.structure)).append(" strain=").append(fmt(s.reedling.body.strain)).append(" rhythm=").append(fmt(s.reedling.body.rhythm)).append("] senses[lumen=").append(fmt(s.reedling.sense.lumenSense)).append(" moisture=").append(fmt(s.reedling.sense.moistureSense)).append(" vibration=").append(fmt(s.reedling.sense.vibrationSense)).append(" proximity=").append(fmt(s.reedling.sense.proximitySense)).append(" alert=").append(fmt(s.reedling.sense.alertness)).append("]\n");}if(s.world!=null){for(WorldArea a:s.world.areas){BiomeLifeFieldState f=field(s,a.id);b.append("field:").append(a.id).append(" body[vital=").append(fmt(f.body.vitalReserve)).append(" strain=").append(fmt(f.body.strain)).append("] senses[lumen=").append(fmt(f.sense.lumenSense)).append(" moisture=").append(fmt(f.sense.moistureSense)).append(" vibration=").append(fmt(f.sense.vibrationSense)).append("] motion=").append(fmt(f.motionDrive)).append(" density=").append(fmt(f.densityVitality)).append('\n');}for(WorldObject o:s.world.objects)if(isLivingFlora(o)){FloraLifeState f=flora(s,o.id);b.append(o.id).append(" body[vital=").append(fmt(f.body.vitalReserve)).append(" fluid=").append(fmt(f.body.fluidBalance)).append(" strain=").append(fmt(f.body.strain)).append("] senses[lumen=").append(fmt(f.sense.lumenSense)).append(" moisture=").append(fmt(f.sense.moistureSense)).append(" vibration=").append(fmt(f.sense.vibrationSense)).append("] opening=").append(fmt(f.opening)).append(" sway=").append(fmt(f.swayDrive)).append(" stimulus=").append(f.lastStimulus).append('\n');}}return b.toString();}
 private static String fmt(double v){return String.format(java.util.Locale.US,"%.2f",v);}
 public static FloraLifeState flora(WorldState s,String objectId){if(s==null)return null;if(s.livingWorld==null)s.livingWorld=new LivingWorldState();return s.livingWorld.flora(objectId);}public static CreatureLifeState creature(WorldState s,String objectId){if(s==null)return null;if(s.livingWorld==null)s.livingWorld=new LivingWorldState();return s.livingWorld.creature(objectId);}public static BiomeLifeFieldState field(WorldState s,String areaId){if(s==null)return null;if(s.livingWorld==null)s.livingWorld=new LivingWorldState();return s.livingWorld.field(areaId);}
 private static double proximity(float x,float y,WorldArea target,WorldArea actor){if(target==null||actor==null||!target.id.equals(actor.id))return 0;return cl(1-Math.abs(x-y)/260.0);}
 private static double follow(double v,double target,double minutes,double tauMin){double k=1-Math.exp(-minutes/Math.max(.05,tauMin));return cl(v+(target-v)*k);}
 private static double cl(double v){return Math.max(0,Math.min(1,v));}
}