package com.aicharacter.v3;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.content.pm.PackageManager;import android.net.Uri;import android.os.Bundle;import android.provider.Settings;import android.util.Log;import android.view.WindowInsets;import android.view.WindowInsetsController;import android.widget.EditText;import android.widget.Toast;import android.widget.TextView;import android.widget.ScrollView;import android.widget.FrameLayout;import android.graphics.Color;import java.io.File;

public final class MainActivity extends Activity implements GameView.Host,GodSessionManager.Listener{
 private static final String TAG="VNF";private WorldRepository repository;private WorldState state;private GameView gameView;private FrameLayout gameRoot;private VoiceController voice;private String deferredProactiveSpeech="";private ProceduralAudioEngine audio;private AppUpdateManager.Update pendingUpdate;private File pendingUpdateApk;private GodContactScene godScene;private boolean updateCheckInFlight=false,updateDownloadInFlight=false,updateDialogVisible=false,backgrounded=false,updateExternalFlow=false,permissionRequestIntroVisible=false,worldCatchupInFlight=false,startupAfterFirstFrameStarted=false;private int worldRefreshRetryCount=0,debugCameraProbeChecks=0,debugGodProbeChecks=0;private long lastUpdateCheckAt=0L,startupStartedAt=0L;private static final long UPDATE_RESUME_GUARD_MS=15000L;
 @Override protected void onCreate(Bundle b){
  super.onCreate(b);WorldRuntimePresence.setForeground(true);startupStartedAt=android.os.SystemClock.elapsedRealtime();showStartupScreen();try{hideSystemUi();}catch(Throwable ignored){}
  final android.content.Context app=getApplicationContext();
  new Thread(()->{
   try{
    Log.i(TAG,"STARTUP_BOOTSTRAP_BEGIN");
    WorldRepository r=new WorldRepository(app);
    Log.i(TAG,"STARTUP_REPOSITORY_READY");
    WorldState preview=r.loadPreviewOrCreate();
    Log.i(TAG,"STARTUP_PREVIEW_READY simulatedAt="+preview.lastSimulatedAt+" haruX="+preview.haruX);
    applyDebugVisualCapture(preview);
    Log.i(TAG,"STARTUP_PREVIEW_DEBUG_APPLIED");
    runOnUiThread(()->showWorldPreview(r,preview));
   }catch(Throwable e){Log.e(TAG,"STARTUP_BOOTSTRAP_FAILED",e);runOnUiThread(()->showStartupFailure(e));}
  },"VNF-World-Bootstrap").start();
 }
 private void showWorldPreview(WorldRepository r,WorldState preview){
  try{
   repository=r;state=preview;worldCatchupInFlight=false;
   gameView=new GameView(this,state,this,true);
   if(BuildConfig.DEBUG){gameView.setDebugBiome(getIntent().getStringExtra("vnf_debug_biome"));gameView.setDebugHaruPose(getIntent().getStringExtra("vnf_debug_pose"));gameView.setDebugCatPose(getIntent().getStringExtra("vnf_debug_cat_pose"));scheduleDebugVisualCapture();}
   gameRoot=new FrameLayout(this);gameRoot.addView(gameView,new FrameLayout.LayoutParams(-1,-1));setContentView(gameRoot);
   long attachedMs=Math.max(0,android.os.SystemClock.elapsedRealtime()-startupStartedAt);
   Log.i(TAG,"STARTUP_WORLD_ATTACHED ms="+attachedMs+" awaitingFirstFrame=true");
  }catch(Throwable e){showStartupFailure(e);}
 }
 @Override public void onFirstWorldFrame(){
  if(startupAfterFirstFrameStarted||repository==null||gameView==null)return;
  startupAfterFirstFrameStarted=true;
  long visibleMs=Math.max(0,android.os.SystemClock.elapsedRealtime()-startupStartedAt);
  Log.i(TAG,"STARTUP_FIRST_WORLD_FRAME ms="+visibleMs+" persistentWorldReady=true");
  try{GodSessionManager.addListener(this);}catch(Throwable e){Log.w(TAG,"God listener deferred startup failed",e);}
  if(!isDebugVisualCapture())gameView.postDelayed(()->refreshPersistentWorldAfterResume(System.currentTimeMillis()),80L);
  if(!isDebugVisualCapture()){
   gameView.postDelayed(this::initializeDeferredAudio,120L);
   gameView.postDelayed(this::initializeDeferredVoice,220L);
   gameView.postDelayed(()->maybeCheckAppUpdate(true),320L);
   gameView.postDelayed(this::maybeHaruRequestCoreRuntimePermissions,1200L);
  }else gameView.postDelayed(this::initializeDeferredVoice,220L);
  if(BuildConfig.DEBUG){scheduleDebugNaturalProbe();scheduleDebugCatSocialProbe();scheduleDebugReopenProbe();scheduleDebugPresentationProbe();}
 }
 private void initializeDeferredVoice(){
  if(voice!=null||isFinishing()||isDestroyed())return;
  try{voice=new VoiceController(this,new VoiceController.Listener(){public void onRecognized(String t){respondToVoice(t);}public void onStatus(String t){Toast.makeText(MainActivity.this,t,Toast.LENGTH_SHORT).show();}});if(!deferredProactiveSpeech.isEmpty()){String pending=deferredProactiveSpeech;deferredProactiveSpeech="";voice.speakProactive(pending);}}
  catch(Throwable e){Log.w(TAG,"Voice init deferred startup failed",e);voice=null;}
 }
 private void initializeDeferredAudio(){
  if(audio!=null||isFinishing()||isDestroyed())return;
  try{audio=new ProceduralAudioEngine();audio.resume();}catch(Throwable e){Log.w(TAG,"Audio init deferred startup failed",e);audio=null;}
 }
 private void refreshPersistentWorldAfterResume(long resumedAt){
  if(isDebugCameraProbe()||isDebugGodProbe())return;
  if(repository==null||state==null||worldCatchupInFlight)return;
  worldCatchupInFlight=true;
  final WorldRepository r=repository;
  final long expectedSavedAt=state.lastSavedAt,expectedSimulatedAt=state.lastSimulatedAt;
  new Thread(()->{
   try{
    r.commitPendingInitialSeed();
    WorldState live=r.loadOrCreate();
    long now=Math.max(resumedAt,System.currentTimeMillis());
    WorldContinuityEngine.advanceForPlayerOpen(live,now);
    r.save(live);
    runOnUiThread(()->{
     worldCatchupInFlight=false;
     if(isFinishing()||isDestroyed()||state==null)return;
     boolean untouched=state.lastSavedAt<=expectedSavedAt&&state.lastSimulatedAt<=expectedSimulatedAt;
     if(untouched){worldRefreshRetryCount=0;state=live;if(gameView!=null)gameView.replaceState(live,true);Log.i(TAG,"RESUME_WORLD_REFRESH ready=true");}
     else{Log.i(TAG,"RESUME_WORLD_REFRESH conflict=true retry="+worldRefreshRetryCount);if(worldRefreshRetryCount<3&&gameView!=null){worldRefreshRetryCount++;gameView.postDelayed(()->refreshPersistentWorldAfterResume(System.currentTimeMillis()),120L);}else worldRefreshRetryCount=0;}
    });
   }catch(Throwable e){Log.e(TAG,"Persistent world refresh failed",e);runOnUiThread(()->{worldCatchupInFlight=false;worldRefreshRetryCount=0;});}
  },"VNF-World-Refresh").start();
 }
 private boolean worldReadyForInteraction(){return state!=null&&gameView!=null;}
 private boolean isDebugVisualCapture(){return BuildConfig.DEBUG&&(getIntent().hasExtra("vnf_debug_biome")||getIntent().hasExtra("vnf_debug_pose")||getIntent().hasExtra("vnf_debug_cat_pose"));}
 private boolean isDebugNaturalProbe(){return BuildConfig.DEBUG&&getIntent().getBooleanExtra("vnf_debug_natural_probe",false);}
 private boolean isDebugCatSocialProbe(){return BuildConfig.DEBUG&&getIntent().getBooleanExtra("vnf_debug_cat_social_probe",false);}
 private boolean isDebugReopenProbe(){return BuildConfig.DEBUG&&getIntent().getBooleanExtra("vnf_debug_reopen_probe",false);}
 private void scheduleDebugNaturalProbe(){if(!isDebugNaturalProbe()||gameView==null)return;gameView.postDelayed(()->logDebugNaturalProbe("start"),5000L);gameView.postDelayed(()->logDebugNaturalProbe("final"),185000L);}
 private void logDebugNaturalProbe(String sample){WorldState s=state;if(s==null)return;PlanState p=s.planState;TravelState gt=s.girlTravel;PhysicsBodyState gp=s.girlPhysics;String plan=p==null?"":p.planId,status=p==null?"":p.status;long progress=p==null?0:p.lastProgressAt;boolean travel=gt!=null&&gt.active,catTravel=s.catTravel!=null&&s.catTravel.active;String catMode=s.catSocial==null?"":s.catSocial.mode,catSleep=s.catState==null?"":s.catState.sleepMode;float cat=s.catState==null?s.catX:s.catState.x;HaruProactiveSpeechState hs=s.haruSpeech;int speechCount=hs==null?0:hs.spokenCount;long lastSpoken=hs==null?0:hs.lastSpokenAt;String anim=gameView==null?"state= frames=0 fps=0":gameView.debugHaruAnimationQa();double instinct=BodyInstinctEngine.movementCapacity(s),muscle=MusculoskeletalEngine.locomotorCapacity(s),nerve=NervousSystemEngine.locomotorConstraint(s);Log.i(TAG,"NATURAL_QA sample="+sample+" haruX="+s.haruX+" intention="+qaToken(s.currentIntention)+" activity="+qaToken(s.haruActivity)+" plan="+qaToken(plan)+" status="+qaToken(status)+" travel="+travel+" planProgress="+progress+" simulatedAt="+s.lastSimulatedAt+" createdAt="+s.createdAt+" openedAt="+s.lastOpenedAt+" savedAt="+s.lastSavedAt+" catX="+cat+" catMode="+qaToken(catMode)+" catSleep="+qaToken(catSleep)+" catTravel="+catTravel+" speechCount="+speechCount+" lastSpoken="+lastSpoken+" travelProgress="+(gt==null?0:gt.progress)+" segStart="+(gt==null?Float.NaN:gt.segmentStartX)+" segEnd="+(gt==null?Float.NaN:gt.segmentEndX)+" lastSpeed="+(gt==null?0:gt.lastSpeed)+" lastDelta="+(gt==null?0:gt.lastDelta)+" distance="+(gt==null?0:gt.distanceTravelled)+" grounded="+(gp!=null&&gp.grounded)+" velocityX="+(gp==null?0:gp.velocityX)+" balance="+(gp==null?0:gp.balance)+" traction="+(gp==null?0:gp.traction)+" slip="+(gp==null?0:gp.slipSeverity)+" instinct="+instinct+" muscle="+muscle+" nerve="+nerve+" energy="+(s.body==null?0:s.body.energy)+" sleepiness="+(s.body==null?0:s.body.sleepiness)+" "+anim);}
 private void scheduleDebugCatSocialProbe(){if(!isDebugCatSocialProbe()||gameView==null)return;gameView.postDelayed(()->{applyDebugCatSocialProbe();logDebugCatSocialProbe("start");},4000L);gameView.postDelayed(()->logDebugCatSocialProbe("final"),20000L);}
 private void applyDebugCatSocialProbe(){WorldState s=state;if(s==null||s.world==null||s.catState==null)return;WorldArea home=s.world.area("home_shelter");if(home==null)return;s.haruX=300f;s.catState.x=480f;s.catX=480f;s.catState.areaId=home.id;s.catState.awake=true;s.catState.attachedToEntity="";s.catState.carryKnownByGirl=false;s.catState.energy=90;s.catState.sleepiness=10;s.catState.lastPlayerActiveAt=0;if(s.catSocial==null)s.catSocial=new CatSocialState();s.catSocial.familiarity=.86;s.catSocial.comfort=.82;s.catSocial.wariness=.06;s.catSocial.curiosity=.62;s.catSocial.mode="WATCH";s.catSocial.reason="";s.catSocial.activeTravelId="";s.catSocial.frozenTargetX=Float.NaN;s.catSocial.lastPlayerOverrideAt=0;s.catTravel=new TravelState();if(s.catPhysics!=null){s.catPhysics.falling=false;s.catPhysics.grounded=true;s.catPhysics.velocityX=0;s.catPhysics.velocityY=0;}if(s.girlTravel!=null)s.girlTravel.active=false;StateInvariantChecker.normalizeSpatialState(s,Math.max(System.currentTimeMillis(),s.lastSimulatedAt));gameView.postInvalidate();}
 private void logDebugCatSocialProbe(String sample){WorldState s=state;if(s==null||s.catState==null)return;CatSocialState cs=s.catSocial;float cat=s.catState.x;String mode=cs==null?"":cs.mode,reason=cs==null?"":cs.reason;boolean travel=s.catTravel!=null&&s.catTravel.active;int approaches=cs==null?0:cs.approaches,retreats=cs==null?0:cs.retreats,settles=cs==null?0:cs.settles;Log.i(TAG,"CAT_QA sample="+sample+" catX="+cat+" haruX="+s.haruX+" mode="+qaToken(mode)+" travel="+travel+" approaches="+approaches+" retreats="+retreats+" settles="+settles+" reason="+qaToken(reason)+" simulatedAt="+s.lastSimulatedAt);}
 private void scheduleDebugReopenProbe(){if(!isDebugReopenProbe()||gameView==null)return;gameView.postDelayed(this::logDebugReopenProbe,5000L);}
 private void logDebugReopenProbe(){WorldState s=state;if(s==null)return;float cat=s.catState==null?s.catX:s.catState.x;String catMode=s.catSocial==null?"":s.catSocial.mode;Log.i(TAG,"REOPEN_QA createdAt="+s.createdAt+" openedAt="+s.lastOpenedAt+" savedAt="+s.lastSavedAt+" simulatedAt="+s.lastSimulatedAt+" haruX="+s.haruX+" catX="+cat+" intention="+qaToken(s.currentIntention)+" activity="+qaToken(s.haruActivity)+" catMode="+qaToken(catMode));}
 private boolean isDebugCameraProbe(){return BuildConfig.DEBUG&&getIntent().getBooleanExtra("vnf_debug_camera_probe",false);}
 private boolean isDebugGodProbe(){return BuildConfig.DEBUG&&getIntent().getBooleanExtra("vnf_debug_god_probe",false);}
 private void scheduleDebugPresentationProbe(){if(gameView==null)return;if(isDebugCameraProbe()){debugCameraProbeChecks=0;gameView.postDelayed(this::applyDebugCameraProbe,4000L);gameView.postDelayed(this::logDebugCameraProbe,4250L);}if(isDebugGodProbe()){debugGodProbeChecks=0;gameView.postDelayed(this::openDebugGodProbe,3500L);gameView.postDelayed(this::logDebugGodProbe,3750L);}}
 private void applyDebugCameraProbe(){WorldState s=state;if(s==null||s.world==null||s.catState==null)return;WorldArea home=s.world.area("home_shelter");if(home==null)return;gameView.debugFreezeSimulation();s.haruX=300f;s.catState.x=390f;s.catX=390f;s.catState.areaId=home.id;s.catState.awake=true;s.catState.attachedToEntity="";s.catState.carryKnownByGirl=false;if(s.girlTravel!=null)s.girlTravel.active=false;if(s.catTravel!=null)s.catTravel.active=false;s.emotion.joy=.94;s.emotion.fear=0;s.emotion.sadness=0;s.emotion.anger=0;s.emotion.loneliness=0;s.emotion.curiosity=.35;s.reunionContext="debug_cat_reunion";long now=Math.max(System.currentTimeMillis(),s.lastSimulatedAt);EmotionEpisodeState e=new EmotionEpisodeState();e.id="debug_camera_social";e.primaryEmotion="joy";e.intensity=.94;e.status="ACTIVE";e.createdAt=now;e.updatedAt=now;e.targetId="cat";e.socialRelevance=.96;e.joy=.96;s.emotionEpisodes.add(e);StateInvariantChecker.normalizeSpatialState(s,now);gameView.postInvalidate();}
 private void logDebugCameraProbe(){if(gameView==null)return;if(!gameView.debugCameraQaReady()&&debugCameraProbeChecks++<48){gameView.postDelayed(this::logDebugCameraProbe,250L);return;}Log.i(TAG,"CAMERA_QA "+gameView.debugCameraQa());}
 private void openDebugGodProbe(){if(godScene!=null||gameRoot==null||gameView==null)return;gameView.debugFreezeSimulation();gameView.setDivineVisualPresence(true);godScene=new GodContactScene(this,"",new GodContactScene.Host(){public void onClose(){closeGodScene();}public void onSend(String q){}});gameRoot.addView(godScene.view(),new FrameLayout.LayoutParams(-1,-1));godScene.setSessionState(GodSessionManager.getState());}
 private void logDebugGodProbe(){boolean scene=godScene!=null,world=gameView!=null,divine=world&&gameView.debugDivinePresenceActive(),clear=world&&gameView.debugPresentationClear();int children=gameRoot==null?0:gameRoot.getChildCount();if((!scene||!divine||!clear)&&debugGodProbeChecks++<48){if(gameView!=null)gameView.postDelayed(this::logDebugGodProbe,250L);return;}Log.i(TAG,"GOD_QA scene="+scene+" world="+world+" divine="+divine+" clear="+clear+" children="+children);}
 private static String qaToken(String raw){return raw==null?"":raw.replaceAll("[^a-zA-Z0-9_-]+","_");}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(!BuildConfig.DEBUG||state==null||gameView==null)return;applyDebugVisualCapture(state);gameView.setDebugBiome(intent.getStringExtra("vnf_debug_biome"));gameView.setDebugHaruPose(intent.getStringExtra("vnf_debug_pose"));gameView.setDebugCatPose(intent.getStringExtra("vnf_debug_cat_pose"));gameView.postInvalidate();scheduleDebugVisualCapture();Log.i(TAG,"VISUAL_CAPTURE_INTENT biome="+intent.getStringExtra("vnf_debug_biome")+" pose="+intent.getStringExtra("vnf_debug_pose")+" cat="+intent.getStringExtra("vnf_debug_cat_pose"));}
 private void scheduleDebugVisualCapture(){if(!isDebugVisualCapture()||gameView==null)return;String raw=getIntent().getStringExtra("vnf_debug_capture_name");if(raw==null||raw.trim().isEmpty())raw=(getIntent().getStringExtra("vnf_debug_biome")+"_"+getIntent().getStringExtra("vnf_debug_pose"));final String name=raw.replaceAll("[^a-zA-Z0-9._-]","_");gameView.postDelayed(()->{try{File root=getFilesDir();File out=new File(new File(root,"visual-capture"),name+".png");boolean ok=gameView.writeDebugCapture(out);Log.i(TAG,"VISUAL_CAPTURE_FILE name="+name+" ok="+ok+" path="+out.getAbsolutePath()+" bytes="+(out.isFile()?out.length():0));}catch(Throwable e){Log.e(TAG,"VISUAL_CAPTURE_FILE failed name="+name,e);}},700L);}
 private void applyDebugVisualCapture(WorldState s){if(!isDebugVisualCapture()||s==null||s.world==null)return;String key=getIntent().getStringExtra("vnf_debug_biome");if(key==null||key.trim().isEmpty())return;String q=key.trim().toLowerCase(java.util.Locale.ROOT),id="home".equals(q)?"home_shelter":"garden".equals(q)?"garden_path":"grove".equals(q)?"quiet_grove":"lakeside".equals(q)?"lakeside":"";if(id.isEmpty())return;WorldArea a=s.world.area(id);if(a==null)return;s.haruX=(a.left+a.right)*.5f;if(s.girlTravel!=null)s.girlTravel.active=false;s.currentIntention="observe_lake";s.haruActivity="standing quietly";if(s.girlPhysics!=null){s.girlPhysics.falling=false;s.girlPhysics.grounded=true;s.girlPhysics.groundClearanceM=0;s.girlPhysics.velocityX=0;s.girlPhysics.velocityY=0;}String catPose=getIntent().getStringExtra("vnf_debug_cat_pose");if(catPose!=null&&!catPose.trim().isEmpty()&&s.catState!=null){String cp=catPose.trim().toLowerCase(java.util.Locale.ROOT);s.catState.x=s.haruX+145f;s.catX=s.catState.x;s.catState.areaId=a.id;s.catState.awake=!"sleep".equals(cp);s.catState.attachedToEntity="attached".equals(cp)?"girl":"";if(s.catTravel!=null)s.catTravel.active=false;if(s.catPhysics!=null){s.catPhysics.falling=false;s.catPhysics.grounded=true;s.catPhysics.velocityX=0;s.catPhysics.velocityY=0;}}}
 private void showStartupScreen(){TextView t=new TextView(this);t.setText("VNF");t.setGravity(android.view.Gravity.CENTER);t.setTextColor(Color.rgb(241,229,201));t.setBackgroundColor(Color.rgb(18,31,33));t.setTextSize(22);setContentView(t);}
 @Override protected void onResume(){super.onResume();WorldRuntimePresence.setForeground(true);long resumedAt=System.currentTimeMillis();boolean returningFromUpdateFlow=updateExternalFlow;updateExternalFlow=false;if(pendingUpdateApk!=null&&android.os.Build.VERSION.SDK_INT>=26&&getPackageManager().canRequestPackageInstalls()){File apk=pendingUpdateApk;pendingUpdateApk=null;launchUpdateInstaller(apk);}else if(startupAfterFirstFrameStarted&&!returningFromUpdateFlow&&!isDebugVisualCapture())maybeCheckAppUpdate(false);if(backgrounded&&state!=null){backgrounded=false;refreshPersistentWorldAfterResume(resumedAt);}if(audio!=null)audio.resume();if(gameView!=null)gameView.postInvalidate();}
 @Override protected void onPause(){super.onPause();if(audio!=null)audio.pause();if(state!=null&&repository!=null){try{repository.save(state);}catch(Throwable e){Log.e(TAG,"Save on pause failed",e);}}}
 @Override protected void onStop(){super.onStop();WorldRuntimePresence.setForeground(false);if(updateExternalFlow){if(state!=null&&repository!=null){try{repository.save(state);}catch(Throwable e){Log.e(TAG,"Save before update flow failed",e);}}WorldHeartbeatScheduler.requestSoon(this);return;}if(state!=null&&repository!=null&&!backgrounded){long wall=System.currentTimeMillis(),n=Math.max(wall,Math.max(state.lastOpenedAt,state.lastSimulatedAt));backgrounded=true;state.catState.lastPlayerActiveAt=Math.max(state.catState.lastPlayerActiveAt,n);state.catState.x=state.catX;try{repository.save(state);}catch(Throwable e){Log.e(TAG,"Save on stop failed",e);}ProactiveScheduler.scheduleApproximate(this,state);WorldHeartbeatScheduler.requestSoon(this);}}
 @Override protected void onDestroy(){WorldRuntimePresence.setForeground(false);GodSessionManager.removeListener(this);if(voice!=null)voice.destroy();if(audio!=null)audio.destroy();super.onDestroy();}
 @Override public void onBackPressed(){if(godScene!=null){if(godScene.isSending()){Toast.makeText(this,"Không gian vẫn đang dao động…",Toast.LENGTH_SHORT).show();return;}godScene.dismiss(this::closeGodScene);return;}super.onBackPressed();}
 @Override public void onGodSessionState(GodSessionManager.State s){if(godScene!=null)godScene.setSessionState(s);}
 @Override public void onTalk(){if(!worldReadyForInteraction())return;final EditText i=new EditText(this);i.setHint("Nói với cô ấy…");i.setSingleLine(false);i.setMaxLines(3);new AlertDialog.Builder(this).setTitle("Nói trong thế giới").setView(i).setPositiveButton("Nói",(d,w)->{HaruMind.Response r=HaruMind.respond(state,i.getText().toString());repository.save(state);new AlertDialog.Builder(this).setTitle(DisplayNames.girl(state)).setMessage(visibleResponse(r)).setPositiveButton("Ừ",null).show();}).setNegativeButton("Thôi",null).show();}
 @Override public void onVoiceTap(boolean d){if(!worldReadyForInteraction())return;if(voice==null){Toast.makeText(this,"Giọng nói chưa sẵn sàng.",Toast.LENGTH_SHORT).show();return;}if(d)voice.toggle();else voice.listen();}@Override public void onAudioScene(AudioSceneFrame frame){if(audio!=null)audio.update(frame);}@Override public void onSoundEvent(SoundEvent event){if(audio!=null)audio.play(event);}@Override public void onHaruProactiveSpeech(HaruProactiveSpeechEngine.Cue cue){if(cue==null||cue.text==null||cue.text.isEmpty())return;Log.i(TAG,"HARU_SPEECH_QA source="+qaToken(cue.sourceId)+" createdAt="+cue.createdAt+" textLen="+cue.text.length());if(voice!=null)voice.speakProactive(cue.text);else deferredProactiveSpeech=cue.text;if(repository!=null&&state!=null){try{repository.save(state);}catch(Throwable e){Log.w(TAG,"Could not persist proactive Haru speech delivery",e);}}}private void respondToVoice(String t){HaruMind.Response r=HaruMind.respond(state,t);repository.save(state);Toast.makeText(this,visibleResponse(r),Toast.LENGTH_LONG).show();if(voice!=null)voice.speak(r.speech);}private String visibleResponse(HaruMind.Response r){if(r==null)return"…";String e=r.expression==null?"":r.expression.trim();return e.isEmpty()?r.speech:"〈"+e+"〉\n\n"+r.speech;}
 @Override public void onGod(){if(!worldReadyForInteraction())return;if(godScene!=null||gameRoot==null)return;if(gameView!=null)gameView.setDivineVisualPresence(true);godScene=new GodContactScene(this,godInboxSummary(),new GodContactScene.Host(){public void onClose(){closeGodScene();}public void onSend(String q){handleGodMessage(q);}});gameRoot.addView(godScene.view(),new FrameLayout.LayoutParams(-1,-1));godScene.setSessionState(GodSessionManager.getState());GodSessionManager.warmup(getApplicationContext());}
 private void closeGodScene(){if(godScene!=null&&gameRoot!=null)gameRoot.removeView(godScene.view());godScene=null;if(gameView!=null)gameView.setDivineVisualPresence(false);try{hideSystemUi();}catch(Throwable ignored){}}
 private void handleGodMessage(String raw){final GodContactScene target=godScene;if(target==null)return;if(looksLikeContentRollback(raw)){RuntimeContentUpdater.Result rr=RuntimeContentUpdater.rollback(getApplicationContext());if(gameView!=null)gameView.postInvalidate();target.showSystem(rr.ok?"Những thay đổi gần nhất đã lùi lại. Thế giới đã ổn định.":"Không có thay đổi nào có thể lùi lại lúc này.");return;}if(isLocalGodCapability(raw)){String out=GodContactController.handle(state,raw);rememberGod(raw,out);target.showSystem(out);return;}if(!VnfOnlineConfig.godConfigured()){target.showError("Không có lời đáp lúc này. Thế giới vẫn tiếp tục.");return;}GodOnlineClient.ask(getApplicationContext(),state,raw,(result,error)->runOnUiThread(()->{if(error!=null){if(godScene==target)target.showError("Không có lời đáp lúc này.");return;}if(result==null){if(godScene==target)target.showError("Chỉ còn một khoảng lặng.");return;}rememberGod(raw,result.reply);if(result.worldEventProposal!=null){long eventNow=Math.max(state.lastSimulatedAt,state.lastOpenedAt);GodWorldEventExecutor.Result er=GodWorldEventExecutor.apply(state,result.worldEventProposal,eventNow);if(er.ok){repository.save(state);if(gameView!=null)gameView.postInvalidate();}}if(godScene!=target)return;if(result.godRecipePayload!=null&&!result.godRecipePayload.isEmpty()){RuntimeContentUpdater.Result rr=SignedGodWorldRecipe.apply(getApplicationContext(),result.godRecipePayload,result.godRecipeSignature);if(gameView!=null)gameView.postInvalidate();target.showReply(result.reply);return;}if(result.autoApplyContentPatch&&!result.contentPatchManifestUrl.isEmpty()){target.showProgress(result.reply+"\n\nÁnh sáng quanh thế giới đang đổi khác…");RuntimeContentUpdater.applySignedManifestAsync(getApplicationContext(),result.contentPatchManifestUrl,pr->runOnUiThread(()->{if(gameView!=null)gameView.postInvalidate();if(godScene==target)target.showReply(pr.ok?"Mọi thứ đã lắng lại.":"Sự thay đổi đã dừng lại." );}));return;}target.showReply(result.reply);}));}
 private void rememberGod(String q,String a){if(state.godMemory==null)state.godMemory=new GodMemory();long n=Math.max(System.currentTimeMillis(),Math.max(state.lastOpenedAt,state.lastSimulatedAt));state.godMemory.remember(q,a,n);repository.save(state);}
 private boolean looksLikeContentRollback(String r){String q=r.toUpperCase(java.util.Locale.ROOT);return q.contains("ROLLBACK CONTENT")||q.contains("HOÀN TÁC ĐỒ HỌA")||q.contains("HOAN TAC DO HOA")||q.contains("KHÔI PHỤC WORLD CONTENT")||q.contains("KHOI PHUC WORLD CONTENT");}
 private boolean isLocalGodCapability(String r){String q=r.toUpperCase(java.util.Locale.ROOT);if(!DivineNamingEngine.extractProposal(r).isEmpty())return true;if(GodTeachingGateway.looksLikeTeaching(r))return true;return q.contains("TRẠNG THÁI")||q.contains("TRANG THAI")||q.contains("BẢO VỆ")||q.contains("BAO VE")||q.contains("ĐÁNH GIÁ")||q.contains("DANH GIA")||q.contains("CHẨN ĐOÁN")||q.contains("CHAN DOAN")||q.contains("TÊN")||q.contains("TEN");}
 @Override public void onConsole(){if(!worldReadyForInteraction())return;final EditText i=new EditText(this);i.setHint("TRẠNG THÁI / CHẨN ĐOÁN / ...");i.setSingleLine(true);new AlertDialog.Builder(this).setTitle("SYSTEM · Thần").setMessage("Chỉ những thay đổi an toàn của thế giới mới có thể được thực hiện tại đây.\n\nTest hình ảnh: DEV GOD VEIL / DEV GOD VEIL SEVERE").setView(i).setPositiveButton("Chạy",(d,w)->{String raw=i.getText().toString();if(runGodVeilTest(raw)||runHaruVisionTest(raw))return;String out=SystemConsole.execute(state,raw);repository.save(state);new AlertDialog.Builder(this).setTitle("SYSTEM").setMessage(out).setPositiveButton("Đóng",null).show();}).setNegativeButton("Đóng",null).show();}
 private boolean runGodVeilTest(String raw){String q=raw==null?"":raw.trim().toUpperCase(java.util.Locale.ROOT);boolean severe=q.equals("DEV GOD VEIL SEVERE")||q.equals("TEST BAI XICH")||q.equals("TEST BÀI XÍCH");boolean normal=q.equals("DEV GOD VEIL")||q.equals("TEST MAN THAN")||q.equals("TEST MÀN THẦN");if(!severe&&!normal)return false;if(gameView!=null)gameView.showGodVeilTest(severe);Toast.makeText(this,severe?"Đang thử màn chắn cấp cao.":"Đang thử màn ổn định thế giới.",Toast.LENGTH_SHORT).show();return true;}
 private boolean runHaruVisionTest(String raw){String q=raw==null?"":raw.trim().toUpperCase(java.util.Locale.ROOT);if(!q.equals("DEV HARU VISION")&&!q.equals("HARU VISION TEST"))return false;if(gameView!=null)gameView.showHaruVisionTest();Toast.makeText(this,"Đang hiển thị nhận thức hiện tại của Haru.",Toast.LENGTH_SHORT).show();return true;}
 private String godInboxSummary(){StringBuilder b=new StringBuilder("TIN TỪ THẦN\n\n");int start=Math.max(0,state.godInbox.size()-5);for(int i=start;i<state.godInbox.size();i++){GodMessage m=state.godInbox.get(i);b.append(m.read?"· ":"• ").append(m.text).append('\n');m.read=true;}if(state.godInbox.isEmpty())b.append("(chưa có lời nhắn)");repository.save(state);return b.toString();}
 private void maybeCheckAppUpdate(boolean force){long now=System.currentTimeMillis();if(!VnfOnlineConfig.appUpdaterConfigured()||updateCheckInFlight||updateDownloadInFlight||updateDialogVisible)return;if(!force&&now-lastUpdateCheckAt<UPDATE_RESUME_GUARD_MS)return;lastUpdateCheckAt=now;pendingUpdate=null;updateCheckInFlight=true;AppUpdateManager.checkAsync(getApplicationContext(),(u,e)->runOnUiThread(()->{updateCheckInFlight=false;if(e!=null){Log.w(TAG,"Update check failed",e);pendingUpdate=null;return;}if(u==null){pendingUpdate=null;return;}int installed=installedVersionCode();if(u.versionCode<=installed){pendingUpdate=null;return;}pendingUpdate=u;Log.i(TAG,"UPDATE_AVAILABLE versionCode="+u.versionCode+" autoDownload=true");downloadPendingUpdate();}));}
 private int installedVersionCode(){try{android.content.pm.PackageInfo p=getPackageManager().getPackageInfo(getPackageName(),0);return android.os.Build.VERSION.SDK_INT>=28?(int)p.getLongVersionCode():p.versionCode;}catch(Throwable ignored){return BuildConfig.VERSION_CODE;}}
 private void downloadPendingUpdate(){final AppUpdateManager.Update u=pendingUpdate;pendingUpdate=null;if(u==null||u.versionCode<=installedVersionCode()||updateDownloadInFlight)return;updateDownloadInFlight=true;Toast.makeText(this,"VNF đang tự tải và kiểm tra bản cập nhật…",Toast.LENGTH_SHORT).show();new Thread(()->{try{File apk=AppUpdateManager.downloadAndVerify(getApplicationContext(),u);runOnUiThread(()->{updateDownloadInFlight=false;Log.i(TAG,"UPDATE_READY versionCode="+u.versionCode+" verified=true");requestInstallOrLaunch(apk);});}catch(Throwable e){runOnUiThread(()->{updateDownloadInFlight=false;showUpdateError(e);});}},"VNF-App-Update-Download").start();}
 private void requestInstallOrLaunch(File apk){if(android.os.Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){pendingUpdateApk=apk;new AlertDialog.Builder(this).setTitle("CHO PHÉP CẬP NHẬT VNF").setMessage("Android cần bạn cho phép VNF cài bản cập nhật từ nguồn này. Sau khi bật quyền, quay lại VNF; màn hình xác nhận cài đặt sẽ tự mở.\n\nVNF không thể bỏ qua bước xác nhận của Android.").setPositiveButton("Mở cài đặt",(d,w)->{updateExternalFlow=true;try{startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())));}catch(Throwable e){updateExternalFlow=false;showUpdateError(e);}}).setNegativeButton("Hủy",(d,w)->pendingUpdateApk=null).show();return;}launchUpdateInstaller(apk);}
 private void launchUpdateInstaller(File apk){updateExternalFlow=true;try{AppUpdateManager.launchInstaller(this,apk);}catch(Throwable e){updateExternalFlow=false;showUpdateError(e);}}
 private void showUpdateError(Throwable e){pendingUpdate=null;Log.e(TAG,"Update stopped",e);new AlertDialog.Builder(this).setTitle("CẬP NHẬT BỊ DỪNG").setMessage("Bản cập nhật chưa thể hoàn tất. VNF hiện tại, thế giới và ký ức vẫn được giữ nguyên.\n\nBạn có thể thử lại khi mở VNF lần sau.").setPositiveButton("Đóng",null).show();}
 private void showStartupFailure(Throwable e){Log.e(TAG,"World startup failed",e);TextView t=new TextView(this);t.setText("VNF đã mở ở chế độ an toàn.\n\nThế giới chưa được chạy để tránh làm hỏng ký ức hiện tại.\nDữ liệu không bị tự động xóa.\n\nHãy đóng rồi mở lại VNF. Nếu tình trạng vẫn lặp lại, giữ nguyên dữ liệu và kiểm tra bản cập nhật tiếp theo.");t.setTextColor(Color.rgb(241,229,201));t.setBackgroundColor(Color.rgb(18,31,33));t.setTextSize(18);int pad=(int)(24*getResources().getDisplayMetrics().density);t.setPadding(pad,pad,pad,pad);ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(18,31,33));s.addView(t);setContentView(s);}private void maybeHaruRequestCoreRuntimePermissions(){if(permissionRequestIntroVisible||isFinishing()||isDestroyed())return;boolean mic=checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED;boolean notifications=android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED;if(!mic&&!notifications)return;permissionRequestIntroVisible=true;String message;if(mic&&notifications)message="Mình muốn nghe được khi bạn nói với mình. Và nếu có chuyện đáng để gọi bạn khi bạn không ở đây, mình cũng muốn tự báo cho bạn.\n\nBạn cho mình hai quyền đó nhé?";else if(mic)message="Mình muốn nghe được khi bạn nói với mình, thay vì bắt bạn phải gõ mọi lúc.\n\nBạn cho mình quyền dùng micro nhé?";else message="Nếu có chuyện thật sự đáng để gọi bạn khi bạn không ở đây, mình muốn có thể tự báo cho bạn.\n\nBạn cho mình quyền gửi thông báo nhé?";new AlertDialog.Builder(this).setTitle("Haru chủ động hỏi").setMessage(message).setPositiveButton("Cho phép",(d,w)->{permissionRequestIntroVisible=false;requestCoreRuntimePermissions();}).setNegativeButton("Chưa",(d,w)->permissionRequestIntroVisible=false).setOnCancelListener(d->permissionRequestIntroVisible=false).show();}private void requestCoreRuntimePermissions(){java.util.ArrayList<String> missing=new java.util.ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)missing.add(Manifest.permission.RECORD_AUDIO);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)missing.add(Manifest.permission.POST_NOTIFICATIONS);if(!missing.isEmpty())requestPermissions(missing.toArray(new String[0]),403);}private void hideSystemUi(){if(android.os.Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController c=getWindow().getInsetsController();if(c!=null)c.hide(WindowInsets.Type.systemBars());}else getWindow().getDecorView().setSystemUiVisibility(5894);}
}
