package com.aicharacter.v3;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.content.pm.PackageManager;import android.net.Uri;import android.os.Bundle;import android.provider.Settings;import android.view.WindowInsets;import android.view.WindowInsetsController;import android.widget.EditText;import android.widget.Toast;import android.widget.TextView;import android.widget.ScrollView;import android.widget.FrameLayout;import android.graphics.Color;import java.io.File;

public final class MainActivity extends Activity implements GameView.Host,GodSessionManager.Listener{
 private WorldRepository repository;private WorldState state;private GameView gameView;private FrameLayout gameRoot;private VoiceController voice;private AppUpdateManager.Update pendingUpdate;private File pendingUpdateApk;private GodContactScene godScene;private boolean updateCheckInFlight=false,updateDialogVisible=false;private long lastUpdateCheckAt=0L;private static final long UPDATE_RESUME_GUARD_MS=15000L;
 @Override protected void onCreate(Bundle b){super.onCreate(b);showStartupScreen();try{hideSystemUi();}catch(Throwable ignored){}maybeCheckAppUpdate(true);final android.content.Context app=getApplicationContext();new Thread(()->{try{WorldRepository r=new WorldRepository(app);WorldState s=r.loadOrCreate();long now=System.currentTimeMillis();LifeCycleEngine.apply(s,now);AgeDevelopmentEngine.apply(s,now);StateInvariantChecker.repairOrReport(s,now);if(!s.catState.awake)CatOfflineEngine.followAttachment(s);String reconstructed=OfflineLifeEngine.reconstruct(s,now);StateInvariantChecker.repairOrReport(s,now);GirlCatSearchEngine.advance(s,now);CatOfflineEngine.followAttachment(s);CatOfflineEngine.wakeForPlayer(s,now);if(!reconstructed.isEmpty())ReunionEngine.process(s,now);r.save(s);runOnUiThread(()->{try{repository=r;state=s;voice=new VoiceController(this,new VoiceController.Listener(){public void onRecognized(String t){respondToVoice(t);}public void onStatus(String t){Toast.makeText(MainActivity.this,t,Toast.LENGTH_SHORT).show();}});gameView=new GameView(this,state,this);gameRoot=new FrameLayout(this);gameRoot.addView(gameView,new FrameLayout.LayoutParams(-1,-1));setContentView(gameRoot);GodSessionManager.addListener(this);GodSessionManager.warmup(getApplicationContext());if(!reconstructed.isEmpty())Toast.makeText(this,"Thế giới đã tiếp tục sống khi mèo ngủ.",Toast.LENGTH_LONG).show();maybeAskNotificationPermission();}catch(Throwable e){showStartupFailure(e);}});}catch(Throwable e){runOnUiThread(()->showStartupFailure(e));}},"VNF-World-Startup").start();}
 private void showStartupScreen(){TextView t=new TextView(this);t.setText("VNF\n\nĐang đánh thức thế giới…");t.setGravity(android.view.Gravity.CENTER);t.setTextColor(Color.rgb(241,229,201));t.setBackgroundColor(Color.rgb(18,31,33));t.setTextSize(22);setContentView(t);}
 @Override protected void onResume(){super.onResume();if(pendingUpdateApk!=null&&android.os.Build.VERSION.SDK_INT>=26&&getPackageManager().canRequestPackageInstalls()){File apk=pendingUpdateApk;pendingUpdateApk=null;try{AppUpdateManager.launchInstaller(this,apk);}catch(Throwable e){showUpdateError(e);}}else maybeCheckAppUpdate(false);if(state!=null&&!state.catState.awake){long n=System.currentTimeMillis();OfflineLifeEngine.reconstruct(state,n);GirlCatSearchEngine.advance(state,n);CatOfflineEngine.followAttachment(state);CatOfflineEngine.wakeForPlayer(state,n);ReunionEngine.process(state,n);repository.save(state);}if(gameView!=null)gameView.postInvalidate();}
 @Override protected void onPause(){super.onPause();if(state!=null){long n=System.currentTimeMillis();state.lastOpenedAt=n;state.lastSimulatedAt=n;state.catState.lastPlayerActiveAt=n;state.catState.x=state.catX;state.catState.awake=true;CatOfflineEngine.beginSleep(state,n);repository.save(state);ProactiveScheduler.scheduleApproximate(this,state);}}
 @Override protected void onDestroy(){GodSessionManager.removeListener(this);if(voice!=null)voice.destroy();super.onDestroy();}
 @Override public void onBackPressed(){if(godScene!=null){if(godScene.isSending()){Toast.makeText(this,"Thần đang trả lời…",Toast.LENGTH_SHORT).show();return;}closeGodScene();return;}super.onBackPressed();}
 @Override public void onGodSessionState(GodSessionManager.State s){if(godScene!=null)godScene.setSessionState(s);}
 @Override public void onTalk(){final EditText i=new EditText(this);i.setHint("Nói với cô ấy…");i.setSingleLine(false);i.setMaxLines(3);new AlertDialog.Builder(this).setTitle("Nói trong thế giới").setView(i).setPositiveButton("Nói",(d,w)->{HaruMind.Response r=HaruMind.respond(state,i.getText().toString());repository.save(state);new AlertDialog.Builder(this).setTitle(DisplayNames.girl(state)).setMessage(visibleResponse(r)).setPositiveButton("Ừ",null).show();}).setNegativeButton("Thôi",null).show();}
 @Override public void onVoiceTap(boolean d){if(d)voice.toggle();else voice.listen();}private void respondToVoice(String t){HaruMind.Response r=HaruMind.respond(state,t);repository.save(state);Toast.makeText(this,visibleResponse(r),Toast.LENGTH_LONG).show();voice.speak(r.speech);}private String visibleResponse(HaruMind.Response r){if(r==null)return"…";String e=r.expression==null?"":r.expression.trim();return e.isEmpty()?r.speech:"〈"+e+"〉\n\n"+r.speech;}
 @Override public void onGod(){if(godScene!=null||gameRoot==null)return;godScene=new GodContactScene(this,godInboxSummary(),new GodContactScene.Host(){public void onClose(){closeGodScene();}public void onSend(String q){handleGodMessage(q);}});gameRoot.addView(godScene.view(),new FrameLayout.LayoutParams(-1,-1));godScene.setSessionState(GodSessionManager.getState());GodSessionManager.warmup(getApplicationContext());}
 private void closeGodScene(){if(godScene!=null&&gameRoot!=null)gameRoot.removeView(godScene.view());godScene=null;try{hideSystemUi();}catch(Throwable ignored){}}
 private void handleGodMessage(String raw){final GodContactScene target=godScene;if(target==null)return;if(looksLikeContentRollback(raw)){RuntimeContentUpdater.Result rr=RuntimeContentUpdater.rollback(getApplicationContext());if(gameView!=null)gameView.postInvalidate();target.showSystem(rr.message);return;}if(isLocalGodCapability(raw)){String out=GodContactController.handle(state,raw);rememberGod(raw,out);target.showSystem(out);return;}if(!VnfOnlineConfig.godConfigured()){target.showError("Thần online chưa được cấu hình. Thế giới và cô gái vẫn tiếp tục offline.");return;}GodOnlineClient.ask(getApplicationContext(),state,raw,(result,error)->runOnUiThread(()->{if(error!=null){if(godScene==target){String d=error.getMessage()==null?error.getClass().getSimpleName():error.getMessage();if(d.length()>320)d=d.substring(0,320)+"…";target.showError(d);}return;}if(result==null){if(godScene==target)target.showError("Thần không trả lời.");return;}rememberGod(raw,result.reply);if(godScene!=target)return;if(result.godRecipePayload!=null&&!result.godRecipePayload.isEmpty()){RuntimeContentUpdater.Result rr=SignedGodWorldRecipe.apply(getApplicationContext(),result.godRecipePayload,result.godRecipeSignature);if(gameView!=null)gameView.postInvalidate();target.showReply(result.reply+"\n\nWORLD CONTENT: "+rr.message);return;}if(result.autoApplyContentPatch&&!result.contentPatchManifestUrl.isEmpty()){target.showProgress(result.reply+"\n\nĐang kiểm tra world-content patch đã ký…");RuntimeContentUpdater.applySignedManifestAsync(getApplicationContext(),result.contentPatchManifestUrl,pr->runOnUiThread(()->{if(gameView!=null)gameView.postInvalidate();if(godScene==target)target.showReply("WORLD CONTENT: "+pr.message);}));return;}String msg=result.reply;if(result.repairPlan!=null&&!result.repairPlan.summary().isEmpty())msg+="\n\nKẾ HOẠCH SỬA:\n"+result.repairPlan.summary()+"\n\nChưa có world-content patch đã ký để áp dụng.";target.showReply(msg);}));}
 private void rememberGod(String q,String a){if(state.godMemory==null)state.godMemory=new GodMemory();state.godMemory.remember(q,a,System.currentTimeMillis());repository.save(state);}
 private boolean looksLikeContentRollback(String r){String q=r.toUpperCase(java.util.Locale.ROOT);return q.contains("ROLLBACK CONTENT")||q.contains("HOÀN TÁC ĐỒ HỌA")||q.contains("HOAN TAC DO HOA")||q.contains("KHÔI PHỤC WORLD CONTENT")||q.contains("KHOI PHUC WORLD CONTENT");}
 private boolean isLocalGodCapability(String r){String q=r.toUpperCase(java.util.Locale.ROOT);if(!DivineNamingEngine.extractProposal(r).isEmpty())return true;if(GodTeachingGateway.looksLikeTeaching(r))return true;return q.contains("TRẠNG THÁI")||q.contains("TRANG THAI")||q.contains("BẢO VỆ")||q.contains("BAO VE")||q.contains("ĐÁNH GIÁ")||q.contains("DANH GIA")||q.contains("CHẨN ĐOÁN")||q.contains("CHAN DOAN")||q.contains("TÊN")||q.contains("TEN");}
 @Override public void onConsole(){final EditText i=new EditText(this);i.setHint("TRẠNG THÁI / CHẨN ĐOÁN / ...");i.setSingleLine(true);new AlertDialog.Builder(this).setTitle("SYSTEM · Thần").setMessage("Console này chỉ thao tác vùng an toàn. Nó không phải AI online.").setView(i).setPositiveButton("Chạy",(d,w)->{String out=SystemConsole.execute(state,i.getText().toString());repository.save(state);new AlertDialog.Builder(this).setTitle("SYSTEM").setMessage(out).setPositiveButton("Đóng",null).show();}).setNegativeButton("Đóng",null).show();}
 private String godInboxSummary(){StringBuilder b=new StringBuilder("Thế giới vẫn sống offline dù Thần mất kết nối.\n\nTIN TỪ THẦN:\n");int start=Math.max(0,state.godInbox.size()-5);for(int i=start;i<state.godInbox.size();i++){GodMessage m=state.godInbox.get(i);b.append(m.read?"· ":"• ").append(m.text).append('\n');m.read=true;}if(state.godInbox.isEmpty())b.append("(chưa có tin quan trọng)");repository.save(state);return b.toString();}
 // Updater is intentionally independent from WorldState/save loading. A launch can discover a new APK even if an old save is present.
 private void maybeCheckAppUpdate(boolean force){long now=System.currentTimeMillis();if(!VnfOnlineConfig.appUpdaterConfigured()||updateCheckInFlight||updateDialogVisible)return;if(!force&&now-lastUpdateCheckAt<UPDATE_RESUME_GUARD_MS)return;lastUpdateCheckAt=now;pendingUpdate=null;updateCheckInFlight=true;AppUpdateManager.checkAsync(getApplicationContext(),(u,e)->runOnUiThread(()->{updateCheckInFlight=false;if(e!=null||u==null){pendingUpdate=null;return;}int installed=installedVersionCode();if(u.versionCode<=installed){pendingUpdate=null;return;}pendingUpdate=u;updateDialogVisible=true;String msg="VNF "+(u.versionName.isEmpty()?u.versionCode:u.versionName)+" đã sẵn sàng."+(u.notes.isEmpty()?"":"\n\n"+u.notes)+"\n\nAPK sẽ được kiểm SHA-256, package và chữ ký trước khi Android cho cài. Thế giới/save không bị thay thế.";AlertDialog dialog=new AlertDialog.Builder(this).setTitle("CẬP NHẬT VNF").setMessage(msg).setPositiveButton("Tải và cập nhật",(d,w)->{updateDialogVisible=false;downloadPendingUpdate();}).setNegativeButton("Để sau",(d,w)->{updateDialogVisible=false;pendingUpdate=null;}).create();dialog.setOnCancelListener(d->{updateDialogVisible=false;pendingUpdate=null;});dialog.show();}));}
 private int installedVersionCode(){try{android.content.pm.PackageInfo p=getPackageManager().getPackageInfo(getPackageName(),0);return android.os.Build.VERSION.SDK_INT>=28?(int)p.getLongVersionCode():p.versionCode;}catch(Throwable ignored){return BuildConfig.VERSION_CODE;}}
 private void downloadPendingUpdate(){final AppUpdateManager.Update u=pendingUpdate;pendingUpdate=null;if(u==null||u.versionCode<=installedVersionCode())return;Toast.makeText(this,"Đang tải bản cập nhật VNF…",Toast.LENGTH_LONG).show();new Thread(()->{try{File apk=AppUpdateManager.downloadAndVerify(getApplicationContext(),u);runOnUiThread(()->requestInstallOrLaunch(apk));}catch(Throwable e){runOnUiThread(()->showUpdateError(e));}},"VNF-App-Update-Download").start();}
 private void requestInstallOrLaunch(File apk){if(android.os.Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){pendingUpdateApk=apk;new AlertDialog.Builder(this).setTitle("CHO PHÉP CẬP NHẬT VNF").setMessage("Android cần bạn cho phép VNF cài bản cập nhật từ nguồn này. Sau khi bật quyền, quay lại VNF; trình cài đặt sẽ tự mở.\n\nVNF không thể và không được phép vượt qua bước xác nhận của Android.").setPositiveButton("Mở cài đặt",(d,w)->startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())))).setNegativeButton("Hủy",(d,w)->pendingUpdateApk=null).show();return;}try{AppUpdateManager.launchInstaller(this,apk);}catch(Throwable e){showUpdateError(e);}}
 private void showUpdateError(Throwable e){pendingUpdate=null;String s=e==null?"Lỗi không xác định":e.getClass().getSimpleName()+": "+(e.getMessage()==null?"":e.getMessage());if(s.length()>500)s=s.substring(0,500)+"…";new AlertDialog.Builder(this).setTitle("CẬP NHẬT BỊ DỪNG").setMessage(s+"\n\nVNF hiện tại và dữ liệu thế giới vẫn được giữ nguyên.").setPositiveButton("Đóng",null).show();}
 private void showStartupFailure(Throwable e){StringBuilder msg=new StringBuilder("VNF đã mở ở chế độ an toàn.\n\nThế giới chưa được chạy để tránh làm hỏng save.\nDữ liệu hiện tại không bị tự động xóa.\n\nLỗi khởi động: ").append(e.getClass().getSimpleName());if(e.getMessage()!=null&&!e.getMessage().isEmpty())msg.append("\n").append(e.getMessage());TextView t=new TextView(this);t.setText(msg.toString());t.setTextColor(Color.rgb(241,229,201));t.setBackgroundColor(Color.rgb(18,31,33));t.setTextSize(18);int pad=(int)(24*getResources().getDisplayMetrics().density);t.setPadding(pad,pad,pad,pad);ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(18,31,33));s.addView(t);setContentView(s);}private void maybeAskNotificationPermission(){if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},401);}private void hideSystemUi(){if(android.os.Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController c=getWindow().getInsetsController();if(c!=null)c.hide(WindowInsets.Type.systemBars());}else getWindow().getDecorView().setSystemUiVisibility(5894);}
}
