package com.aicharacter.v3;

import android.Manifest;import android.app.Activity;import android.app.AlertDialog;import android.content.Intent;import android.content.pm.PackageManager;import android.net.Uri;import android.os.Bundle;import android.provider.Settings;import android.util.Log;import android.view.WindowInsets;import android.view.WindowInsetsController;import android.widget.EditText;import android.widget.Toast;import android.widget.TextView;import android.widget.ScrollView;import android.widget.FrameLayout;import android.graphics.Color;import java.io.File;

public final class MainActivity extends Activity implements GameView.Host,GodSessionManager.Listener{
 private static final String TAG="VNF";private WorldRepository repository;private WorldState state;private GameView gameView;private FrameLayout gameRoot;private VoiceController voice;private ProceduralAudioEngine audio;private AppUpdateManager.Update pendingUpdate;private File pendingUpdateApk;private GodContactScene godScene;private boolean updateCheckInFlight=false,updateDialogVisible=false,backgrounded=false,updateExternalFlow=false,permissionRequestIntroVisible=false,worldCatchupInFlight=false;private long lastUpdateCheckAt=0L,startupStartedAt=0L;private static final long UPDATE_RESUME_GUARD_MS=15000L;
 @Override protected void onCreate(Bundle b){
  super.onCreate(b);startupStartedAt=android.os.SystemClock.elapsedRealtime();showStartupScreen();try{hideSystemUi();}catch(Throwable ignored){}
  if(!isDebugVisualCapture())maybeCheckAppUpdate(true);
  final android.content.Context app=getApplicationContext();
  new Thread(()->{
   try{
    WorldRepository r=new WorldRepository(app);
    WorldState preview=r.loadOrCreate();
    applyDebugVisualCapture(preview);
    runOnUiThread(()->showWorldPreview(r,preview));
   }catch(Throwable e){runOnUiThread(()->showStartupFailure(e));}
  },"VNF-World-Bootstrap").start();
 }
 private void showWorldPreview(WorldRepository r,WorldState preview){
  try{
   repository=r;state=preview;worldCatchupInFlight=true;
   voice=new VoiceController(this,new VoiceController.Listener(){public void onRecognized(String t){respondToVoice(t);}public void onStatus(String t){Toast.makeText(MainActivity.this,t,Toast.LENGTH_SHORT).show();}});
   if(!isDebugVisualCapture()){audio=new ProceduralAudioEngine();audio.resume();}
   gameView=new GameView(this,state,this,false);
   if(BuildConfig.DEBUG){gameView.setDebugBiome(getIntent().getStringExtra("vnf_debug_biome"));gameView.setDebugHaruPose(getIntent().getStringExtra("vnf_debug_pose"));scheduleDebugVisualCapture();}
   gameRoot=new FrameLayout(this);gameRoot.addView(gameView,new FrameLayout.LayoutParams(-1,-1));setContentView(gameRoot);
   GodSessionManager.addListener(this);GodSessionManager.warmup(getApplicationContext());
   long visibleMs=Math.max(0,android.os.SystemClock.elapsedRealtime()-startupStartedAt);
   Log.i(TAG,"STARTUP_WORLD_VISIBLE ms="+visibleMs+" catchup=pending");
   new Thread(()->completeCausalStartup(r),"VNF-World-Catchup").start();
  }catch(Throwable e){showStartupFailure(e);}
 }
 private void completeCausalStartup(WorldRepository r){
  try{
   WorldState live=r.loadOrCreate();long now=System.currentTimeMillis();
   DivineMaintenanceEngine.maintain(live,now);LifeCycleEngine.apply(live,now);AgeDevelopmentEngine.apply(live,now);StateInvariantChecker.repairOrReport(live,now);
   if(!live.catState.awake)CatOfflineEngine.followAttachment(live);
   String reconstructed=OfflineLifeEngine.reconstruct(live,now);
   StateInvariantChecker.repairOrReport(live,now);GirlCatSearchEngine.advance(live,now);CatOfflineEngine.followAttachment(live);CatOfflineEngine.wakeForPlayer(live,now);
   applyDebugVisualCapture(live);r.save(live);
   runOnUiThread(()->finishCausalStartup(live,reconstructed));
  }catch(Throwable e){
   Log.e(TAG,"Deferred world catch-up failed",e);
   runOnUiThread(()->{
    worldCatchupInFlight=false;
    if(gameView!=null)gameView.setSimulationReady(true);
    if(!isDebugVisualCapture()&&gameView!=null)gameView.postDelayed(this::maybeHaruRequestCoreRuntimePermissions,1200L);
   });
  }
 }
 private void finishCausalStartup(WorldState live,String reconstructed){
  if(isFinishing()||isDestroyed())return;
  state=live;worldCatchupInFlight=false;
  if(gameView!=null)gameView.replaceState(live,true);
  long readyMs=Math.max(0,android.os.SystemClock.elapsedRealtime()-startupStartedAt);
  Log.i(TAG,"STARTUP_CAUSAL_READY ms="+readyMs+" offlineTrace="+(reconstructed==null?0:reconstructed.length()));
  if(reconstructed!=null&&!reconstructed.isEmpty())Toast.makeText(this,"Thế giới đã tiếp tục sống khi mèo ngủ.",Toast.LENGTH_LONG).show();
  if(!isDebugVisualCapture()&&gameView!=null)gameView.postDelayed(this::maybeHaruRequestCoreRuntimePermissions,1200L);
 }
 private void startResumeCausalCatchup(long resumedAt){
  if(repository==null||state==null||worldCatchupInFlight)return;
  worldCatchupInFlight=true;if(gameView!=null)gameView.setSimulationReady(false);
  final WorldRepository r=repository;
  new Thread(()->{
   try{
    WorldState live=r.loadOrCreate();long causalResume=Math.max(resumedAt,Math.max(live.lastSimulatedAt,live.lastOpenedAt));
    DivineMaintenanceEngine.maintain(live,causalResume);LifeCycleEngine.apply(live,causalResume);AgeDevelopmentEngine.apply(live,causalResume);
    OfflineLifeEngine.reconstruct(live,causalResume);StateInvariantChecker.repairOrReport(live,causalResume);GirlCatSearchEngine.advance(live,causalResume);CatOfflineEngine.followAttachment(live);CatOfflineEngine.wakeForPlayer(live,causalResume);r.save(live);
    runOnUiThread(()->{if(isFinishing()||isDestroyed())return;state=live;worldCatchupInFlight=false;if(gameView!=null)gameView.replaceState(live,true);Log.i(TAG,"RESUME_CAUSAL_READY");});
   }catch(Throwable e){Log.e(TAG,"Resume recovery failed",e);runOnUiThread(()->{worldCatchupInFlight=false;if(gameView!=null)gameView.setSimulationReady(true);});}
  },"VNF-Resume-Catchup").start();
 }
 private boolean worldReadyForInteraction(){if(!worldCatchupInFlight)return true;Toast.makeText(this,"Thế giới đang bắt kịp thời gian…",Toast.LENGTH_SHORT).show();return false;}
 private boolean isDebugVisualCapture(){return BuildConfig.DEBUG&&(getIntent().hasExtra("vnf_debug_biome")||getIntent().hasExtra("vnf_debug_pose"));}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(!BuildConfig.DEBUG||state==null||gameView==null)return;applyDebugVisualCapture(state);gameView.setDebugBiome(intent.getStringExtra("vnf_debug_biome"));gameView.setDebugHaruPose(intent.getStringExtra("vnf_debug_pose"));gameView.postInvalidate();scheduleDebugVisualCapture();Log.i(TAG,"VISUAL_CAPTURE_INTENT biome="+intent.getStringExtra("vnf_debug_biome")+" pose="+intent.getStringExtra("vnf_debug_pose"));}
 private void scheduleDebugVisualCapture(){if(!isDebugVisualCapture()||gameView==null)return;String raw=getIntent().getStringExtra("vnf_debug_capture_name");if(raw==null||raw.trim().isEmpty())raw=(getIntent().getStringExtra("vnf_debug_biome")+"_"+getIntent().getStringExtra("vnf_debug_pose"));final String name=raw.replaceAll("[^a-zA-Z0-9._-]","_");gameView.postDelayed(()->{try{File root=getFilesDir();File out=new File(new File(root,"visual-capture"),name+".png");boolean ok=gameView.writeDebugCapture(out);Log.i(TAG,"VISUAL_CAPTURE_FILE name="+name+" ok="+ok+" path="+out.getAbsolutePath()+" bytes="+(out.isFile()?out.length():0));}catch(Throwable e){Log.e(TAG,"VISUAL_CAPTURE_FILE failed name="+name,e);}},700L);}
 private void applyDebugVisualCapture(WorldState s){if(!isDebugVisualCapture()||s==null||s.world==null)return;String key=getIntent().getStringExtra("vnf_debug_biome");if(key==null||key.trim().isEmpty())return;String q=key.trim().toLowerCase(java.util.Locale.ROOT),id="home".equals(q)?"home_shelter":"garden".equals(q)?"garden_path":"grove".equals(q)?"quiet_grove":"lakeside".equals(q)?"lakeside":"";if(id.isEmpty())return;WorldArea a=s.world.area(id);if(a==null)return;s.haruX=(a.left+a.right)*.5f;if(s.girlTravel!=null)s.girlTravel.active=false;s.currentIntention="observe_lake";s.haruActivity="standing quietly";if(s.girlPhysics!=null){s.girlPhysics.falling=false;s.girlPhysics.grounded=true;s.girlPhysics.groundClearanceM=0;s.girlPhysics.velocityX=0;s.girlPhysics.velocityY=0;}}
 private void showStartupScreen(){TextView t=new TextView(this);t.setText("VNF\n\nĐang đánh thức thế giới…");t.setGravity(android.view.Gravity.CENTER);t.setTextColor(Color.rgb(241,229,201));t.setBackgroundColor(Color.rgb(18,31,33));t.setTextSize(22);setContentView(t);}
 @Override protected void onResume(){super.onResume();long resumedAt=System.currentTimeMillis();boolean returningFromUpdateFlow=updateExternalFlow;updateExternalFlow=false;if(pendingUpdateApk!=null&&android.os.Build.VERSION.SDK_INT>=26&&getPackageManager().canRequestPackageInstalls()){File apk=pendingUpdateApk;pendingUpdateApk=null;launchUpdateInstaller(apk);}else if(!returningFromUpdateFlow&&!isDebugVisualCapture())maybeCheckAppUpdate(false);if(backgrounded&&state!=null){backgrounded=false;startResumeCausalCatchup(resumedAt);}if(audio!=null)audio.resume();if(gameView!=null)gameView.postInvalidate();}
 @Override protected void onPause(){super.onPause();if(audio!=null)audio.pause();if(state!=null&&repository!=null&&!worldCatchupInFlight){try{repository.save(state);}catch(Throwable e){Log.e(TAG,"Save on pause failed",e);}}}
 @Override protected void onStop(){super.onStop();if(updateExternalFlow){if(state!=null&&repository!=null){try{repository.save(state);}catch(Throwable e){Log.e(TAG,"Save before update flow failed",e);}}return;}if(state!=null&&repository!=null&&!worldCatchupInFlight&&!backgrounded){long wall=System.currentTimeMillis(),n=Math.max(wall,Math.max(state.lastOpenedAt,state.lastSimulatedAt));backgrounded=true;state.lastOpenedAt=Math.max(state.lastOpenedAt,n);state.catState.lastPlayerActiveAt=Math.max(state.catState.lastPlayerActiveAt,n);state.catState.x=state.catX;state.catState.awake=true;CatOfflineEngine.beginSleep(state,n);try{repository.save(state);}catch(Throwable e){Log.e(TAG,"Save on stop failed",e);}ProactiveScheduler.scheduleApproximate(this,state);}}
 @Override protected void onDestroy(){GodSessionManager.removeListener(this);if(voice!=null)voice.destroy();if(audio!=null)audio.destroy();super.onDestroy();}
 @Override public void onBackPressed(){if(godScene!=null){if(godScene.isSending()){Toast.makeText(this,"Không gian vẫn đang dao động…",Toast.LENGTH_SHORT).show();return;}godScene.dismiss(this::closeGodScene);return;}super.onBackPressed();}
 @Override public void onGodSessionState(GodSessionManager.State s){if(godScene!=null)godScene.setSessionState(s);}
 @Override public void onTalk(){if(!worldReadyForInteraction())return;final EditText i=new EditText(this);i.setHint("Nói với cô ấy…");i.setSingleLine(false);i.setMaxLines(3);new AlertDialog.Builder(this).setTitle("Nói trong thế giới").setView(i).setPositiveButton("Nói",(d,w)->{HaruMind.Response r=HaruMind.respond(state,i.getText().toString());repository.save(state);new AlertDialog.Builder(this).setTitle(DisplayNames.girl(state)).setMessage(visibleResponse(r)).setPositiveButton("Ừ",null).show();}).setNegativeButton("Thôi",null).show();}
 @Override public void onVoiceTap(boolean d){if(!worldReadyForInteraction())return;if(d)voice.toggle();else voice.listen();}@Override public void onAudioScene(AudioSceneFrame frame){if(audio!=null)audio.update(frame);}@Override public void onSoundEvent(SoundEvent event){if(audio!=null)audio.play(event);}@Override public void onHaruProactiveSpeech(HaruProactiveSpeechEngine.Cue cue){if(cue==null||cue.text==null||cue.text.isEmpty())return;if(voice!=null)voice.speakProactive(cue.text);if(repository!=null&&state!=null){try{repository.save(state);}catch(Throwable e){Log.w(TAG,"Could not persist proactive Haru speech delivery",e);}}}private void respondToVoice(String t){HaruMind.Response r=HaruMind.respond(state,t);repository.save(state);Toast.makeText(this,visibleResponse(r),Toast.LENGTH_LONG).show();voice.speak(r.speech);}private String visibleResponse(HaruMind.Response r){if(r==null)return"…";String e=r.expression==null?"":r.expression.trim();return e.isEmpty()?r.speech:"〈"+e+"〉\n\n"+r.speech;}
 @Override public void onGod(){if(!worldReadyForInteraction())return;if(godScene!=null||gameRoot==null)return;if(gameView!=null)gameView.setDivineVisualPresence(true);godScene=new GodContactScene(this,godInboxSummary(),new GodContactScene.Host(){public void onClose(){closeGodScene();}public void onSend(String q){handleGodMessage(q);}});gameRoot.addView(godScene.view(),new FrameLayout.LayoutParams(-1,-1));godScene.setSessionState(GodSessionManager.getState());GodSessionManager.warmup(getApplicationContext());}
 private void closeGodScene(){if(godScene!=null&&gameRoot!=null)gameRoot.removeView(godScene.view());godScene=null;if(gameView!=null)gameView.setDivineVisualPresence(false);try{hideSystemUi();}catch(Throwable ignored){}}
 private void handleGodMessage(String raw){final GodContactScene target=godScene;if(target==null)return;if(looksLikeContentRollback(raw)){RuntimeContentUpdater.Result rr=RuntimeContentUpdater.rollback(getApplicationContext());if(gameView!=null)gameView.postInvalidate();target.showSystem(rr.ok?"Những thay đổi gần nhất đã lùi lại. Thế giới đã ổn định.":"Không có thay đổi nào có thể lùi lại lúc này.");return;}if(isLocalGodCapability(raw)){String out=GodContactController.handle(state,raw);rememberGod(raw,out);target.showSystem(out);return;}if(!VnfOnlineConfig.godConfigured()){target.showError("Không có lời đáp lúc này. Thế giới vẫn tiếp tục.");return;}GodOnlineClient.ask(getApplicationContext(),state,raw,(result,error)->runOnUiThread(()->{if(error!=null){if(godScene==target)target.showError("Không có lời đáp lúc này.");return;}if(result==null){if(godScene==target)target.showError("Chỉ còn một khoảng lặng.");return;}rememberGod(raw,result.reply);if(result.worldEventProposal!=null){long eventNow=Math.max(state.lastSimulatedAt,state.lastOpenedAt);GodWorldEventExecutor.Result er=GodWorldEventExecutor.apply(state,result.worldEventProposal,eventNow);if(er.ok){repository.save(state);if(gameView!=null)gameView.postInvalidate();}}if(godScene!=target)return;if(result.godRecipePayload!=null&&!result.godRecipePayload.isEmpty()){RuntimeContentUpdater.Result rr=SignedGodWorldRecipe.apply(getApplicationContext(),result.godRecipePayload,result.godRecipeSignature);if(gameView!=null)gameView.postInvalidate();target.showReply(result.reply);return;}if(result.autoApplyContentPatch&&!result.contentPatchManifestUrl.isEmpty()){target.showProgress(result.reply+"\n\nÁnh sáng quanh thế giới đang đổi khác…");RuntimeContentUpdater.applySignedManifestAsync(getApplicationContext(),result.contentPatchManifestUrl,pr->runOnUiThread(()->{if(gameView!=null)gameView.postInvalidate();if(godScene==target)target.showReply(pr.ok?"Mọi thứ đã lắng lại.":"Sự thay đổi đã dừng lại." );}));return;}target.showReply(result.reply);}));}
 private void rememberGod(String q,String a){if(state.godMemory==null)state.godMemory=new GodMemory();long n=Math.max(System.currentTimeMillis(),Math.max(state.lastOpenedAt,state.lastSimulatedAt));state.godMemory.remember(q,a,n);repository.save(state);}
 private boolean looksLikeContentRollback(String r){String q=r.toUpperCase(java.util.Locale.ROOT);return q.contains("ROLLBACK CONTENT")||q.contains("HOÀN TÁC ĐỒ HỌA")||q.contains("HOAN TAC DO HOA")||q.contains("KHÔI PHỤC WORLD CONTENT")||q.contains("KHOI PHUC WORLD CONTENT");}
 private boolean isLocalGodCapability(String r){String q=r.toUpperCase(java.util.Locale.ROOT);if(!DivineNamingEngine.extractProposal(r).isEmpty())return true;if(GodTeachingGateway.looksLikeTeaching(r))return true;return q.contains("TRẠNG THÁI")||q.contains("TRANG THAI")||q.contains("BẢO VỆ")||q.contains("BAO VE")||q.contains("ĐÁNH GIÁ")||q.contains("DANH GIA")||q.contains("CHẨN ĐOÁN")||q.contains("CHAN DOAN")||q.contains("TÊN")||q.contains("TEN");}
 @Override public void onConsole(){if(!worldReadyForInteraction())return;final EditText i=new EditText(this);i.setHint("TRẠNG THÁI / CHẨN ĐOÁN / ...");i.setSingleLine(true);new AlertDialog.Builder(this).setTitle("SYSTEM · Thần").setMessage("Chỉ những thay đổi an toàn của thế giới mới có thể được thực hiện tại đây.\n\nTest hình ảnh: DEV GOD VEIL / DEV GOD VEIL SEVERE").setView(i).setPositiveButton("Chạy",(d,w)->{String raw=i.getText().toString();if(runGodVeilTest(raw)||runHaruVisionTest(raw))return;String out=SystemConsole.execute(state,raw);repository.save(state);new AlertDialog.Builder(this).setTitle("SYSTEM").setMessage(out).setPositiveButton("Đóng",null).show();}).setNegativeButton("Đóng",null).show();}
 private boolean runGodVeilTest(String raw){String q=raw==null?"":raw.trim().toUpperCase(java.util.Locale.ROOT);boolean severe=q.equals("DEV GOD VEIL SEVERE")||q.equals("TEST BAI XICH")||q.equals("TEST BÀI XÍCH");boolean normal=q.equals("DEV GOD VEIL")||q.equals("TEST MAN THAN")||q.equals("TEST MÀN THẦN");if(!severe&&!normal)return false;if(gameView!=null)gameView.showGodVeilTest(severe);Toast.makeText(this,severe?"Đang thử màn chắn cấp cao.":"Đang thử màn ổn định thế giới.",Toast.LENGTH_SHORT).show();return true;}
 private boolean runHaruVisionTest(String raw){String q=raw==null?"":raw.trim().toUpperCase(java.util.Locale.ROOT);if(!q.equals("DEV HARU VISION")&&!q.equals("HARU VISION TEST"))return false;if(gameView!=null)gameView.showHaruVisionTest();Toast.makeText(this,"Đang hiển thị nhận thức hiện tại của Haru.",Toast.LENGTH_SHORT).show();return true;}
 private String godInboxSummary(){StringBuilder b=new StringBuilder("TIN TỪ THẦN\n\n");int start=Math.max(0,state.godInbox.size()-5);for(int i=start;i<state.godInbox.size();i++){GodMessage m=state.godInbox.get(i);b.append(m.read?"· ":"• ").append(m.text).append('\n');m.read=true;}if(state.godInbox.isEmpty())b.append("(chưa có lời nhắn)");repository.save(state);return b.toString();}
 private void maybeCheckAppUpdate(boolean force){long now=System.currentTimeMillis();if(!VnfOnlineConfig.appUpdaterConfigured()||updateCheckInFlight||updateDialogVisible)return;if(!force&&now-lastUpdateCheckAt<UPDATE_RESUME_GUARD_MS)return;lastUpdateCheckAt=now;pendingUpdate=null;updateCheckInFlight=true;AppUpdateManager.checkAsync(getApplicationContext(),(u,e)->runOnUiThread(()->{updateCheckInFlight=false;if(e!=null){Log.w(TAG,"Update check failed",e);pendingUpdate=null;return;}if(u==null){pendingUpdate=null;return;}int installed=installedVersionCode();if(u.versionCode<=installed){pendingUpdate=null;return;}pendingUpdate=u;updateDialogVisible=true;String msg="VNF "+(u.versionName.isEmpty()?u.versionCode:u.versionName)+" đã sẵn sàng."+(u.notes.isEmpty()?"":"\n\n"+u.notes)+"\n\nBản cập nhật sẽ được kiểm tra an toàn trước khi Android cho phép cài. Thế giới và ký ức hiện tại được giữ nguyên.";AlertDialog dialog=new AlertDialog.Builder(this).setTitle("CẬP NHẬT VNF").setMessage(msg).setPositiveButton("Tải và cập nhật",(d,w)->{updateDialogVisible=false;downloadPendingUpdate();}).setNegativeButton("Để sau",(d,w)->{updateDialogVisible=false;pendingUpdate=null;}).create();dialog.setOnCancelListener(d->{updateDialogVisible=false;pendingUpdate=null;});dialog.show();}));}
 private int installedVersionCode(){try{android.content.pm.PackageInfo p=getPackageManager().getPackageInfo(getPackageName(),0);return android.os.Build.VERSION.SDK_INT>=28?(int)p.getLongVersionCode():p.versionCode;}catch(Throwable ignored){return BuildConfig.VERSION_CODE;}}
 private void downloadPendingUpdate(){final AppUpdateManager.Update u=pendingUpdate;pendingUpdate=null;if(u==null||u.versionCode<=installedVersionCode())return;Toast.makeText(this,"Đang đón bản cập nhật VNF…",Toast.LENGTH_LONG).show();new Thread(()->{try{File apk=AppUpdateManager.downloadAndVerify(getApplicationContext(),u);runOnUiThread(()->requestInstallOrLaunch(apk));}catch(Throwable e){runOnUiThread(()->showUpdateError(e));}},"VNF-App-Update-Download").start();}
 private void requestInstallOrLaunch(File apk){if(android.os.Build.VERSION.SDK_INT>=26&&!getPackageManager().canRequestPackageInstalls()){pendingUpdateApk=apk;new AlertDialog.Builder(this).setTitle("CHO PHÉP CẬP NHẬT VNF").setMessage("Android cần bạn cho phép VNF cài bản cập nhật từ nguồn này. Sau khi bật quyền, quay lại VNF; màn hình xác nhận cài đặt sẽ tự mở.\n\nVNF không thể bỏ qua bước xác nhận của Android.").setPositiveButton("Mở cài đặt",(d,w)->{updateExternalFlow=true;try{startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+getPackageName())));}catch(Throwable e){updateExternalFlow=false;showUpdateError(e);}}).setNegativeButton("Hủy",(d,w)->pendingUpdateApk=null).show();return;}launchUpdateInstaller(apk);}
 private void launchUpdateInstaller(File apk){updateExternalFlow=true;try{AppUpdateManager.launchInstaller(this,apk);}catch(Throwable e){updateExternalFlow=false;showUpdateError(e);}}
 private void showUpdateError(Throwable e){pendingUpdate=null;Log.e(TAG,"Update stopped",e);new AlertDialog.Builder(this).setTitle("CẬP NHẬT BỊ DỪNG").setMessage("Bản cập nhật chưa thể hoàn tất. VNF hiện tại, thế giới và ký ức vẫn được giữ nguyên.\n\nBạn có thể thử lại khi mở VNF lần sau.").setPositiveButton("Đóng",null).show();}
 private void showStartupFailure(Throwable e){Log.e(TAG,"World startup failed",e);TextView t=new TextView(this);t.setText("VNF đã mở ở chế độ an toàn.\n\nThế giới chưa được chạy để tránh làm hỏng ký ức hiện tại.\nDữ liệu không bị tự động xóa.\n\nHãy đóng rồi mở lại VNF. Nếu tình trạng vẫn lặp lại, giữ nguyên dữ liệu và kiểm tra bản cập nhật tiếp theo.");t.setTextColor(Color.rgb(241,229,201));t.setBackgroundColor(Color.rgb(18,31,33));t.setTextSize(18);int pad=(int)(24*getResources().getDisplayMetrics().density);t.setPadding(pad,pad,pad,pad);ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(18,31,33));s.addView(t);setContentView(s);}private void maybeHaruRequestCoreRuntimePermissions(){if(permissionRequestIntroVisible||isFinishing()||isDestroyed())return;boolean mic=checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED;boolean notifications=android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED;if(!mic&&!notifications)return;permissionRequestIntroVisible=true;String message;if(mic&&notifications)message="Mình muốn nghe được khi bạn nói với mình. Và nếu có chuyện đáng để gọi bạn khi bạn không ở đây, mình cũng muốn tự báo cho bạn.\n\nBạn cho mình hai quyền đó nhé?";else if(mic)message="Mình muốn nghe được khi bạn nói với mình, thay vì bắt bạn phải gõ mọi lúc.\n\nBạn cho mình quyền dùng micro nhé?";else message="Nếu có chuyện thật sự đáng để gọi bạn khi bạn không ở đây, mình muốn có thể tự báo cho bạn.\n\nBạn cho mình quyền gửi thông báo nhé?";new AlertDialog.Builder(this).setTitle("Haru chủ động hỏi").setMessage(message).setPositiveButton("Cho phép",(d,w)->{permissionRequestIntroVisible=false;requestCoreRuntimePermissions();}).setNegativeButton("Chưa",(d,w)->permissionRequestIntroVisible=false).setOnCancelListener(d->permissionRequestIntroVisible=false).show();}private void requestCoreRuntimePermissions(){java.util.ArrayList<String> missing=new java.util.ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)missing.add(Manifest.permission.RECORD_AUDIO);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)missing.add(Manifest.permission.POST_NOTIFICATIONS);if(!missing.isEmpty())requestPermissions(missing.toArray(new String[0]),403);}private void hideSystemUi(){if(android.os.Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController c=getWindow().getInsetsController();if(c!=null)c.hide(WindowInsets.Type.systemBars());}else getWindow().getDecorView().setSystemUiVisibility(5894);}
}
