package com.aicharacter.v3;
import java.util.Calendar;
/** Bounded, idempotent persistent-life reconstruction reusing the same decision/travel/search engines as active life. */
public final class OfflineLifeEngine{private OfflineLifeEngine(){}
 public static String reconstruct(WorldState s,long now){StateInvariantChecker.normalize(s,now);long base=s.lastSimulatedAt>0?s.lastSimulatedAt:s.lastOpenedAt;if(now<=base){syncClock(s,now);s.lastOfflineTrace="OFFLINE TRACE V108 idempotent: no unsimulated interval";return s.lastOfflineTrace;}long delta=now-base;if(delta>30L*24*3600000L)delta=30L*24*3600000L;long away=delta/60000L;if(away<1){syncClock(s,now);s.lastSimulatedAt=now;return"";}s.lastAbsenceMinutes=away;if(s.catState.awake&&away>=2)CatOfflineEngine.beginSleep(s,base+60000L);int count=eventBudget(away);StringBuilder tr=new StringBuilder("OFFLINE TRACE V108 elapsedMin=").append(away).append(" budget=").append(count).append("\n");long cursor=base;for(int i=1;i<=count;i++){long t=base+delta*i/count;double minutes=Math.max(1,(t-cursor)/60000.0);cursor=t;syncClock(s,t);progressWeather(s,t);BodyRhythmEngine.advanceMinutes(s,minutes);EnvironmentConsequences.advance(s,minutes);decayMind(s,minutes);CreatureLifeEngine.advance(s,minutes,t);String prior=state(s);CatOfflineEngine.advanceSleepTravel(s,minutes,t);CatOfflineEngine.followAttachment(s);if(GirlCatSearchEngine.shouldSearch(s,t))GirlCatSearchEngine.start(s,t,"absence, relationship and remembered evidence made search worthwhile");advanceGirlLife(s,minutes,t);CatOfflineEngine.followAttachment(s);tr.append(t).append(" actor=world prior={").append(prior).append("} result={").append(state(s)).append("}\n");}
  syncClock(s,now);if(away>180){MemoryEntry m=CognitionEngine.process(s,new Experience("absence","The cat had been away long enough for its absence to become noticeable.",-.08,.35+.35*Math.min(1,away/1440.0)).at(HaruPerception.currentPlaceId(s),"").with("cat").tag("absence").tag("player"));CognitionEngine.reviseFromMemory(s,"cat_returns","usually_returns",-1,Math.min(.9,.25+away/4320.0),m);}MemoryConsolidationEngine.consolidate(s,now);DiaryEngine.reflect(s,now);s.reunionContext=ReunionEngine.contextKey(s,away);s.lastSimulatedAt=now;s.lastOpenedAt=now;s.lastOfflineTrace=tr.toString();return tr.toString();}
 private static void decayMind(WorldState s,double minutes){double seconds=minutes*60.0;if(s.emotion!=null)s.emotion.decay(Math.pow(.997,seconds));if(s.mood!=null)s.mood.decay(Math.pow(.9997,seconds));}
 private static void syncClock(WorldState s,long timestamp){Calendar c=Calendar.getInstance();c.setTimeInMillis(timestamp);s.worldMinutes=c.get(Calendar.HOUR_OF_DAY)*60+c.get(Calendar.MINUTE)+c.get(Calendar.SECOND)/60.0;s.environment.updateForTime(s.worldMinutes);}
 private static void advanceGirlLife(WorldState s,double minutes,long now){if(!BodyRhythmEngine.isSleeping(s)&&BodyRhythmEngine.shouldCollapse(s)){BodyRhythmEngine.collapse(s,now);return;}if(BodyRhythmEngine.shouldRemainAsleep(s))return;if(BodyRhythmEngine.isSleeping(s)){s.haruActivity="waking slowly";s.currentIntention="";s.persistentIntentionTarget="";s.intentionStartedAt=now;if(BodyRhythmEngine.needsRecoveryTransition(s))return;}if(s.planState==null)s.planState=new PlanState();if(s.catSearch.active){GirlCatSearchEngine.advance(s,now,minutes);return;}if(s.girlTravel.active){PlanIntegrityChecker.check(s,now);PlanReconsiderationEngine.Result rr=PlanReconsiderationEngine.evaluate(s,now);s.planState.lastReconsideredAt=now;if(rr.reconsider())PlanExecutor.applyDecision(s,rr,now);if(s.girlTravel.active)TravelEngine.advanceMinutes(s,s.girlTravel,minutes,now);return;}if("PAUSED".equals(s.planState.status)){s.planState.lastReconsideredAt=now;if(PlanExecutor.resume(s,now)){if(s.girlTravel.active)TravelEngine.advanceMinutes(s,s.girlTravel,minutes,now);return;}}if(("COMPLETED".equals(s.planState.status)||"FAILED".equals(s.planState.status)||"ABANDONED".equals(s.planState.status))&&s.planState.lastProgressAt>0&&now-s.planState.lastProgressAt<12000L)return;PlanIntegrityChecker.check(s,now);PlanReconsiderationEngine.Result rr=PlanReconsiderationEngine.evaluate(s,now);s.planState.lastReconsideredAt=now;if(s.planState.active()&&!rr.reconsider())return;if(rr.reconsider()){PlanExecutor.applyDecision(s,rr,now);if(s.planState.active()){if(s.girlTravel.active)TravelEngine.advanceMinutes(s,s.girlTravel,minutes,now);return;}}LifeDecision d=LifeDecisionEngine.choose(s,now);beginDecision(s,d,now);if(s.girlTravel.active)TravelEngine.advanceMinutes(s,s.girlTravel,minutes,now);}
 public static void beginDecision(WorldState s,LifeDecision d,long now){if(s==null||d==null||d.intention==null)return;Intention in=d.intention;if("find_cat".equals(in.id)){GirlCatSearchEngine.start(s,now,"shared autonomy selected find_cat");return;}s.currentIntention=in.id;s.persistentIntentionTarget=in.targetId;s.intentionStartedAt=now;s.haruActivity=activityText(in.id);s.planState=new PlanState();s.planState.planId="plan_"+Long.toHexString(now);s.planState.intentionId=in.id;s.planState.goal=in.expectedOutcome;s.planState.status="ACTIVE";s.planState.commitment=Math.max(.25,Math.min(.9,.35+in.urgency*.45));s.planState.createdAt=now;s.planState.lastProgressAt=now;WorldObject o=s.world==null?null:s.world.object(in.targetId);String dest=o!=null?o.areaId:in.targetId;s.planState.destination=in.targetId;s.planState.plannedAction=plannedAction(in.id);s.planState.steps.add("TRAVEL:"+dest);s.planState.steps.add("ACTION:"+s.planState.plannedAction);if(s.world!=null&&s.world.area(dest)!=null){if(!TravelEngine.start(s,s.girlTravel,"girl",dest,s.planState.planId,now))s.planState.status="FAILED";}else s.planState.status="FAILED";}
 private static String plannedAction(String id){if("sleep".equals(id)||"seek_shelter".equals(id)||"recover".equals(id))return"REST_PROTECT";if("reflect".equals(id)||"quiet_pause".equals(id))return"REFLECT";return"OBSERVE";}
 private static String activityText(String id){if("sleep".equals(id))return"resting";if("seek_shelter".equals(id))return"looking for shelter";if("recover".equals(id))return"taking a quiet rest";if("reflect".equals(id))return"thinking quietly";if("observe_lake".equals(id))return"watching the lake";if("explore_garden".equals(id))return"wandering along the garden path";if("watch_reedling".equals(id))return"watching the small creature";if("seek_solitude".equals(id)||"quiet_pause".equals(id))return"spending a quiet moment alone";return id==null?"":id;}
 private static int eventBudget(long m){if(m<60)return 2;if(m<360)return 4;if(m<720)return 5;if(m<1440)return 7;return 8;}
 private static void progressWeather(WorldState s,long t){long bucket=t/(3*3600000L),mixed=(bucket*1103515245L+12345L)&0x7fffffffL;double climate=(mixed%1000)/1000.0;String next=climate<.16?"RAIN":climate<.42?"CLOUDY":"CLEAR";if(!next.equals(s.environment.weather)){s.environment.setWeather(next,"RAIN".equals(next)?.62:"CLOUDY".equals(next)?.3:.1,t);WorldEventBus.publishId(s,t,"weather_"+bucket,"WEATHER",next,"Weather progressed during absence.");if(!s.catState.awake&&"RAIN".equals(next)&&s.environment.weatherIntensity>.55)WorldEventBus.publishId(s,t,"cat_weather_"+bucket,"CAT_WEATHER_RISK","cat","Weather worsened around the resting cat.");}}
 private static String state(WorldState s){return"time="+(int)s.worldMinutes+" weather="+s.environment.weather+" girlX="+(int)s.haruX+" catX="+(int)s.catState.x+" cat="+s.catState.sleepMode+" attached="+s.catState.attachedToEntity+" intention="+s.currentIntention+" plan="+s.planState.status;}
}
