package com.aicharacter.v3;
/** Bounded, idempotent persistent-life reconstruction reusing online decision/travel/search engines. */
public final class OfflineLifeEngine{private OfflineLifeEngine(){}
 public static String reconstruct(WorldState s,long now){long base=s.lastSimulatedAt>0?s.lastSimulatedAt:s.lastOpenedAt;if(now<=base){s.lastOfflineTrace="OFFLINE TRACE V2 idempotent: no unsimulated interval";return s.lastOfflineTrace;}long delta=now-base;if(delta>30L*24*3600000L)delta=30L*24*3600000L;long away=delta/60000L;if(away<1){s.lastSimulatedAt=now;return"";}s.lastAbsenceMinutes=away;if(s.catState.awake&&away>=2)CatOfflineEngine.beginSleep(s,base+60000L);int count=eventBudget(away);StringBuilder tr=new StringBuilder("OFFLINE TRACE V2 elapsedMin=").append(away).append(" budget=").append(count).append("\n");long cursor=base;for(int i=1;i<=count;i++){long t=base+delta*i/count;double minutes=Math.max(1,(t-cursor)/60000.0);cursor=t;s.worldMinutes=(s.worldMinutes+minutes)%1440;s.environment.updateForTime(s.worldMinutes);progressWeather(s,t);EnvironmentConsequences.advance(s,minutes);CreatureLifeEngine.advance(s,minutes,t);String prior=state(s);CatOfflineEngine.advanceSleepTravel(s,minutes,t);CatOfflineEngine.followAttachment(s);if(GirlCatSearchEngine.shouldSearch(s,t))GirlCatSearchEngine.start(s,t,"absence, relationship and remembered evidence made search worthwhile");if(s.catSearch.active)GirlCatSearchEngine.advance(s,t,minutes);else if(s.girlTravel.active){PlanReconsiderationEngine.Result rr=PlanReconsiderationEngine.evaluate(s,t);if(rr.reconsider())PlanExecutor.applyDecision(s,rr,t);else TravelEngine.advanceMinutes(s,s.girlTravel,minutes,t);}else{LifeDecision d=LifeDecisionEngine.choose(s,t);beginDecision(s,d,t);if(s.girlTravel.active)TravelEngine.advanceMinutes(s,s.girlTravel,minutes,t);}CatOfflineEngine.followAttachment(s);tr.append(t).append(" actor=world prior={").append(prior).append("} result={").append(state(s)).append("}\n");}
  if(away>180){MemoryEntry m=CognitionEngine.process(s,new Experience("absence","The cat had been away long enough for its absence to become noticeable.",-.08,.35+.35*Math.min(1,away/1440.0)).at(HaruPerception.currentPlaceId(s),"").with("cat").tag("absence").tag("player"));CognitionEngine.reviseFromMemory(s,"cat_returns","usually_returns",-1,Math.min(.9,.25+away/4320.0),m);}MemoryConsolidationEngine.consolidate(s,now);DiaryEngine.reflect(s,now);s.reunionContext=ReunionEngine.contextKey(s,away);s.lastSimulatedAt=now;s.lastOpenedAt=now;s.lastOfflineTrace=tr.toString();return tr.toString();}
 public static void beginDecision(WorldState s,LifeDecision d,long now){Intention in=d.intention;if("find_cat".equals(in.id)){GirlCatSearchEngine.start(s,now,"shared autonomy selected find_cat");return;}s.currentIntention=in.id;s.persistentIntentionTarget=in.targetId;s.intentionStartedAt=now;s.planState=new PlanState();s.planState.planId="plan_"+Long.toHexString(now);s.planState.intentionId=in.id;s.planState.goal=in.expectedOutcome;s.planState.status="ACTIVE";s.planState.commitment=Math.max(.25,Math.min(.9,.35+in.urgency*.45));s.planState.createdAt=now;s.planState.lastProgressAt=now;WorldObject o=s.world.object(in.targetId);String dest=o!=null?o.areaId:in.targetId;s.planState.destination=in.targetId;s.planState.plannedAction=("sleep".equals(in.id)||"seek_shelter".equals(in.id))?"REST_PROTECT":"reflect".equals(in.id)?"REFLECT":"OBSERVE";if(s.world.area(dest)!=null){s.planState.steps.add("TRAVEL:"+dest);s.planState.steps.add("ACTION:"+s.planState.plannedAction);if(!TravelEngine.start(s,s.girlTravel,"girl",dest,s.planState.planId,now))s.planState.status="FAILED";}else s.planState.status="FAILED";}
 private static int eventBudget(long m){if(m<60)return 2;if(m<360)return 4;if(m<720)return 5;if(m<1440)return 7;return 8;}
 private static void progressWeather(WorldState s,long t){long bucket=t/(3*3600000L),mixed=(bucket*1103515245L+12345L)&0x7fffffffL;double climate=(mixed%1000)/1000.0;String next=climate<.16?"RAIN":climate<.42?"CLOUDY":"CLEAR";if(!next.equals(s.environment.weather)){s.environment.setWeather(next,"RAIN".equals(next)?.62:"CLOUDY".equals(next)?.3:.1,t);WorldEventBus.publishId(s,t,"weather_"+bucket,"WEATHER",next,"Weather progressed during absence.");if(!s.catState.awake&&"RAIN".equals(next)&&s.environment.weatherIntensity>.55)WorldEventBus.publishId(s,t,"cat_weather_"+bucket,"CAT_WEATHER_RISK","cat","Weather worsened around the resting cat.");}}
 private static String state(WorldState s){return"time="+(int)s.worldMinutes+" weather="+s.environment.weather+" girlX="+(int)s.haruX+" catX="+(int)s.catState.x+" cat="+s.catState.sleepMode+" attached="+s.catState.attachedToEntity+" intention="+s.currentIntention;}
}
