package com.aicharacter.v3;
import org.json.*;import java.util.*;
/** Haru's own bottom-up concepts. Features come only from her perceived cues and personal observations. */
public final class PerceptualConceptState{
 public static final class Profile{
  public String key="";public int observations;public long lastSeenAt;public final Map<String,Double> features=new LinkedHashMap<>();
  public double feature(String k){return features.getOrDefault(k,0.0);}
  JSONObject toJson(){JSONObject j=new JSONObject();try{j.put("key",key);j.put("observations",observations);j.put("lastSeenAt",lastSeenAt);JSONObject f=new JSONObject();for(Map.Entry<String,Double>e:features.entrySet())f.put(e.getKey(),e.getValue());j.put("features",f);}catch(Exception ignored){}return j;}
  static Profile fromJson(JSONObject j){Profile p=new Profile();if(j==null)return p;p.key=j.optString("key","");p.observations=Math.max(0,j.optInt("observations"));p.lastSeenAt=j.optLong("lastSeenAt");JSONObject f=j.optJSONObject("features");if(f!=null){Iterator<String>it=f.keys();while(it.hasNext()){String k=it.next();p.features.put(k,cl(f.optDouble(k)));}}return p;}
 }
 public static final class Concept{
  public String id="",name="";public final List<String> definingFeatures=new ArrayList<>();public final LinkedHashSet<String> members=new LinkedHashSet<>();public double confidence=.25;public int support,contradictions,revisions;public long createdAt,lastUpdatedAt;
  JSONObject toJson(){JSONObject j=new JSONObject();try{j.put("id",id);j.put("name",name);j.put("definingFeatures",new JSONArray(definingFeatures));j.put("members",new JSONArray(members));j.put("confidence",confidence);j.put("support",support);j.put("contradictions",contradictions);j.put("revisions",revisions);j.put("createdAt",createdAt);j.put("lastUpdatedAt",lastUpdatedAt);}catch(Exception ignored){}return j;}
  static Concept fromJson(JSONObject j){Concept c=new Concept();if(j==null)return c;c.id=j.optString("id","");c.name=j.optString("name","");JSONArray a=j.optJSONArray("definingFeatures");if(a!=null)for(int i=0;i<a.length();i++){String x=a.optString(i,"");if(!x.isEmpty())c.definingFeatures.add(x);}a=j.optJSONArray("members");if(a!=null)for(int i=0;i<a.length();i++){String x=a.optString(i,"");if(!x.isEmpty())c.members.add(x);}c.confidence=cl(j.optDouble("confidence",c.confidence));c.support=Math.max(0,j.optInt("support"));c.contradictions=Math.max(0,j.optInt("contradictions"));c.revisions=Math.max(0,j.optInt("revisions"));c.createdAt=j.optLong("createdAt");c.lastUpdatedAt=j.optLong("lastUpdatedAt");return c;}
 }
 public final Map<String,Profile> profiles=new LinkedHashMap<>();public final Map<String,Concept> concepts=new LinkedHashMap<>();public final Map<String,Long> evidenceCooldown=new LinkedHashMap<>();public long lastObservedAt;
 public Profile profile(String key){Profile p=profiles.computeIfAbsent(key,k->new Profile());if(p.key.isEmpty())p.key=key;return p;}
 public JSONObject toJson(){JSONObject j=new JSONObject();try{JSONObject p=new JSONObject();for(Map.Entry<String,Profile>e:profiles.entrySet())p.put(e.getKey(),e.getValue().toJson());j.put("profiles",p);JSONObject c=new JSONObject();for(Map.Entry<String,Concept>e:concepts.entrySet())c.put(e.getKey(),e.getValue().toJson());j.put("concepts",c);JSONObject cd=new JSONObject();for(Map.Entry<String,Long>e:evidenceCooldown.entrySet())cd.put(e.getKey(),e.getValue());j.put("evidenceCooldown",cd);j.put("lastObservedAt",lastObservedAt);}catch(Exception ignored){}return j;}
 public static PerceptualConceptState fromJson(JSONObject j){PerceptualConceptState s=new PerceptualConceptState();if(j==null)return s;JSONObject p=j.optJSONObject("profiles");if(p!=null){Iterator<String>it=p.keys();while(it.hasNext()){String k=it.next();Profile x=Profile.fromJson(p.optJSONObject(k));if(x.key.isEmpty())x.key=k;s.profiles.put(k,x);}}JSONObject c=j.optJSONObject("concepts");if(c!=null){Iterator<String>it=c.keys();while(it.hasNext()){String k=it.next();Concept x=Concept.fromJson(c.optJSONObject(k));if(x.id.isEmpty())x.id=k;s.concepts.put(k,x);}}JSONObject cd=j.optJSONObject("evidenceCooldown");if(cd!=null){Iterator<String>it=cd.keys();while(it.hasNext()){String k=it.next();s.evidenceCooldown.put(k,cd.optLong(k));}}s.lastObservedAt=j.optLong("lastObservedAt");return s;}
 public static double cl(double v){return Math.max(0,Math.min(1,v));}
}