package com.aicharacter.v3;
/** Range/goal gate shared by planned object actions. Action semantics choose the physical goal; geometry decides whether the body can reach it. */
public final class PhysicalInteraction{private PhysicalInteraction(){}
 public static float range(WorldObject o){return o==null?0:(o.interactionRadius>0?o.interactionRadius:Math.max(28,Math.min(72,o.width*.35f+20)));}
 public static float rangeForAction(WorldObject o,String action){if(o==null)return 0;if(requiresInterior(o,action)){float left=o.x+o.interiorLeftOffset,right=o.x+o.interiorRightOffset,target=interiorTarget(o);float margin=Math.min(target-left,right-target);return Math.max(12,Math.min(18,margin-2));}return range(o);}
 public static float reachableTargetX(WorldState s,WorldObject o,String actor,float actorX){return targetXForAction(s,o,actor,actorX,"");}
 public static float targetXForAction(WorldState s,WorldObject o,String actor,float actorX,String action){if(o==null)return actorX;if(requiresInterior(o,action)){float left=o.x+o.interiorLeftOffset,right=o.x+o.interiorRightOffset,desired=interiorTarget(o);if(!WholeBodyPhysicsEngine.blockedBetween(s,actor,actorX,desired))return desired;}return o.nearestReachableInteractionX(s,actor,actorX);}
 private static boolean requiresInterior(WorldObject o,String action){if(o==null||!o.hasInteriorZone())return false;return("REST_PROTECT".equals(action)&&o.tags.contains("shelter"))||"EAT".equals(action)||"DRINK".equals(action)||"TOILET".equals(action)||"PREPARE_HERB".equals(action)||"TRY_HERB".equals(action);}
 private static float interiorTarget(WorldObject o){float left=o.x+o.interiorLeftOffset,right=o.x+o.interiorRightOffset,center=(left+right)*.5f,preferred=o.interactionX==0?center:o.interactionX;float edgeInset=Math.min(18f,Math.max(4f,(right-left)*.18f));return Math.max(left+edgeInset,Math.min(right-edgeInset,preferred));}
 public static boolean inRange(WorldState s,WorldObject o){return inRangeForAction(s,o,"");}
 public static boolean inRangeForAction(WorldState s,WorldObject o,String action){if(s==null||o==null||s.world==null)return false;WorldArea a=s.world.areaAt(s.haruX);if(a==null||!a.id.equals(o.areaId))return false;if(requiresInterior(o,action))return o.containsInterior(s.haruX);float tx=targetXForAction(s,o,"girl",s.haruX,action);return !WholeBodyPhysicsEngine.blockedBetween(s,"girl",s.haruX,tx)&&Math.abs(s.haruX-tx)<=rangeForAction(o,action);}
 public static String trace(WorldState s,WorldObject o){if(s==null||o==null)return"target=<null> execute=false";float tx=reachableTargetX(s,o,"girl",s.haruX),d=Math.abs(s.haruX-tx),r=range(o);boolean clear=!WholeBodyPhysicsEngine.blockedBetween(s,"girl",s.haruX,tx);return"target="+o.id+" reachableX="+(int)tx+" currentX="+(int)s.haruX+" distance="+(int)d+" range="+(int)r+" clear="+clear+" execute="+(clear&&d<=r);}
}
