package com.aicharacter.v3;
/** Goal-aware life reconsideration. New needs/evidence can interrupt a plan without scripting a route or schedule. */
public final class PlanReconsiderationEngine{
 public enum Decision{CONTINUE,PAUSE,REPLAN,ABANDON}public static final class Result{public final Decision decision;public final String reason,supportive,contradictory;public final double pressure,support;Result(Decision d,String r,double p,double s,String sup,String con){decision=d;reason=r;pressure=p;support=s;supportive=sup;contradictory=con;}public boolean reconsider(){return decision!=Decision.CONTINUE;}}
 private PlanReconsiderationEngine(){}
 public static Result evaluate(WorldState s,long now){PlanState p=s.planState;if(p==null||!p.active())return out(p,Decision.CONTINUE,"no active plan",0,0,"","",now);NeedState n=NeedState.evaluate(s);double con=0,sup=0,urgent=0;StringBuilder ss=new StringBuilder(),cc=new StringBuilder();boolean outdoor=isOutdoorLeisure(p.intentionId),restGoal=isRestGoal(p.intentionId);WorldArea here=s.world==null?null:s.world.areaAt(s.haruX);double exposure=WorldSemantics.exposure(here);
  double bodilyPressure=Math.max(n.physicalComfort,n.safety*.75);if(bodilyPressure>38&&exposure>.35){if(restGoal){sup+=Math.min(.52,bodilyPressure/120.0);ss.append("body/environment needs support protection/rest; ");}else if(outdoor){con+=Math.min(.62,bodilyPressure/90.0);cc.append("physical comfort/safety needs weaken optional outdoor goal; ");}else if("find_cat".equals(p.intentionId)){if(n.safety>55||s.body.energy<22){con+=.34;urgent+=Math.min(.28,n.safety/250.0);cc.append("body/safety pressure competes with search; ");}else{sup+=.08;ss.append("connection goal remains meaningful despite discomfort; ");}}}
  if(s.girlTravel.interruption.startsWith("perceived_cat")){double rel=parseRel(s.girlTravel.interruption);if(!"find_cat".equals(p.intentionId)&&rel>.55){con+=.30+Math.min(.35,rel*.3);urgent+=rel>.9?.25:0;cc.append("locally perceived cat is relevant; ");}else ss.append("cat perception compatible with current goal; ");}
  double mobility=MusculoskeletalEngine.locomotorCapacity(s)*BodyInstinctEngine.movementCapacity(s)*NervousSystemEngine.locomotorConstraint(s);double regionalInjury=s.localizedPain==null?0:s.localizedPain.maxLoad();if(s.body.pain>20){con+=.32;cc.append("pain; ");if(s.body.pain>55)urgent+=.35;}if(!restGoal&&mobility<.58){con+=Math.min(.42,(.58-mobility)*1.05);cc.append("reduced mobility weakens continued travel; ");if(mobility<.40||regionalInjury>.62)urgent+=.24;}else if(restGoal&&mobility<.58){sup+=Math.min(.22,(.58-mobility)*.55);ss.append("reduced mobility supports recovery/protection; ");}if(regionalInjury>.35&&!restGoal){con+=Math.min(.28,(regionalInjury-.35)*.55);cc.append("localized injury conflicts with continued exertion; ");}if(s.body.energy<15&&!restGoal){con+=.48;urgent+=.12;cc.append("critical_energy; ");}else if(s.body.energy<28&&outdoor){con+=.22;cc.append("low_energy weakens optional outdoor goal; ");}
  if((s.relationship.hurt>55||s.relationship.irritation>55)&&"find_cat".equals(p.intentionId)&&s.mood.loneliness<.35){con+=.18;cc.append("relationship tension weakens connection seeking; ");}
  double learned=AdaptiveBeliefEngine.planExpectation(s,p.intentionId);if(learned<-.01){con+=(-learned)*.38;cc.append("learned failures weaken this plan; ");}else if(learned>.01){sup+=learned*.24;ss.append("experienced success supports this plan; ");}
  double progress=s.girlTravel.active?s.girlTravel.routeProgress():0,inertia=p.commitment*.45+progress*.42;double pressure=con+urgent-inertia*.35;if(sup>0){p.commitment=Math.min(.98,p.commitment+sup*.08);pressure-=sup*.28;}Decision d=Decision.CONTINUE;String reason="current plan remains causally coherent";
  if("find_cat".equals(p.intentionId)&&con+urgent>.72&&(n.safety>55||s.body.energy<22)){d=Decision.PAUSE;reason="temporary body/safety interruption; preserve search state";}else if(urgent>.42&&pressure>.38){d=Decision.PAUSE;reason="urgent local interruption; preserve plan for later cognition";}else if(pressure>.82&&learned<-.55&&progress<.70&&!"find_cat".equals(p.intentionId)){d=Decision.ABANDON;reason="new evidence plus learned failures make this goal no longer worth pursuing now";}else if(pressure>.62&&progress<.88){d=Decision.REPLAN;reason="current life plan is contradicted strongly enough to reconsider";}else if(progress>.88&&pressure<.9){reason="near completion inertia outweighs non-critical challenger";}
  return out(p,d,reason,Math.max(0,pressure),sup,ss.toString(),cc.toString(),now);}
 private static boolean isOutdoorLeisure(String id){return"reflect".equals(id)||"seek_solitude".equals(id)||"observe_lake".equals(id)||"explore_garden".equals(id)||"watch_reedling".equals(id)||"quiet_pause".equals(id);}
 private static boolean isRestGoal(String id){return"sleep".equals(id)||"seek_shelter".equals(id)||"recover".equals(id);}
 private static double parseRel(String x){try{int i=x.indexOf("relevance=");return i<0?0:Double.parseDouble(x.substring(i+10).trim());}catch(Exception e){return 0;}}
 private static Result out(PlanState p,Decision d,String r,double pressure,double support,String sup,String con,long now){if(p!=null){p.lastDecision=d.name()+": "+r;p.lastReason="support=["+sup+"] contradiction=["+con+"] pressure="+String.format(java.util.Locale.US,"%.2f",pressure);p.lastReconsideredAt=now;}return new Result(d,r,pressure,support,sup,con);}
}