package com.aicharacter.v3;
/** Arrival -> required physical target -> action -> outcome. Area arrival never implies object contact. */
public final class PlanExecutor{private PlanExecutor(){}
 public static void onArrival(WorldState s,TravelState travel,long now){PlanState p=s.planState;if(p==null||!"girl".equals(travel.actor)||!p.planId.equals(travel.currentPlanId))return;p.lastArrival=("LOCAL".equals(travel.travelMode)?travel.targetId:travel.destinationArea)+" @"+now;p.lastProgressAt=now;if("find_cat".equals(p.intentionId)){GirlCatSearchEngine.onArrival(s,now);return;}if("LOCAL".equals(travel.travelMode)){executeAction(s,now);return;}WorldObject target=resolveTarget(s,p);if(target!=null&&!PhysicalInteraction.inRange(s,target)){p.lastAction="approaching "+target.id;if(!TravelEngine.startLocal(s,s.girlTravel,"girl",target.id,target.x,PhysicalInteraction.range(target),p.planId,now)){p.status="FAILED";p.lastOutcome="object target not physically reachable";}return;}executeAction(s,now);}
 private static WorldObject resolveTarget(WorldState s,PlanState p){WorldObject t=s.world.object(p.destination);if(t!=null)return t;if("REST_PROTECT".equals(p.plannedAction))return s.world.firstTagged("shelter");if("REFLECT".equals(p.plannedAction))return s.world.firstTagged("reflect");return null;}
 public static void executeAction(WorldState s,long now){PlanState p=s.planState;if(p==null||!"ACTIVE".equals(p.status))return;String action=p.plannedAction;WorldObject target=resolveTarget(s,p);boolean needsObject="REST_PROTECT".equals(action)||"REFLECT".equals(action)||"OBSERVE".equals(action);if(needsObject&&(target==null||!PhysicalInteraction.inRange(s,target))){p.lastOutcome="blocked: target outside interaction range";if(target!=null)TravelEngine.startLocal(s,s.girlTravel,"girl",target.id,target.x,PhysicalInteraction.range(target),p.planId,now);return;}boolean ok=true;String outcome;if("REST_PROTECT".equals(action)){ok=WorldInteractionEngine.interact(s,target,"REST");if(ok){s.body.energy=Math.min(100,s.body.energy+8);s.body.sleepiness=Math.max(0,s.body.sleepiness-7);}outcome=ok?"protected and resting":"shelter interaction failed";}else if("REFLECT".equals(action)){ok=WorldInteractionEngine.interact(s,target,"REFLECT");if(ok)s.mood.pleasantness=Math.min(1,s.mood.pleasantness+.08);outcome=ok?"reflection completed":"reflection target unavailable";}else if("OBSERVE".equals(action)){ok=WorldInteractionEngine.interact(s,target,"OBSERVE");outcome=ok?"observation completed":"observation target unavailable";}else{outcome="no executable action: "+action;ok=false;}p.lastAction=action+" @"+now;p.lastOutcome=outcome;p.status=ok?"COMPLETED":"FAILED";if(ok)p.stepIndex=p.steps.size();CognitionEngine.process(s,new Experience("planned_action_outcome",p.intentionId+": "+outcome,ok?.12:-.12,ok?.42:.5).at(HaruPerception.currentPlaceId(s),target==null?p.destination:target.id).tag(p.intentionId).tag(ok?"success":"failure"));}
 public static void applyDecision(WorldState s,PlanReconsiderationEngine.Result r,long now){PlanState p=s.planState;if(p==null)return;if(r.decision==PlanReconsiderationEngine.Decision.CONTINUE)return;if(r.decision==PlanReconsiderationEngine.Decision.PAUSE){p.status="PAUSED";p.pausedAt=now;p.pauseReason=r.reason;s.girlTravel.active=false;return;}if(r.decision==PlanReconsiderationEngine.Decision.REPLAN){p.status="ACTIVE";if(!p.destination.isEmpty()&&!TravelEngine.start(s,s.girlTravel,"girl",p.destination,p.planId,now)){p.status="FAILED";p.lastOutcome="replan failed: no valid route";}}else{p.status="ABANDONED";s.girlTravel.active=false;}}
 public static boolean resume(WorldState s,long now){PlanState p=s.planState;if(p==null||!"PAUSED".equals(p.status))return false;boolean safe=!("RAIN".equals(s.environment.weather)&&s.environment.weatherIntensity>.55&&s.body.energy<22)&&s.body.energy>=18;if(!safe)return false;p.pauseReason="";p.lastDecision="RESUME";if("find_cat".equals(p.intentionId))return GirlCatSearchEngine.resume(s,now);p.status="ACTIVE";return TravelEngine.start(s,s.girlTravel,"girl",p.destination,p.planId,now);}
}
