package com.aicharacter.v3;
/** Goal-aware life reconsideration. New evidence can interrupt a plan without scripting a route or schedule. */
public final class PlanReconsiderationEngine{
 public enum Decision{CONTINUE,PAUSE,REPLAN,ABANDON}public static final class Result{public final Decision decision;public final String reason,supportive,contradictory;public final double pressure,support;Result(Decision d,String r,double p,double s,String sup,String con){decision=d;reason=r;pressure=p;support=s;supportive=sup;contradictory=con;}public boolean reconsider(){return decision!=Decision.CONTINUE;}}
 private PlanReconsiderationEngine(){}
 public static Result evaluate(WorldState s,long now){PlanState p=s.planState;if(p==null||!p.active())return out(p,Decision.CONTINUE,"no active plan",0,0,"","",now);double con=0,sup=0,urgent=0;StringBuilder ss=new StringBuilder(),cc=new StringBuilder();boolean heavy="RAIN".equals(s.environment.weather)&&s.environment.weatherIntensity>.55,outdoor=isOutdoorLeisure(p.intentionId);
  if(heavy){if("seek_shelter".equals(p.intentionId)||"sleep".equals(p.intentionId)||"recover".equals(p.intentionId)){sup+=.52;ss.append("bad_weather supports protection/rest +0.52; ");}else if(outdoor){con+=.66;cc.append("bad_weather contradicts outdoor goal +0.66; ");}else if("find_cat".equals(p.intentionId)){if(s.body.energy<22){con+=.42;urgent+=.2;cc.append("weather+low_energy interrupts search; ");}else{sup+=.12;ss.append("weather increases concern for cat; ");}}}
  if(s.girlTravel.interruption.startsWith("perceived_cat")){double rel=parseRel(s.girlTravel.interruption);if(!"find_cat".equals(p.intentionId)&&rel>.55){con+=.30+Math.min(.35,rel*.3);urgent+=rel>.9?.25:0;cc.append("locally perceived cat is relevant; ");}else ss.append("cat perception compatible with current goal; ");}
  if(s.body.pain>20){con+=.32;cc.append("pain; ");if(s.body.pain>55)urgent+=.35;}if(s.body.energy<15&&!isRestGoal(p.intentionId)){con+=.48;urgent+=.12;cc.append("critical_energy; ");}else if(s.body.energy<28&&outdoor){con+=.22;cc.append("low_energy weakens optional outdoor goal; ");}
  if((s.relationship.hurt>55||s.relationship.irritation>55)&&"find_cat".equals(p.intentionId)&&s.mood.loneliness<.35){con+=.18;cc.append("relationship tension weakens connection seeking; ");}
  double learned=AdaptiveBeliefEngine.planExpectation(s,p.intentionId);if(learned<-.01){con+=(-learned)*.38;cc.append("learned failures weaken this plan; ");}else if(learned>.01){sup+=learned*.24;ss.append("experienced success supports this plan; ");}
  double progress=s.girlTravel.active?s.girlTravel.routeProgress():0,inertia=p.commitment*.45+progress*.42;double pressure=con+urgent-inertia*.35;if(sup>0){p.commitment=Math.min(.98,p.commitment+sup*.08);pressure-=sup*.28;}Decision d=Decision.CONTINUE;String reason="current plan remains causally coherent";
  if("find_cat".equals(p.intentionId)&&con+urgent>.72&&s.body.energy<22){d=Decision.PAUSE;reason="temporary safety/body interruption; preserve search state";}else if(urgent>.42&&pressure>.38){d=Decision.PAUSE;reason="urgent local interruption; preserve plan for later cognition";}else if(pressure>.82&&learned<-.55&&progress<.70&&!"find_cat".equals(p.intentionId)){d=Decision.ABANDON;reason="new evidence plus learned failures make this goal no longer worth pursuing now";}else if(pressure>.62&&progress<.88){d=Decision.REPLAN;reason="current life plan is contradicted strongly enough to reconsider";}else if(progress>.88&&pressure<.9){reason="near completion inertia outweighs non-critical challenger";}
  return out(p,d,reason,Math.max(0,pressure),sup,ss.toString(),cc.toString(),now);}
 private static boolean isOutdoorLeisure(String id){return"reflect".equals(id)||"seek_solitude".equals(id)||"observe_lake".equals(id)||"explore_garden".equals(id)||"watch_reedling".equals(id)||"quiet_pause".equals(id);}
 private static boolean isRestGoal(String id){return"sleep".equals(id)||"seek_shelter".equals(id)||"recover".equals(id);}
 private static double parseRel(String x){try{int i=x.indexOf("relevance=");return i<0?0:Double.parseDouble(x.substring(i+10).trim());}catch(Exception e){return 0;}}
 private static Result out(PlanState p,Decision d,String r,double pressure,double support,String sup,String con,long now){if(p!=null){p.lastDecision=d.name()+": "+r;p.lastReason="support=["+sup+"] contradiction=["+con+"] pressure="+String.format(java.util.Locale.US,"%.2f",pressure);p.lastReconsideredAt=now;}return new Result(d,r,pressure,support,sup,con);}
}