package com.aicharacter.v3;
import java.util.Iterator;
public final class StateInvariantChecker{private static final int MAX_REPORTS=80;private StateInvariantChecker(){}
 public static void normalize(WorldState s,long now){if(s==null)return;if(s.body==null)s.body=new BodyState();if(s.relationship==null)s.relationship=RelationshipState.fromJson(null);if(s.emotion==null)s.emotion=new EmotionState();if(s.environment==null)s.environment=new EnvironmentState();if(s.runtime==null)s.runtime=new WorldRuntimeState();if(s.mood==null)s.mood=new MoodState();if(s.personality==null)s.personality=new PersonalityState();if(s.reedling==null)s.reedling=new CreatureState();if(s.nameState==null)s.nameState=new NameState();if(s.catState==null)s.catState=CatState.fromJson(null,s.catX,now);if(s.catSearch==null)s.catSearch=new GirlCatSearchEngine.SearchState();if(s.girlTravel==null)s.girlTravel=new TravelState();if(s.catTravel==null)s.catTravel=new TravelState();if(s.planState==null)s.planState=new PlanState();if(s.routeRuntime==null)s.routeRuntime=new RouteRuntimeState();if(s.godMemory==null)s.godMemory=new GodMemory();if(s.currentIntention==null)s.currentIntention="observe_lake";if(s.haruMood==null)s.haruMood="curious";if(s.haruActivity==null)s.haruActivity="walking";if(s.reunionContext==null)s.reunionContext="";if(s.persistentIntentionTarget==null)s.persistentIntentionTarget="";if(s.lastCaretakerCheckpoint==null)s.lastCaretakerCheckpoint="";if(s.lastOpenedAt<=0)s.lastOpenedAt=now;if(s.lastSimulatedAt<=0)s.lastSimulatedAt=s.lastOpenedAt;if(s.lastSavedAt<=0)s.lastSavedAt=s.lastOpenedAt;if(s.visibility<0||s.visibility>1||Double.isNaN(s.visibility))s.visibility=1;if(Double.isNaN(s.worldWetness)||s.worldWetness<0)s.worldWetness=0;trimOldest(s.worldHistory,180);trimOldest(s.caretakerLog,180);trimOldest(s.developerReports,MAX_REPORTS);trimOldest(s.thoughts,80);trimOldest(s.diary,60);trimOldest(s.godInbox,40);trimOldest(s.notificationEvents,24);while(s.processedLearningIds.size()>1024){Iterator<String>it=s.processedLearningIds.iterator();if(!it.hasNext())break;it.next();it.remove();}}
 private static <T> void trimOldest(java.util.List<T> list,int max){if(list==null)return;while(list.size()>max)list.remove(0);}
 public static boolean valid(WorldState s){if(s==null||s.world==null||s.catState==null||s.catTravel==null||s.catSearch==null)return false;boolean attached="girl".equals(s.catState.attachedToEntity);WorldArea ca=s.world.areaAt(s.catState.x),ga=s.world.areaAt(s.haruX);if(attached&&(ca==null||ga==null||!ca.id.equals(ga.id)))return false;if(attached&&s.catTravel.active)return false;if(attached&&!s.catState.carryKnownByGirl)return false;if(attached&&s.catSearch.active)return false;if("APPROACHING_GIRL".equals(s.catState.sleepMode)&&attached)return false;if("HOME".equals(s.catState.sleepMode)&&attached)return false;return true;}
 public static void repairOrReport(WorldState s,long now){normalize(s,now);if(valid(s))return;report(s,now);if(s.world==null)return;if("girl".equals(s.catState.attachedToEntity)){s.catTravel.active=false;s.catSearch.active=false;s.catState.carryKnownByGirl=true;CatOfflineEngine.followAttachment(s);if("APPROACHING_GIRL".equals(s.catState.sleepMode)||"HOME".equals(s.catState.sleepMode))s.catState.sleepMode="WITH_GIRL";}}
 private static void report(WorldState s,long now){s.developerReports.add(new DeveloperReport(now,"PERSISTENT_LIFE_INVARIANT","ERROR","PersistentLife","Impossible cat/search/attachment combination detected.","state contradiction","saveVersion="+WorldState.SAVE_VERSION,"recover attachment/search coherence without world reset"));while(s.developerReports.size()>MAX_REPORTS)s.developerReports.remove(0);}
}
