package com.aicharacter.v3;import java.util.*;
/** Physical travel. Segment geometry is captured once and never changes while progress belongs to it. */
public final class TravelEngine{private TravelEngine(){}private static final float GIRL_SPEED=92f,CAT_SPEED=105f;private static final double MAX_STEP_SECONDS=5.0;
 public static boolean start(WorldState s,TravelState t,String actor,String destination,String planId,long now){float x=currentX(s,actor);WorldArea a=s.world.areaAt(x);if(a==null)return false;List<String>r=WorldPathPlanner.route(s,actor,a.id,destination);if(r.isEmpty())return false;reset(t,actor,a.id,destination,planId,now);t.route.addAll(r);t.active=r.size()>1;t.topologyRevision=s.routeRuntime.topologyRevision;if(t.active)initRouteSegment(s,t,now);else arrive(s,t,now);WorldEventBus.publish(s,now,"TRAVEL_STARTED",planId,actor+" started physical travel to "+destination+".");return true;}
 public static boolean startLocal(WorldState s,TravelState t,String actor,String targetId,float targetX,float range,String planId,long now){float x=currentX(s,actor);WorldArea a=s.world.areaAt(x),b=s.world.areaAt(targetX);if(a==null||b==null||!a.id.equals(b.id))return false;reset(t,actor,a.id,a.id,planId,now);t.travelMode="LOCAL";t.targetType="OBJECT";t.targetId=targetId;t.interactionRange=Math.max(12,range);t.active=Math.abs(targetX-x)>t.interactionRange;t.segmentStartX=x;t.segmentEndX=targetX;t.segmentStartedAt=now;t.previousX=x;if(!t.active)arrive(s,t,now);return true;}
 private static void reset(TravelState t,String actor,String origin,String dest,String plan,long now){t.actor=actor;t.originArea=origin;t.destinationArea=dest;t.currentPlanId=plan;t.route.clear();t.routeIndex=0;t.progress=0;t.startedAt=now;t.active=false;t.interruption="";t.travelMode="ROUTE";t.targetType="AREA";t.targetId="";t.segmentStartX=Float.NaN;t.segmentEndX=Float.NaN;t.previousX=Float.NaN;t.lastDelta=0;t.lastSpeed=0;}
 private static void initRouteSegment(WorldState s,TravelState t,long now){WorldConnection c=WorldPathPlanner.connection(s.world,t.route.get(t.routeIndex),t.route.get(t.routeIndex+1));if(c==null){t.active=false;return;}float x=currentX(s,t.actor);t.segmentStartX=x;t.segmentEndX=c.entryX;t.segmentStartedAt=now;t.progress=0;t.previousX=x;}
 public static void advanceSeconds(WorldState s,TravelState t,double seconds,long now){if(!t.active||seconds<=0)return;double remain=Math.min(seconds,3600);int guard=0;while(t.active&&remain>0&&guard++<64){double step=Math.min(remain,MAX_STEP_SECONDS);if("ROUTE".equals(t.travelMode)&&!validateOrReplan(s,t,now))return;WorldConnection c="ROUTE".equals(t.travelMode)?WorldPathPlanner.connection(s.world,t.route.get(t.routeIndex),t.route.get(t.routeIndex+1)):null;if(!Float.isFinite(t.segmentStartX)||!Float.isFinite(t.segmentEndX)){if("ROUTE".equals(t.travelMode))initRouteSegment(s,t,now);else return;}double dist=Math.max(1,Math.abs(t.segmentEndX-t.segmentStartX));double sp=speed(s,t,c);t.lastSpeed=sp;double left=dist*(1-t.progress);double move=Math.min(left,sp*step);double used=move/sp;float oldX=currentX(s,t.actor);t.progress=(float)Math.min(1,t.progress+move/dist);float x=t.segmentStartX+(t.segmentEndX-t.segmentStartX)*t.progress;t.previousX=oldX;t.lastDelta=x-oldX;setX(s,t,x);t.distanceTravelled+=Math.abs(t.lastDelta);consumeBody(s,t,used);remain-=used;if("girl".equals(t.actor))TravelPerceptionEngine.sample(s,t,now);if(t.progress>=.999999f){setX(s,t,t.segmentEndX);if("LOCAL".equals(t.travelMode)){arrive(s,t,now);break;}String to=t.route.get(t.routeIndex+1);WorldEventBus.publish(s,now,"AREA_ENTERED",t.currentPlanId,t.actor+" entered "+to+" at connection anchor.");t.routeIndex++;if(t.routeIndex>=t.route.size()-1){arrive(s,t,now);break;}initRouteSegment(s,t,now);}if(used<=0)break;}}
 public static void advanceMinutes(WorldState s,TravelState t,double minutes,long now){advanceSeconds(s,t,minutes*60,now);}
 public static boolean validateOrReplan(WorldState s,TravelState t,long now){if(!t.active||!"ROUTE".equals(t.travelMode))return true;if(t.routeIndex>=t.route.size()-1)return false;WorldConnection c=WorldPathPlanner.connection(s.world,t.route.get(t.routeIndex),t.route.get(t.routeIndex+1));if(t.topologyRevision==s.routeRuntime.topologyRevision&&c!=null&&!s.routeRuntime.blocked(c.id))return true;return replan(s,t,now,"current connection invalid/topology changed");}
 private static boolean replan(WorldState s,TravelState t,long now,String why){String at=area(s,currentX(s,t.actor));List<String>r=WorldPathPlanner.route(s,t.actor,at,t.destinationArea);t.lastInvalidation=why+" @"+now;WorldEventBus.publish(s,now,"ROUTE_BLOCKED",t.currentPlanId,why);if(r.isEmpty()){t.active=false;t.interruption="route_failed";if("girl".equals(t.actor)){s.planState.status="FAILED";s.planState.lastOutcome="route invalid; no alternate path";}return false;}t.route.clear();t.route.addAll(r);t.routeIndex=0;t.topologyRevision=s.routeRuntime.topologyRevision;t.lastReplan="route-only replan from actual area "+at;t.clearSegment();initRouteSegment(s,t,now);WorldEventBus.publish(s,now,"ROUTE_REPLANNED",t.currentPlanId,t.actor+" replanned route without changing life destination.");return true;}
 private static double speed(WorldState s,TravelState t,WorldConnection c){double b="cat".equals(t.actor)?CAT_SPEED:GIRL_SPEED;if("girl".equals(t.actor)){b*=.72+.28*Math.max(.15,s.body.energy/100.0);b*=1-Math.min(.35,s.body.pain/180.0);if("girl".equals(s.catState.attachedToEntity))b*=.92;}else b*=.72+.28*Math.max(.15,s.catState.energy/100.0);if("RAIN".equals(s.environment.weather))b*=1-.22*s.environment.weatherIntensity;return Math.max(35,b);}
 private static void consumeBody(WorldState s,TravelState t,double sec){double cost=sec/3600.0*("RAIN".equals(s.environment.weather)?1.25:1);if("girl".equals(t.actor)){s.body.energy=Math.max(0,s.body.energy-cost*1.8);s.body.sleepiness=Math.min(100,s.body.sleepiness+cost*.7);}else{s.catState.energy=Math.max(0,s.catState.energy-cost*2);s.catState.sleepiness=Math.min(100,s.catState.sleepiness+cost*.8);}}
 private static void setX(WorldState s,TravelState t,float x){if("cat".equals(t.actor)){s.catState.x=x;s.catX=x;s.catState.areaId=area(s,x);}else{s.haruX=x;s.haruActivity="walking";CatOfflineEngine.followAttachment(s);}}
 private static void arrive(WorldState s,TravelState t,long now){t.active=false;t.progress=1;WorldEventBus.publish(s,now,"TRAVEL_ARRIVED",t.currentPlanId,t.actor+" physically arrived at "+("LOCAL".equals(t.travelMode)?t.targetId:t.destinationArea)+".");if("girl".equals(t.actor))PlanExecutor.onArrival(s,t,now);else CatOfflineEngine.onCatTravelArrival(s,t,now);}
 public static float currentX(WorldState s,String actor){return"cat".equals(actor)?s.catState.x:s.haruX;}private static String area(WorldState s,float x){WorldArea a=s.world.areaAt(x);return a==null?"":a.id;}
}
