package com.aicharacter.v3;import java.util.*;
/** Bounded local perception during movement. SYSTEM positions are only consulted after local-access checks. */
public final class TravelPerceptionEngine{private TravelPerceptionEngine(){}
 public static void sample(WorldState s,TravelState t,long now){if(!"girl".equals(t.actor)||!t.active)return;String area=area(s,s.haruX);if(area.isEmpty())return;StringBuilder trace=new StringBuilder();
  // Cat: same area + local range only. No adjacent-area omniscience.
  WorldArea ca=s.world.areaAt(s.catState.x);if(ca!=null&&area.equals(ca.id)){double dist=Math.abs(s.haruX-s.catState.x);if(dist<=180){double relevance=s.relationship.attachment/101.0+("RAIN".equals(s.environment.weather)&&!s.catState.awake?.35:0);notice(s,t,now,"cat","same_area range="+(int)dist,relevance,relevance>.55?"interrupt_candidate":"noticed",trace);if(relevance>.55){CognitionEngine.process(s,new Experience("saw_cat_on_path","She noticed the cat while travelling.",.12,.62).at(area,"cat").with("cat").tag("travel").tag("cat"));t.interruption="perceived_cat relevance="+fmt(relevance);}}}
  // Creature/object checks are bounded to current area and proximity; ordinary sightings do not cancel plans.
  for(WorldObject o:s.world.objects){if(!o.enabled||!area.equals(o.areaId)||Math.abs(o.x-s.haruX)>130)continue;if("creature".equals(o.type)){double rel=.18+s.personality.curiosity*.15;notice(s,t,now,o.id,"same_area proximity",rel,"noticed_no_interrupt",trace);if(rel>.3)CognitionEngine.process(s,new Experience("creature_seen_on_route","She noticed a small creature while walking.",.05,.28).at(area,o.id).tag("travel").tag("creature"));}else if(o.tags.contains("landmark")&&!seenRecently(s,o.id,now)){notice(s,t,now,o.id,"landmark proximity",.22,"noticed",trace);}}
  if(trace.length()>0)s.lastPerceptionTrace=trace.toString();}
 private static void notice(WorldState s,TravelState t,long now,String what,String context,double relevance,String effect,StringBuilder trace){trace.append(now).append(" perceived=").append(what).append(" area=").append(area(s,s.haruX)).append(" context=").append(context).append(" relevance=").append(fmt(relevance)).append(" effect=").append(effect).append('\n');t.lastPerceivedEvent=what+"/"+effect;}
 private static boolean seenRecently(WorldState s,String id,long now){for(int i=s.memories.size()-1;i>=0&&i>s.memories.size()-12;i--){MemoryEntry m=s.memories.get(i);if((m.participants.contains(id)||m.tags.contains(id))&&now-m.time<6*3600000L)return true;}return false;}
 private static String area(WorldState s,float x){WorldArea a=s.world.areaAt(x);return a==null?"":a.id;}private static String fmt(double d){return String.format(Locale.US,"%.2f",d);}
}
