package com.aicharacter.v3;import org.json.*;import java.util.*;
/** Persistent physical journey with immutable geometry for the active segment. */
public final class TravelState{
 public String actor="girl",originArea="",destinationArea="",currentPlanId="",interruption="",lastPerceivedEvent="",lastInvalidation="",lastReplan="",travelMode="ROUTE",targetType="AREA",targetId="";public final List<String> route=new ArrayList<>();public int routeIndex=0;public float progress=0,segmentStartX=Float.NaN,segmentEndX=Float.NaN,previousX=Float.NaN;public long startedAt=0,segmentStartedAt=0,expectedArrivalAt=0,topologyRevision=0;public boolean active=false;public double distanceTravelled=0,lastDelta=0,lastSpeed=0;public float interactionRange=0;
 public void clearSegment(){progress=0;segmentStartX=Float.NaN;segmentEndX=Float.NaN;segmentStartedAt=0;}
 public JSONObject toJson(){JSONObject j=new JSONObject();try{j.put("actor",actor);j.put("originArea",originArea);j.put("destinationArea",destinationArea);j.put("currentPlanId",currentPlanId);j.put("interruption",interruption);j.put("lastPerceivedEvent",lastPerceivedEvent);j.put("lastInvalidation",lastInvalidation);j.put("lastReplan",lastReplan);j.put("travelMode",travelMode);j.put("targetType",targetType);j.put("targetId",targetId);j.put("interactionRange",interactionRange);j.put("route",new JSONArray(route));j.put("routeIndex",routeIndex);j.put("progress",progress);j.put("segmentStartX",segmentStartX);j.put("segmentEndX",segmentEndX);j.put("previousX",previousX);j.put("startedAt",startedAt);j.put("segmentStartedAt",segmentStartedAt);j.put("expectedArrivalAt",expectedArrivalAt);j.put("topologyRevision",topologyRevision);j.put("active",active);j.put("distanceTravelled",distanceTravelled);j.put("lastDelta",lastDelta);j.put("lastSpeed",lastSpeed);}catch(Exception ignored){}return j;}
 public static TravelState fromJson(JSONObject j){TravelState t=new TravelState();if(j==null)return t;t.actor=j.optString("actor","girl");t.originArea=j.optString("originArea","");t.destinationArea=j.optString("destinationArea","");t.currentPlanId=j.optString("currentPlanId","");t.interruption=j.optString("interruption","");t.lastPerceivedEvent=j.optString("lastPerceivedEvent","");t.lastInvalidation=j.optString("lastInvalidation","");t.lastReplan=j.optString("lastReplan","");t.travelMode=j.optString("travelMode","ROUTE");t.targetType=j.optString("targetType","AREA");t.targetId=j.optString("targetId","");t.interactionRange=(float)j.optDouble("interactionRange",0);JSONArray a=j.optJSONArray("route");if(a!=null)for(int i=0;i<a.length();i++)t.route.add(a.optString(i));t.routeIndex=j.optInt("routeIndex",0);t.progress=(float)j.optDouble("progress",0);t.segmentStartX=(float)j.optDouble("segmentStartX",Double.NaN);t.segmentEndX=(float)j.optDouble("segmentEndX",Double.NaN);t.previousX=(float)j.optDouble("previousX",Double.NaN);t.startedAt=j.optLong("startedAt",0);t.segmentStartedAt=j.optLong("segmentStartedAt",0);t.expectedArrivalAt=j.optLong("expectedArrivalAt",0);t.topologyRevision=j.optLong("topologyRevision",0);t.active=j.optBoolean("active",false);t.distanceTravelled=j.optDouble("distanceTravelled",0);t.lastDelta=j.optDouble("lastDelta",0);t.lastSpeed=j.optDouble("lastSpeed",0);return t;}
 public String currentSegment(){return "LOCAL".equals(travelMode)?"local -> "+targetId:!active||routeIndex>=route.size()-1?destinationArea:route.get(routeIndex)+" -> "+route.get(routeIndex+1);}public double routeProgress(){if("LOCAL".equals(travelMode))return progress;if(route.size()<2)return active?0:1;return Math.min(1,(routeIndex+progress)/(route.size()-1.0));}
}
