package com.aicharacter.v3;
/** Focused V0.7.1 plan-integrity scenarios A-G. Runs on the supplied dev state. */
public final class V071DevTest{private V071DevTest(){}
 public static String run(WorldState s){StringBuilder b=new StringBuilder("V0.7.1 PLAN INTEGRITY TEST\n");long now=System.currentTimeMillis();
  // A arrival -> action -> completed
  s.haruX=WorldPathPlanner.center(s.world,"lakeside");LifeDecision reflect=new LifeDecision(new Intention("reflect",1,"curiosity","bench_lake_01","reflect",.4,now+10000));OfflineLifeEngine.beginDecision(s,reflect,now);TravelEngine.advanceMinutes(s,s.girlTravel,30,now+1000);b.append("A arrival/action: ").append("COMPLETED".equals(s.planState.status)&&!s.planState.lastOutcome.isEmpty()?"PASS":"FAIL "+s.planState.status).append('\n');
  // B shelter rain supports current goal
  s.haruX=WorldPathPlanner.center(s.world,"lakeside");LifeDecision shelter=new LifeDecision(new Intention("seek_shelter",1,"safety","shelter_01","stay dry",.9,now+10000));OfflineLifeEngine.beginDecision(s,shelter,now);s.environment.weather="RAIN";s.environment.weatherIntensity=.9;PlanReconsiderationEngine.Result rb=PlanReconsiderationEngine.evaluate(s,now+2);b.append("B shelter+rain: ").append(rb.decision==PlanReconsiderationEngine.Decision.CONTINUE?"PASS":"FAIL "+rb.decision).append('\n');
  // C outdoor reflect rain contradicts
  s.haruX=WorldPathPlanner.center(s.world,"home_shelter");OfflineLifeEngine.beginDecision(s,reflect,now+3);s.environment.weather="RAIN";s.environment.weatherIntensity=.9;PlanReconsiderationEngine.Result rc=PlanReconsiderationEngine.evaluate(s,now+4);b.append("C lakeside+rain reconsider: ").append(rc.decision!=PlanReconsiderationEngine.Decision.CONTINUE?"PASS "+rc.decision:"FAIL").append('\n');
  // D search local perception happens only after arrival
  s.environment.weather="CLEAR";s.environment.weatherIntensity=.1;s.catState.awake=false;s.catState.sleepStartedAt=now-3*3600000L;s.relationship.attachment=70;s.catState.x=WorldPathPlanner.center(s.world,"quiet_grove");s.catX=s.catState.x;s.haruX=WorldPathPlanner.center(s.world,"lakeside");s.catSearch=new GirlCatSearchEngine.SearchState();GirlCatSearchEngine.start(s,now+5,"dev");int before=s.catSearch.visited.size();TravelEngine.advanceMinutes(s,s.girlTravel,30,now+6);b.append("D search arrival before perception: ").append(s.catSearch.visited.size()>before?"PASS":"CHECK").append('\n');
  // E pause/resume
  s.catState.x=WorldPathPlanner.center(s.world,"quiet_grove");s.catX=s.catState.x;s.haruX=WorldPathPlanner.center(s.world,"lakeside");s.catSearch=new GirlCatSearchEngine.SearchState();GirlCatSearchEngine.start(s,now+7,"pause test");s.environment.weather="RAIN";s.environment.weatherIntensity=.9;s.body.energy=10;GirlCatSearchEngine.advance(s,now+8,0.1);boolean paused="PAUSED".equals(s.planState.status);s.environment.weather="CLEAR";s.body.energy=55;boolean resumed=PlanExecutor.resume(s,now+9);b.append("E pause/resume: ").append(paused&&resumed?"PASS":"CHECK paused="+paused+" resumed="+resumed).append('\n');
  // F near completion inertia
  s.planState=new PlanState();s.planState.status="ACTIVE";s.planState.planId="near";s.planState.intentionId="seek_shelter";s.planState.destination="shelter_01";s.planState.commitment=.7;s.girlTravel=new TravelState();s.girlTravel.active=true;s.girlTravel.route.add("garden_path");s.girlTravel.route.add("home_shelter");s.girlTravel.routeIndex=0;s.girlTravel.progress=.9f;s.girlTravel.destinationArea="home_shelter";s.environment.weather="CLOUDY";PlanReconsiderationEngine.Result rf=PlanReconsiderationEngine.evaluate(s,now+9);b.append("F near completion inertia: ").append(rf.decision==PlanReconsiderationEngine.Decision.CONTINUE?"PASS":"FAIL").append('\n');
  // G invalid route: isolated route should fail, never teleport
  s.haruX=WorldPathPlanner.center(s.world,"lakeside");java.util.List<String> saved=new java.util.ArrayList<>(s.world.area("garden_path").connections);s.world.area("garden_path").connections.clear();boolean path=TravelEngine.start(s,new TravelState(),"girl","home_shelter","broken",now+10);s.world.area("garden_path").connections.addAll(saved);b.append("G invalid route: ").append(!path?"PASS":"FAIL").append('\n');return b.toString();}
}
