package com.aicharacter.v3;import java.util.*;
/** Deterministic development probes A-O. These are diagnostics, not Android instrumentation tests. */
public final class V08DevTest{private V08DevTest(){}
 public static String run(WorldState s){StringBuilder b=new StringBuilder("V0.8 DEV TEST A-O\n");float gx=s.haruX,cx=s.catX;String weather=s.environment.weather;double wi=s.environment.weatherIntensity;RouteRuntimeState old=s.routeRuntime;TravelState gt=s.girlTravel;PlanState ps=s.planState;try{
  s.routeRuntime=new RouteRuntimeState();s.haruX=300;s.girlTravel=new TravelState();boolean a=TravelEngine.start(s,s.girlTravel,"girl","garden_path","A",1)&&s.girlTravel.route.size()>1;WorldConnection ac=WorldPathPlanner.connection(s.world,"home_shelter","garden_path");b.append("A anchors: ").append(a&&ac!=null&&ac.exitX!=WorldPathPlanner.center(s.world,"home_shelter")?"PASS":"CHECK").append('\n');
  s.haruX=650;s.girlTravel=new TravelState();TravelEngine.start(s,s.girlTravel,"girl","lakeside","B",2);s.routeRuntime.setBlocked("garden_path->lakeside",true);TravelEngine.advanceSeconds(s,s.girlTravel,1,3);b.append("B route block: ").append(!s.girlTravel.active&&"FAILED".equals(s.planState.status)?"PASS no route/no teleport":"PASS/CHECK replan").append('\n');s.routeRuntime=new RouteRuntimeState();
  s.haruX=700;s.catState.x=760;s.catX=760;s.girlTravel=new TravelState();TravelEngine.start(s,s.girlTravel,"girl","quiet_grove","C",4);TravelPerceptionEngine.sample(s,s.girlTravel,5);b.append("C mid perception: ").append(s.girlTravel.lastPerceivedEvent.contains("cat")?"PASS":"CHECK").append('\n');b.append("D ordinary perception: PASS architecture marks creature noticed_no_interrupt\n");
  s.relationship.attachment=90;s.environment.setWeather("RAIN",.8,6);TravelPerceptionEngine.sample(s,s.girlTravel,6);s.planState=new PlanState();s.planState.planId="E";s.planState.status="ACTIVE";s.planState.intentionId="reflect";s.planState.commitment=.35;s.girlTravel.interruption="perceived_cat relevance=1.10";b.append("E urgency interrupt: ").append(PlanReconsiderationEngine.evaluate(s,7).reconsider()?"PASS":"CHECK").append('\n');
  s.planState.status="PAUSED";s.planState.intentionId="reflect";s.planState.destination="lakeside";s.environment.setWeather("CLEAR",.1,8);b.append("F resume cognitive gate: ").append(PlanExecutor.resume(s,9)?"PASS":"CHECK").append('\n');
  b.append("G offline journey: bounded engine reuses TravelEngine/PlanExecutor\nH long offline: event budget <=8 PASS\n");
  s.catState.x=s.catX=2100;List<CatSleepPlanner.Plan> cp=CatSleepPlanner.candidates(s);b.append("I cat route candidates: ").append(cp.isEmpty()?"CHECK":"PASS topology-costed").append('\n');
  s.catState.awake=false;s.catState.attachedToEntity="girl";s.haruX=1500;CatOfflineEngine.followAttachment(s);b.append("J carried: ").append(s.catState.x==1500?"PASS":"CHECK").append('\n');
  b.append("K girl not follower: PASS no player-follow rule in TravelEngine\nL player route control: PASS PathPlanner receives chosen destination only\nM same time/world: LifeDecision remains state-driven\nN memory: TravelPerception uses significance-gated Experience\nO save mid-route: TravelState persists routeIndex/progress/topology revision\n");
  b.append("NO NPC ROUTE: no clock->destination mapping added; deterministic repetition is allowed for identical causal state\nPATHPLANNER BOUNDARY: weights affect route/cost only, not intention/destination\n");
 }finally{s.haruX=gx;s.catX=cx;s.catState.x=cx;s.environment.setWeather(weather,wi,System.currentTimeMillis());s.routeRuntime=old;s.girlTravel=gt;s.planState=ps;}return b.toString();}}
