package com.aicharacter.v3;
/** Executable V0.98 assertions. Methods throw on failed evaluated conditions. */
public final class V098DevTest {private V098DevTest(){}
 public static void learningOnce(WorldState s,long now){MemoryEntry m=new MemoryEntry(now,"outcome","calm lake rest",.7,.5,.9,"lakeside",null,java.util.Arrays.asList("rest"));boolean first=CharacterLearningEngine.learnOutcome(s,m,"v098_same_exp"),second=CharacterLearningEngine.learnOutcome(s,m,"v098_same_exp");if(!first||second)throw new IllegalStateException("learning replay was not idempotent");}
 public static void weatherChangesDecision(WorldState s,long now){s.environment.weather="CLEAR";s.environment.weatherIntensity=.1;EnvironmentConsequences.advance(s,5);LifeDecisionEngine.choose(s,now);double clear=score(s,"reflect");s.environment.weather="RAIN";s.environment.weatherIntensity=.95;EnvironmentConsequences.advance(s,5);LifeDecisionEngine.choose(s,now+1);double rain=score(s,"reflect");if(Math.abs(clear-rain)<5)throw new IllegalStateException("weather consequence too weak "+clear+"/"+rain);}
 public static void creatureIsPhysical(WorldState s,long now){s.haruX=300;s.reedling.areaId="lakeside";s.reedling.x=1400;if(CreatureLifeEngine.perceivable(s))throw new IllegalStateException("remote creature perceived");s.haruX=1400;s.visibility=1;if(!CreatureLifeEngine.perceivable(s))throw new IllegalStateException("local creature not perceived");}
 public static void objectRange(WorldState s){WorldObject b=s.world.object("bench_lake_01");s.haruX=b.x-400;if(PhysicalInteraction.inRange(s,b))throw new IllegalStateException("remote bench interaction");s.haruX=b.x;if(!PhysicalInteraction.inRange(s,b))throw new IllegalStateException("near bench unavailable");}
 public static void noMagicAttach(WorldState s,long now){s.catState.attachedToEntity="";s.catState.areaId="home_shelter";s.catState.x=300;s.catX=300;s.haruX=1500;CatOfflineEngine.beginSleep(s,now);if("girl".equals(s.catState.attachedToEntity)&&Math.abs(s.catX-s.haruX)>90)throw new IllegalStateException("magic attachment");}
 public static void invariants(WorldState s){java.util.List<String> x=WorldIntegrityChecker.check(s);if(!x.isEmpty())throw new IllegalStateException("world invariant: "+x);}
 private static double score(WorldState s,String id){String t=s.lastDecisionTrace;int i=t.indexOf("- "+id);if(i<0)return -999;int p=t.indexOf(" total=",i),e=t.indexOf('\n',p);return Double.parseDouble(t.substring(p+7,e));}
}
