package com.aicharacter.v3;
import org.json.JSONObject;import java.util.*;
/** Safe data caretaker. Haru cognition/personality are outside its writable domain. */
public final class WorldCaretaker {
 public static final int MAX_REPAIR_ATTEMPTS=8;
 public static final class Result{public final int attempted,kept,rolledBack,reported;public final String message;Result(int a,int k,int r,int d,String m){attempted=a;kept=k;rolledBack=r;reported=d;message=m;}}
 private WorldCaretaker(){}
 public static List<WorldIssue> evaluate(WorldState s){String obs="obs-"+System.currentTimeMillis();List<WorldIssue>x=WorldEvaluator.evaluate(s);log(s,"OBSERVED",WorldSnapshot.observe(s).summary(),obs,"","");for(WorldIssue i:x)log(s,"ISSUE_DETECTED",i.toString()+" score="+i.priorityScore(),obs,"","");return x;}
 public static Result repairPrioritized(WorldState s){return repairPrioritized(s,false);}
 public static Result autoRepairSafe(WorldState s){return repairPrioritized(s,true);}
 private static Result repairPrioritized(WorldState s,boolean automatic){List<WorldIssue> initial=automatic?WorldEvaluator.evaluate(s):evaluate(s);if(initial.isEmpty())return new Result(0,0,0,0,"World state is healthy; no repair required.");int attempted=0,kept=0,rolled=0,reports=0;Set<String> seen=new HashSet<>();
  while(attempted<MAX_REPAIR_ATTEMPTS){List<WorldIssue> issues=WorldEvaluator.evaluate(s);WorldIssue target=null;for(WorldIssue i:issues)if(!seen.contains(i.key())&&(!automatic||autoRepairAllowed(i))){target=i;break;}if(target==null)break;seen.add(target.key());attempted++;
   if(!target.safeRepair){if(!automatic){report(s,target);reports++;}continue;}String obs="obs-"+System.currentTimeMillis();try{RepairTransaction tx=new RepairTransaction(obs,target,s);s.lastCaretakerCheckpoint=tx.beforeJson;log(s,"CHECKPOINT","before="+WorldSnapshot.observe(s).summary(),obs,tx.id,"");int beforeWorst=WorldEvaluator.worstSeverity(issues);apply(s,target);List<WorldIssue> after=WorldEvaluator.evaluate(s);boolean fixed=!WorldEvaluator.containsKey(after,target.key());boolean worse=WorldEvaluator.worstSeverity(after)>beforeWorst;boolean invariants=s.world!=null&&!s.world.areas.isEmpty();if(fixed&&!worse&&invariants){kept++;s.runtime.capture(s.world);history(s,"SYSTEM_REPAIR",target.entityId,"SYSTEM safely repaired "+target.id);log(s,"VERIFIED",target.key()+" fixed; no worse severity introduced",obs,tx.id,"KEEP");}else{restoreInto(tx.restore(),s);rolled++;log(s,"VERIFIED","targetFixed="+fixed+" worse="+worse+" invariants="+invariants,obs,tx.id,"ROLLBACK");}}
   catch(Exception e){reports++;DeveloperReport r=new DeveloperReport(System.currentTimeMillis(),"CARETAKER","HIGH","RepairTransaction",e.toString(),"Transaction failure","issue="+target.key(),"Inspect transaction and persistence path.");s.developerReports.add(r);}
  }return new Result(attempted,kept,rolled,reports,"Caretaker: attempted="+attempted+", KEEP="+kept+", ROLLBACK="+rolled+", developerReports="+reports);}
 private static boolean autoRepairAllowed(WorldIssue i){if(i==null||!i.safeRepair)return false;switch(i.repairType){case"CLAMP_HARU":case"CLAMP_CAT":case"MOVE_PROP_INSIDE":case"CLAMP_LIGHT":case"RESET_WEATHER":case"CLAMP_BODY":return true;default:return false;}}
 public static boolean rollback(WorldState s){if(s.lastCaretakerCheckpoint==null||s.lastCaretakerCheckpoint.isEmpty())return false;try{WorldState old=WorldState.fromJson(new JSONObject(s.lastCaretakerCheckpoint));restoreInto(old,s);s.lastCaretakerCheckpoint="";log(s,"MANUAL_ROLLBACK","Restored latest caretaker checkpoint","","","ROLLBACK");return true;}catch(Exception e){return false;}}
 private static void apply(WorldState s,WorldIssue i){switch(i.repairType){case"CLAMP_HARU":s.haruX=nearestSafe(s,s.haruX);break;case"CLAMP_CAT":s.catX=nearestSafe(s,s.catX);break;case"MOVE_PROP_INSIDE":WorldObject o=s.world.object(i.entityId);WorldArea a=o==null?null:s.world.area(o.areaId);if(o!=null&&a!=null)o.x=Math.max(a.left+24,Math.min(a.right-24,o.x));break;case"CLAMP_LIGHT":s.environment.ambientBrightness=Math.max(0,Math.min(1,s.environment.ambientBrightness));break;case"RESET_WEATHER":s.environment.setWeather("CLEAR",.1,System.currentTimeMillis());break;case"CLAMP_BODY":s.body.clamp();break;default:throw new SecurityException("Unsafe repair blocked: "+i.repairType);}}
 private static float nearestSafe(WorldState s,float x){float best=s.world.areas.get(0).left+24,min=Float.MAX_VALUE;for(WorldArea a:s.world.areas){float c=Math.max(a.left+12,Math.min(a.right-12,x)),d=Math.abs(c-x);if(d<min){min=d;best=c;}}return best;}
 private static void restoreInto(WorldState a,WorldState b){b.catX=a.catX;b.haruX=a.haruX;b.environment=a.environment;b.runtime=a.runtime;b.body=a.body;b.lastCaretakerCheckpoint=a.lastCaretakerCheckpoint;b.devForceRepairRegression=false;b.runtime.mergeDefinition(b.world);}
 private static void report(WorldState s,WorldIssue i){s.developerReports.add(new DeveloperReport(System.currentTimeMillis(),i.domain,i.severity,"WorldEvaluator",i.description,"Unsafe/core configuration","entity="+i.entityId,"Developer inspection required; executable modification forbidden."));log(s,"DEVELOPER_REPORT",i.key(),"","","ESCALATED");}
 private static void history(WorldState s,String type,String entity,String summary){s.worldHistory.add(new WorldHistoryEntry(System.currentTimeMillis(),type,entity,summary));while(s.worldHistory.size()>120)s.worldHistory.remove(0);}
 private static void log(WorldState s,String e,String d,String o,String tx,String result){s.caretakerLog.add(new CaretakerLogEntry(System.currentTimeMillis(),e,d,o,tx,result));while(s.caretakerLog.size()>180)s.caretakerLog.remove(0);}
 public static void injectScenario(WorldState s,int test){if(test==1){WorldObject o=s.world.object("bench_lake_01");if(o!=null)o.x=2250;}else if(test==2)s.environment.ambientBrightness=1.8;else if(test==3)s.haruX=-900;else if(test==4){WorldObject o=s.world.object("lake_tree_03");if(o!=null)o.assetRef="";}else if(test==5){s.environment.ambientBrightness=-.4;s.devForceRepairRegression=true;}log(s,"DEV_TEST_INJECTED","scenario="+test,"","","");}
}
