package com.aicharacter.v3;import java.util.*;
/** Route-only Dijkstra. Never chooses life destination. */
public final class WorldPathPlanner{private WorldPathPlanner(){}
 public static WorldConnection connection(WorldModel w,String from,String to){WorldArea a=w.area(from),b=w.area(to);if(a==null||b==null||!a.connections.contains(to))return null;boolean right=b.left>=a.right;float exit=right?a.right-12:a.left+12,entry=right?b.left+12:b.right-12;double weather=(a.weatherExposed||b.weatherExposed)?.32:.05;double safety=(a.tags.contains("safe")||b.tags.contains("safe"))?.85:.65;return new WorldConnection(from,to,exit,entry,weather,safety,"walk");}
 public static double cost(WorldState s,WorldConnection c,String actor){if(c==null||s.routeRuntime.blocked(c.id))return Double.POSITIVE_INFINITY;double cost=c.baseCost;boolean bad="RAIN".equals(s.environment.weather);if(bad)cost*=1+c.weatherSensitivity*s.environment.weatherIntensity;if("girl".equals(actor)){cost*=1+Math.max(0,30-s.body.energy)/100.0+Math.max(0,s.body.pain)/250.0;}else cost*=1+Math.max(0,35-s.catState.energy)/90.0;if(s.worldMinutes<330||s.worldMinutes>1260)cost*=1.08;return cost;}
 public static List<String> route(WorldState s,String actor,String start,String dest){ArrayList<String> none=new ArrayList<>();if(s.world==null||s.world.area(start)==null||s.world.area(dest)==null)return none;if(start.equals(dest)){none.add(start);return none;}Map<String,Double>d=new HashMap<>();Map<String,String>prev=new HashMap<>();PriorityQueue<String>q=new PriorityQueue<>(Comparator.comparingDouble(x->d.getOrDefault(x,Double.POSITIVE_INFINITY)));d.put(start,0.0);q.add(start);while(!q.isEmpty()){String x=q.poll();if(x.equals(dest))break;WorldArea a=s.world.area(x);for(String n:a.connections){WorldConnection c=connection(s.world,x,n);double edge=cost(s,c,actor);if(!Double.isFinite(edge))continue;double nd=d.get(x)+edge;if(nd<d.getOrDefault(n,Double.POSITIVE_INFINITY)){d.put(n,nd);prev.put(n,x);q.remove(n);q.add(n);}}}if(!d.containsKey(dest))return none;ArrayList<String>r=new ArrayList<>();for(String at=dest;at!=null;at=prev.get(at))r.add(at);Collections.reverse(r);return r;}
 public static List<String> route(WorldModel w,String start,String dest){WorldState s=WorldState.fresh();s.world=w;return route(s,"girl",start,dest);}public static boolean accessible(WorldModel w,String a,String b){return !route(w,a,b).isEmpty();}
 public static double routeCost(WorldState s,String actor,String start,String dest){List<String>r=route(s,actor,start,dest);if(r.isEmpty())return Double.POSITIVE_INFINITY;double x=0;for(int i=0;i<r.size()-1;i++)x+=cost(s,connection(s.world,r.get(i),r.get(i+1)),actor);return x;}
 public static float center(WorldModel w,String id){WorldArea a=w.area(id);return a==null?0:(a.left+a.right)/2f;}
}
