package com.aicharacter.v3;

import android.content.Context;import org.json.JSONObject;import java.io.File;import java.io.FileInputStream;import java.io.FileOutputStream;import java.io.ByteArrayOutputStream;import java.io.IOException;import java.nio.charset.StandardCharsets;
/** Atomic-ish private world save with last-known-good backup recovery. */
public final class WorldRepository{
 private final File saveFile,backupFile,tmpFile;private final Context context;
 public WorldRepository(Context context){this.context=context.getApplicationContext();File dir=new File(this.context.getFilesDir(),"world");if(!dir.exists()&&!dir.mkdirs())throw new IllegalStateException("Could not create private world directory");saveFile=new File(dir,"world.json");backupFile=new File(dir,"world.backup.json");tmpFile=new File(dir,"world.tmp");}
 public synchronized WorldState loadOrCreate(){WorldState state=tryLoad(saveFile);boolean recovered=false;if(state==null){state=tryLoad(backupFile);recovered=state!=null;}if(state==null)state=WorldState.fresh();attachDefinition(state);if(recovered||!saveFile.exists())save(state);else if(tmpFile.exists())tmpFile.delete();return state;}
 private WorldState tryLoad(File f){if(!f.exists()||!f.isFile()||f.length()<=0)return null;try(FileInputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream((int)Math.min(f.length(),1024L*1024L))){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);return WorldState.fromJson(new JSONObject(new String(out.toByteArray(),StandardCharsets.UTF_8)));}catch(Exception ignored){return null;}}
 public synchronized void save(WorldState state){try{if(state==null)throw new IOException("World state is null");if(state.world==null)attachDefinition(state);state.runtime.capture(state.world);state.lastSavedAt=System.currentTimeMillis();byte[] data=state.toJson().toString(2).getBytes(StandardCharsets.UTF_8);if(tmpFile.exists()&&!tmpFile.delete())throw new IOException("Could not clear stale temporary world save");try(FileOutputStream out=new FileOutputStream(tmpFile)){out.write(data);out.getFD().sync();}if(tryLoad(tmpFile)==null)throw new IOException("Temporary world save failed validation");if(saveFile.exists()&&tryLoad(saveFile)!=null)copy(saveFile,backupFile);if(!tmpFile.renameTo(saveFile)){copy(tmpFile,saveFile);if(tmpFile.exists()&&!tmpFile.delete())tmpFile.deleteOnExit();}if(tryLoad(saveFile)==null)throw new IOException("Committed world save failed validation");}catch(Exception e){throw new IllegalStateException("Could not persist VNF world",e);}}
 private void attachDefinition(WorldState state){state.world=WorldDefinitionLoader.load(context);state.runtime.mergeDefinition(state.world);}
 private static void copy(File from,File to)throws IOException{try(FileInputStream in=new FileInputStream(from);FileOutputStream out=new FileOutputStream(to)){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);out.getFD().sync();}}
}
