package com.aicharacter.v3;
import org.json.JSONObject;import org.json.JSONArray;import java.util.ArrayList;import java.util.List;
/** Stable System-Reality entity; authored technical metadata stays outside Haru cognition. */
public final class WorldObject {
 public String id,type,areaId,assetRef,haruDescription,tags,renderLayer,habitat,safeEditable,state;public float x,y,width,height,interactionX,interactionRadius,colliderOffsetX,colliderWidth;public boolean enabled=true,interactable,collision;public final List<float[]> colliderSegments=new ArrayList<>();
 public WorldObject(String id,String type,String area,String asset,String haru,float x,float y,float w,float h,String tags){this.id=id;this.type=type;areaId=area;assetRef=asset;haruDescription=haru;this.x=x;this.y=y;this.width=w;this.height=h;this.interactionX=x;this.interactionRadius=Math.max(28,Math.min(72,w*.35f+20));this.tags=tags;state="normal";renderLayer="WORLD_PROPS";habitat="";safeEditable="position,enabled";}
 public float collisionCenterX(){return x+colliderOffsetX;} public float collisionLeft(){float w=colliderWidth>0?colliderWidth:Math.max(0,width);return collisionCenterX()-w*.5f;} public float collisionRight(){float w=colliderWidth>0?colliderWidth:Math.max(0,width);return collisionCenterX()+w*.5f;} public List<float[]> collisionIntervals(){if(!colliderSegments.isEmpty())return colliderSegments;List<float[]>r=new ArrayList<>();r.add(new float[]{collisionLeft(),collisionRight()});return r;}
 public float nearestReachableInteractionX(WorldState s,String actor,float fromX){float desired=interactionX==0?x:interactionX;if(!collision||s==null)return desired;if(!WholeBodyPhysicsEngine.blockedBetween(s,actor,fromX,desired))return desired;float radius=WorldUnits.mToPx("cat".equals(actor)?.16:.22),best=Float.NaN;double bestD=Double.MAX_VALUE;for(float[]seg:collisionIntervals()){if(seg==null||seg.length<2)continue;float[]candidates=new float[]{seg[0]-radius-1,seg[1]+radius+1};for(float v:candidates){if(WholeBodyPhysicsEngine.blockedBetween(s,actor,fromX,v))continue;double d=Math.abs(v-desired);if(d<bestD){bestD=d;best=v;}}}return Float.isFinite(best)?best:desired;}
 public static WorldObject fromJson(JSONObject j){WorldObject o=new WorldObject(j.optString("id"),j.optString("type"),j.optString("areaId"),j.optString("assetRef"),j.optString("haruDescription",j.optString("perceptionName")),(float)j.optDouble("x"),(float)j.optDouble("ground",j.optDouble("y",846)),(float)j.optDouble("width"),(float)j.optDouble("height"),j.optString("tags"));o.enabled=j.optBoolean("enabled",true);o.interactable=j.optBoolean("interactable",false);o.collision=j.optBoolean("collision",false);o.renderLayer=j.optString("renderLayer","WORLD_PROPS");o.habitat=j.optString("habitat","");o.safeEditable=j.optString("safeEditable","position,enabled");o.state=j.optString("state","normal");o.interactionX=(float)j.optDouble("interactionX",o.x);o.interactionRadius=(float)j.optDouble("interactionRadius",o.interactionRadius);o.colliderOffsetX=(float)j.optDouble("colliderOffsetX",0);o.colliderWidth=(float)j.optDouble("colliderWidth",0);JSONArray seg=j.optJSONArray("colliderSegments");if(seg!=null)for(int i=0;i<seg.length();i++){JSONArray a=seg.optJSONArray(i);if(a!=null&&a.length()>=2){float l=o.x+(float)a.optDouble(0),r=o.x+(float)a.optDouble(1);if(r>l)o.colliderSegments.add(new float[]{l,r});}}return o;}
}
