package com.aicharacter.v3;

import android.content.Context;import org.json.JSONObject;import java.io.File;import java.io.FileInputStream;import java.io.FileOutputStream;import java.io.ByteArrayOutputStream;import java.io.IOException;import java.nio.charset.StandardCharsets;
/** Atomic-ish private world save with last-known-good backup recovery. */
public final class WorldRepository{
 private final File saveFile,backupFile,tmpFile;private final Context context;
 public WorldRepository(Context context){this.context=context.getApplicationContext();File dir=new File(this.context.getFilesDir(),"world");if(!dir.exists()&&!dir.mkdirs())throw new IllegalStateException("Could not create private world directory");saveFile=new File(dir,"world.json");backupFile=new File(dir,"world.backup.json");tmpFile=new File(dir,"world.tmp");}
 public synchronized WorldState loadOrCreate(){long now=System.currentTimeMillis();WorldState primary=tryLoad(saveFile),backup=tryLoad(backupFile);WorldState state=primary;boolean recovered=false;if(state==null&&backup!=null){state=backup;recovered=true;}else if(state!=null&&backup!=null&&isCausallyNewer(backup,state)){state=backup;recovered=true;}if(state==null)state=WorldState.fresh();StateInvariantChecker.normalize(state,now);attachDefinition(state);StateInvariantChecker.repairOrReport(state,now);if(recovered||!saveFile.exists())save(state);else if(tmpFile.exists())tmpFile.delete();return state;} private static boolean isCausallyNewer(WorldState a,WorldState b){if(a==null)return false;if(b==null)return true;long ac=Math.max(a.lastSimulatedAt,a.lastOpenedAt),bc=Math.max(b.lastSimulatedAt,b.lastOpenedAt);return ac>bc||(ac==bc&&a.lastSavedAt>b.lastSavedAt);}
 private WorldState tryLoad(File f){if(!f.exists()||!f.isFile()||f.length()<=0)return null;try(FileInputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream((int)Math.min(f.length(),1024L*1024L))){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);WorldState state=WorldState.fromJson(new JSONObject(new String(out.toByteArray(),StandardCharsets.UTF_8)));StateInvariantChecker.normalize(state,System.currentTimeMillis());return state;}catch(Exception ignored){return null;}}
 public synchronized void save(WorldState state){try{if(state==null)throw new IOException("World state is null");long wallNow=System.currentTimeMillis(),priorSaved=state.lastSavedAt;StateInvariantChecker.normalize(state,wallNow);if(state.world==null)attachDefinition(state);StateInvariantChecker.repairOrReport(state,wallNow);state.runtime.capture(state.world);state.lastSavedAt=Math.max(priorSaved,wallNow);byte[] data=state.toJson().toString(2).getBytes(StandardCharsets.UTF_8);if(tmpFile.exists()&&!tmpFile.delete())throw new IOException("Could not clear stale temporary world save");try(FileOutputStream out=new FileOutputStream(tmpFile)){out.write(data);out.getFD().sync();}if(tryLoad(tmpFile)==null)throw new IOException("Temporary world save failed validation");if(saveFile.exists()&&tryLoad(saveFile)!=null)copy(saveFile,backupFile);if(!tmpFile.renameTo(saveFile)){copy(tmpFile,saveFile);if(tmpFile.exists()&&!tmpFile.delete())tmpFile.deleteOnExit();}if(tryLoad(saveFile)==null)throw new IOException("Committed world save failed validation");}catch(Exception e){throw new IllegalStateException("Could not persist VNF world",e);}}
 private void attachDefinition(WorldState state){state.world=WorldDefinitionLoader.load(context);state.runtime.mergeDefinition(state.world);}
 private static void copy(File from,File to)throws IOException{try(FileInputStream in=new FileInputStream(from);FileOutputStream out=new FileOutputStream(to)){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);out.getFD().sync();}}
}
